// Disclaimer
//
// This work (specification and/or software implementation) and the material
// contained in it, as released by AUTOSAR, is for the purpose of information
// only. AUTOSAR and the companies that have contributed to it shall not be
// liable for any use of the work.
//
// The material contained in this work is protected by copyright and other
// types of intellectual property rights. The commercial exploitation of the
// material contained in this work requires a license to such intellectual
// property rights.
//
// This work may be utilized or reproduced without any modification, in any
// form or by any means, for informational purposes only. For any other
// purpose, no part of the work may be utilized or reproduced, in any form
// or by any means, without permission in writing from the publisher.
//
// The work has been developed for automotive applications only. It has
// neither been developed, nor tested for non-automotive applications.
//
// The word AUTOSAR and the AUTOSAR logo are registered trademarks.
// --------------------------------------------------------------------------

/// ================================================================
///
/// File description:
/// ----------------
/// @file       isoft_common_api.h
/// @brief      AutoSar-AP
/// @details    Some common methods
/// @date       2021-07-14
/// @author     hanjingjing
/// @version    1.2.0
///
/// ================================================================
///
/// @par Modification log:
/// <table>
/// <tr><th>Date        <th>Version  <th>Author      <th>Description
/// </table>
///
/// ================================================================
///
/// @code{.isoft}
/// @module_path=/CRYPTO/Reusable Functions/Reusable Functions Module
/// @interface_level=unit
/// @trace_id_sr=SR_CRYPTO_06005
/// @unit_name=Common_api
/// @unit_description=Crypto Object Unique Identifier (COUID)
/// @endcode
///
/// ================================================================

#ifndef ARA_CRYPTO_COMMON_PUHUA_COMMON_API_H_
#define ARA_CRYPTO_COMMON_PUHUA_COMMON_API_H_

#include <nai/os/nai_file.h>

#include <chrono>
#include <cstring>
#include <random>

#include "ara/core/string.h"
#include "ara/core/string_view.h"
#include "ara/core/vector.h"
#include "ara/crypto/common/isoft_data_type.h"
#include "ara/crypto/common/isoft_log_api.h"
#include "ara/crypto/common/security_error_domain.h"
#include "ara/crypto/common/uuid.h"
#include "ara/crypto/cryp/isoft_auto_buff.h"

namespace ara {
namespace crypto {
//********************************/
/// @brief Save data to a file
/// @param fileName The name of the file receiving the data
/// @param pData Data: starting address of the memory
/// @param nDataLen Data length
/// @return true if save to file sucess false otherwise
/// @code{.isoft}
/// @interface_level=unit
/// @trace_id_ad=AD_CRYPTO_02548
/// @trace_id_dd=DD_CRYPTO_00115
/// @trace_id_sr=SR_CRYPTO_06005
/// @needwork = dd
/// @endcode
inline bool SaveDataToFile(ara::core::StringView const &fileName,
                           uint8_t const *const pData,
                           uint32_t const nDataLen) noexcept
{
    if (fileName.empty()) {
        ara::crypto::isoft_def::LogInfo() << "SaveDataToFile : Do Noing";
        return true;
    }
    nai_int_t const naiOpenMode{static_cast< nai_int_t >(kInt_64 | kInt_2)};  //NAI_O_CREAT | NAI_O_RDWR
    nai_fd_t const fd{nai_file_open(fileName.data(), naiOpenMode, static_cast< size_t >(kInt_666U))};
    if (static_cast< nai_fd_t >(-1) == fd) {
        ara::crypto::isoft_def::LogInfo() << "SaveDataToFile :" << fileName.data() << " Not Exist\n";
        return true;
    }
    intptr_t r{nai_file_write(fd, pData, static_cast< size_t >(nDataLen))};
    if (r != static_cast< intptr_t >(nDataLen)) {
        return false;
    }
    r = nai_file_close(fd);
    return r >= 0;
}
//********************************/
/// @brief uuid
/// @code{.isoft}
/// @interface_level=unit
/// @trace_id_ad=AD_CRYPTO_02548
/// @trace_id_dd=DD_CRYPTO_00116
/// @trace_id_sr=SR_CRYPTO_06005
/// @needwork = dd
/// @endcode
struct P_Uuid
{
    /// @brief nTimeLow
    uint32_t nTimeLow;
    /// @brief nTimeMid
    uint16_t nTimeMid;
    /// @brief nTimeHighAndVersion
    uint16_t nTimeHighAndVersion;
    /// @brief nClockSeqAndReserved
    uint8_t nClockSeqAndReserved;
    /// @brief nClockSeqLow
    uint8_t nClockSeqLow;
    /// @brief node
    uint8_t node[kInt_6U];
};
/// @brief Return a UUID generated by time
/// @return UUID instance
/// @code{.isoft}
/// @interface_level=unit
/// @trace_id_ad=AD_CRYPTO_02548
/// @trace_id_dd=DD_CRYPTO_00117
/// @trace_id_sr=SR_CRYPTO_06005
/// @needwork = dd
/// @endcode
inline Uuid GetUuidByTime() noexcept
{
    std::time_t const t0{std::chrono::system_clock::to_time_t(std::chrono::system_clock::now())};
    std::tm const *const tm0{std::localtime(&t0)};  // NOLINT
    P_Uuid uid{kInt_0U, kInt_0U, kInt_0U, kInt_0U, kInt_0U, {kInt_0U}};
    Uuid uidData;
    uid.nTimeLow             = static_cast< uint32_t >(tm0->tm_year) + kInt_1900U;
    uid.nTimeMid             = static_cast< uint16_t >(tm0->tm_mon);
    uid.nTimeHighAndVersion  = static_cast< uint16_t >(tm0->tm_mday);
    uid.nClockSeqAndReserved = 0U;
    uid.nClockSeqLow         = static_cast< uint8_t >(tm0->tm_sec);

    std::mt19937 gen{static_cast< uint_fast32_t >(tm0->tm_sec)};  // Mersenne Twister generator
    std::uniform_int_distribution<> dis{0, kInt_255};             // Define distribution range

    for (uint8_t &itData : uid.node) {
        itData      = static_cast< uint8_t >(dis(gen));
        std::ignore = gen;
    }
    std::ignore = memcpy(static_cast< uint64_t * >(static_cast< void * >(&uidData)),
                         static_cast< uint64_t * >(static_cast< void * >(&uid)), sizeof(uid));
    return uidData;
}
//********************************/
/// @brief Addition operation for uint8_t, uint16_t, uint32_t, and int32_t
/// @param nData Integer data: augend
/// @param nAdd Integer data: addend
/// @return Addition result
/// @code{.isoft}
/// @tparam T
/// @interface_level=unit
/// @trace_id_ad=AD_CRYPTO_02548
/// @trace_id_dd=DD_CRYPTO_00118
/// @trace_id_sr=SR_CRYPTO_06005
/// @needwork = dd
/// @endcode
template < typename T >
inline T T_AddInt(T const nData, int32_t const nAdd) noexcept
{
    int32_t const nTemp{static_cast< int32_t >(nData) + nAdd};
    return static_cast< T >(nTemp);
}
/// @brief Calculate remainder
/// @param nDataA Integer data A: similar to dividend in division
/// @param nDataB Integer data B: similar to divisor in division
/// @return nDataA % nDataB remainder
/// @code{.isoft}
/// @tparam T_Src1
/// @tparam T_Src2
/// @interface_level=unit
/// @trace_id_ad=AD_CRYPTO_02548
/// @trace_id_dd=DD_CRYPTO_00119
/// @trace_id_sr=SR_CRYPTO_06005
/// @needwork = dd
/// @endcode
template < typename T_Src1, typename T_Src2 >
inline int32_t T_Mod(T_Src1 const nDataA, T_Src2 const nDataB) noexcept
{
    return static_cast< int32_t >(nDataA) % static_cast< int32_t >(nDataB);
}
/// @brief Calculate quotient, Gaussian rounding
/// @param nDataA Integer data A: similar to dividend in division
/// @param nDataB Integer data B: similar to divisor in division
/// @return (nDataA + (nDataB - 1)) / nDataB
/// @code{.isoft}
/// @tparam TDst
/// @tparam TSrc
/// @interface_level=unit
/// @trace_id_ad=AD_CRYPTO_02548
/// @trace_id_dd=DD_CRYPTO_00120
/// @trace_id_sr=SR_CRYPTO_06005
/// @needwork = dd
/// @endcode
template < typename T_Src, typename T_Dst >
inline T_Dst T_DivUp(T_Src const nDataA, T_Src const nDataB) noexcept
{
    T_Src const nDiv{(nDataA + (nDataB - 1)) / nDataB};
    return static_cast< T_Dst >(nDiv);
}
/// @brief Calculate quotient, discard remainder
/// @param nDataA Integer data A: similar to dividend in division
/// @param nDataB Integer data B: similar to divisor in division
/// @return nDataA / nDataB
/// @code{.isoft}
/// @tparam T_Src
/// @tparam T_Dst
/// @interface_level=unit
/// @trace_id_ad=AD_CRYPTO_02548
/// @trace_id_dd=DD_CRYPTO_00121
/// @trace_id_sr=SR_CRYPTO_06005
/// @needwork = dd
/// @endcode
template < typename T_Src, typename T_Dst >
inline T_Dst T_Div(T_Src const nDataA, T_Src const nDataB) noexcept
{
    T_Src const nDiv{nDataA / nDataB};
    return static_cast< T_Dst >(nDiv);
}
/// @brief Do nothing, just occupy a function call
/// @param n Integer: int32_t
/// @return
/// @code{.isoft}
/// @interface_level=unit
/// @trace_id_ad=AD_CRYPTO_02548
/// @trace_id_dd=DD_CRYPTO_00122
/// @trace_id_sr=SR_CRYPTO_06005
/// @needwork = dd
/// @endcode
inline int32_t T_Void(int32_t n = 0) noexcept
{
    if (n > 0) {
        n += 1;
    }
    return n;
}
/// @brief Number => Base16 character
/// @param n Integer data
/// @return String
/// @code{.isoft}
/// @tparam T
/// @interface_level=unit
/// @trace_id_ad=AD_CRYPTO_02548
/// @trace_id_dd=DD_CRYPTO_00123
/// @trace_id_sr=SR_CRYPTO_06005
/// @needwork = dd
/// @endcode
template < typename T >
inline ara::crypto::char8_t T_itochar(T n) noexcept
{
    n = n % static_cast< T >(kInt_0x10);
    if (n >= static_cast< T >(kInt_10)) {
        return static_cast< ara::crypto::char8_t >(static_cast< T >(kChar_a) + (n - static_cast< T >(kInt_10)));
    }
    return static_cast< ara::crypto::char8_t >(static_cast< T >(kChar_0) + n);
}
/// @brief Base16 character => number
/// @param ch Input character
/// @return Integer
/// @code{.isoft}
/// @tparam T
/// @interface_level=unit
/// @trace_id_ad=AD_CRYPTO_02548
/// @trace_id_dd=DD_CRYPTO_00124
/// @trace_id_sr=SR_CRYPTO_06005
/// @needwork = dd
/// @endcode
template < typename T >
inline T T_chartoi(ara::crypto::char8_t const ch) noexcept
{
    T nData;
    if ((ch >= kChar_A) && (ch <= kChar_Z)) {
        nData = static_cast< T >(ch) - static_cast< T >(kChar_A) + static_cast< T >(kInt_10);
    } else if ((ch >= kChar_a) && (ch <= kChar_z)) {
        nData = static_cast< T >(ch) - static_cast< T >(kChar_a) + static_cast< T >(kInt_10);
    } else if ((ch >= kChar_0) && (ch <= kChar_9)) {
        nData = static_cast< T >(ch) - static_cast< T >(kChar_0);
    } else {
        nData = static_cast< T >(0);
    }
    return nData;
}
/// @brief Base16 character => number
/// @param ch Input character
/// @return Data of type T
/// @code{.isoft}
/// @tparam T
/// @interface_level=unit
/// @trace_id_ad=AD_CRYPTO_02548
/// @trace_id_dd=DD_CRYPTO_00125
/// @trace_id_sr=SR_CRYPTO_06005
/// @needwork = dd
/// @endcode
template < typename T >
inline T T_chartoi(uint8_t const ch) noexcept
{
    return T_chartoi< T >(static_cast< ara::crypto::char8_t >(ch));
}
/// @brief String stored in memory => number
/// @param pData Data: starting address of the memory
/// @param nLen Data length: in bytes
/// @param nBase Base
/// @return Number
/// @code{.isoft}
/// @tparam T
/// @interface_level=unit
/// @trace_id_ad=AD_CRYPTO_02548
/// @trace_id_dd=DD_CRYPTO_00126
/// @trace_id_sr=SR_CRYPTO_06005
/// @needwork = dd
/// @endcode
template < typename T >
inline T T_stoi(void const *const pData, uint32_t const nLen, int32_t const nBase = kInt_10) noexcept
{
    std::string const stData{static_cast< ara::crypto::char8_t const * >(pData), static_cast< std::size_t >(nLen)};
    return static_cast< T >(std::stoi(stData, nullptr, nBase));
}
/// @brief String stored in memory => uint32_t number
/// @param pData Data: starting address of the memory
/// @param nLen Data length: in bytes
/// @param nBase Base
/// @return uint32_t number
/// @code{.isoft}
/// @interface_level=unit
/// @trace_id_ad=AD_CRYPTO_02548
/// @trace_id_dd=DD_CRYPTO_00127
/// @trace_id_sr=SR_CRYPTO_06005
/// @needwork = dd
/// @endcode
template <>
inline uint32_t T_stoi(void const *const pData, uint32_t const nLen, int32_t const nBase) noexcept
{
    try {
        std::string const stData{static_cast< ara::crypto::char8_t const * >(pData), static_cast< std::size_t >(nLen)};
        return static_cast< uint32_t >(std::stoul(stData, nullptr, nBase));
    } catch (...) {
        return 0U;
    }
}
/// @brief String stored in memory => int64_t number
/// @param pData Data: starting address of the memory
/// @param nLen Data length: in bytes
/// @param nBase Base
/// @return int64_t number
/// @code{.isoft}
/// @interface_level=unit
/// @trace_id_ad=AD_CRYPTO_02548
/// @trace_id_dd=DD_CRYPTO_00128
/// @trace_id_sr=SR_CRYPTO_06005
/// @needwork = dd
/// @endcode
template <>
inline int64_t T_stoi(void const *const pData, uint32_t const nLen, int32_t const nBase) noexcept
{
    try {
        std::string const stData{static_cast< ara::crypto::char8_t const * >(pData), static_cast< std::size_t >(nLen)};
        return static_cast< int64_t >(std::stoll(stData, nullptr, nBase));
    } catch (...) {
        return 0;
    }
}
/// @brief String stored in memory => uint64_t number
/// @param pData Data: starting address of the memory
/// @param nLen Data length: in bytes
/// @param nBase Base
/// @return uint64_t number
/// @code{.isoft}
/// @interface_level=unit
/// @trace_id_ad=AD_CRYPTO_02548
/// @trace_id_dd=DD_CRYPTO_00129
/// @trace_id_sr=SR_CRYPTO_06005
/// @needwork = dd
/// @endcode
template <>
inline uint64_t T_stoi(void const *const pData, uint32_t const nLen, int32_t const nBase) noexcept
{
    try {
        std::string const stData{static_cast< ara::crypto::char8_t const * >(pData), static_cast< std::size_t >(nLen)};
        return static_cast< uint64_t >(std::stoull(stData, nullptr, nBase));
    } catch (...) {
        return 0U;
    }
}
/// @brief Determine if b == (a & b)
/// @param a T template object
/// @param b T template object
/// @return true if b == (a & b) false otherwise
/// @code{.isoft}
/// @tparam T
/// @interface_level=unit
/// @trace_id_ad=AD_CRYPTO_02548
/// @trace_id_dd=DD_CRYPTO_00130
/// @trace_id_sr=SR_CRYPTO_06005
/// @needwork = dd
/// @endcode
template < typename T >
inline bool T_IsAndData(T const a, T const b) noexcept
{
    uint32_t const nA{static_cast< uint32_t >(a)};
    uint32_t const nB{static_cast< uint32_t >(b)};
    return nB == (nA & nB);
}
/// @brief Calculate a & b
/// @param a T template object: basic numeric type
/// @param b T template object: basic numeric type
/// @return a & b value
/// @code{.isoft}
/// @tparam T
/// @interface_level=unit
/// @trace_id_ad=AD_CRYPTO_02548
/// @trace_id_dd=DD_CRYPTO_00131
/// @trace_id_sr=SR_CRYPTO_06005
/// @needwork = dd
/// @endcode
template < typename T >
inline T T_AndData(T const a, T const b) noexcept
{
    uint32_t const nA{static_cast< uint32_t >(a)};
    uint32_t const nB{static_cast< uint32_t >(b)};
    return static_cast< T >(nA & nB);
}
/// @brief Return the ceiling of integer A divided by B
/// @param a Similar to dividend in division
/// @param b Similar to divisor in division
/// @return The ceiling of A divided by B
/// @code{.isoft}
/// @interface_level=unit
/// @trace_id_ad=AD_CRYPTO_02548
/// @trace_id_dd=DD_CRYPTO_00132
/// @trace_id_sr=SR_CRYPTO_06005
/// @needwork = dd
/// @endcode
inline uint32_t T_AlignNumberUp(uint32_t const a, uint32_t const b) noexcept
{
    uint32_t const bStep{b - 1U};
    return (a + bStep) & (~bStep);
}
/// @brief Return the ceiling of integer A divided by B
/// @param a Similar to dividend in division
/// @param b Similar to divisor in division
/// @return The ceiling of A divided by B
/// @code{.isoft}
/// @interface_level=unit
/// @trace_id_ad=AD_CRYPTO_02548
/// @trace_id_dd=DD_CRYPTO_00133
/// @trace_id_sr=SR_CRYPTO_06005
/// @needwork = dd
/// @endcode
inline int64_t T_AlignNumberUp(int64_t const a, uint32_t const b) noexcept
{
    uint64_t const bStep{b - static_cast< uint64_t >(1)};
    uint64_t nA{static_cast< uint64_t >(a) + bStep};
    nA = nA & (~bStep);
    return static_cast< int64_t >(nA);
}
/// @brief Return the floor of integer A divided by B
/// @param a Similar to dividend in division
/// @param b Similar to divisor in division
/// @return The floor of A divided by B
/// @code{.isoft}
/// @interface_level=unit
/// @trace_id_ad=AD_CRYPTO_02548
/// @trace_id_dd=DD_CRYPTO_00134
/// @trace_id_sr=SR_CRYPTO_06005
/// @needwork = dd
/// @endcode
inline int64_t T_AlignNumberDown(int64_t const a, uint32_t const b) noexcept
{
    uint64_t const bStep{b - static_cast< uint64_t >(1)};
    uint64_t nA{static_cast< uint64_t >(a)};
    nA = nA & (~bStep);
    return static_cast< int64_t >(nA);
}
/// @brief Memory copy function
/// @param pDst Destination address
/// @param pSrc Source address
/// @param nLen Data length: in bytes
/// @return Destination address
/// @code{.isoft}
/// @interface_level=unit
/// @trace_id_ad=AD_CRYPTO_02548
/// @trace_id_dd=DD_CRYPTO_00135
/// @trace_id_sr=SR_CRYPTO_06005
/// @needwork = dd
/// @endcode
inline void *T_Memcpy(void *const pDst, void const *const pSrc, uint32_t const nLen) noexcept
{
    return memcpy(pDst, pSrc, static_cast< std::size_t >(nLen));
}
//********************************/ // The following type conversions are to work around QAC (e.g., 3080) rule restrictions
/// @brief Pointer conversion: T * => void *
/// @param pData Data: starting address of the memory
/// @return void pointer instance
/// @code{.isoft}
/// @tparam T
/// @interface_level=unit
/// @trace_id_ad=AD_CRYPTO_02548
/// @trace_id_dd=DD_CRYPTO_00136
/// @trace_id_sr=SR_CRYPTO_06005
/// @needwork = dd
/// @endcode
template < typename T >
inline void *T_TransVoid(T *const pData) noexcept
{
    return static_cast< void * >(pData);
}
/// @brief Pointer conversion: T const * => void const *
/// @param pData Data: starting address of the memory
/// @return void const pointer instance
/// @code{.isoft}
/// @tparam T
/// @interface_level=unit
/// @trace_id_ad=AD_CRYPTO_02548
/// @trace_id_dd=DD_CRYPTO_00137
/// @trace_id_sr=SR_CRYPTO_06005
/// @needwork = dd
/// @endcode
template < typename T >
inline void const *T_TransVoid(T const *const pData) noexcept
{
    return static_cast< void const * >(pData);
}
/// @brief Pointer conversion: T * => uint8_t *
/// @param pData Data: starting address of the memory
/// @return uint8_t pointer instance
/// @code{.isoft}
/// @tparam T
/// @interface_level=unit
/// @trace_id_ad=AD_CRYPTO_02548
/// @trace_id_dd=DD_CRYPTO_00138
/// @trace_id_sr=SR_CRYPTO_06005
/// @needwork = dd
/// @endcode
template < typename T >
inline uint8_t *T_TransBytes(T *const pData) noexcept
{
    return static_cast< uint8_t * >(static_cast< void * >(pData));
}
/// @brief Pointer conversion: T * => char8_t *
/// @param pData Data: starting address of the memory
/// @return char8_t pointer instance
/// @code{.isoft}
/// @tparam T
/// @interface_level=unit
/// @trace_id_ad=AD_CRYPTO_02548
/// @trace_id_dd=DD_CRYPTO_00139
/// @trace_id_sr=SR_CRYPTO_06005
/// @needwork = dd
/// @endcode
template < typename T >
inline ara::crypto::char8_t *T_TransChar(T *const pData) noexcept
{
    return static_cast< ara::crypto::char8_t * >(static_cast< void * >(pData));
}
/// @brief Pointer conversion: T const * => char8_t const *
/// @param pData Data: starting address of the memory
/// @return char8_t const pointer instance
/// @code{.isoft}
/// @tparam T
/// @interface_level=unit
/// @trace_id_ad=AD_CRYPTO_02548
/// @trace_id_dd=DD_CRYPTO_00140
/// @trace_id_sr=SR_CRYPTO_06005
/// @needwork = dd
/// @endcode
template < typename T >
inline ara::crypto::char8_t const *T_TransChar(T const *const pData) noexcept
{
    return static_cast< ara::crypto::char8_t const * >(static_cast< void const * >(pData));
}
/// @brief Pointer conversion: T const * => uint8_t const *
/// @param pData Data: starting address of the memory
/// @return uint8_t const pointer instance
/// @code{.isoft}
/// @tparam T
/// @interface_level=unit
/// @trace_id_ad=AD_CRYPTO_02548
/// @trace_id_dd=DD_CRYPTO_00141
/// @trace_id_sr=SR_CRYPTO_06005
/// @needwork = dd
/// @endcode
template < typename T >
inline uint8_t const *T_TransBytes(T const *const pData) noexcept
{
    return static_cast< uint8_t const * >(static_cast< void const * >(pData));
}
/// @brief Pointer conversion: uint8_t * => T *
/// @param pData Data: starting address of the memory
/// @return T type pointer instance
/// @code{.isoft}
/// @tparam T
/// @interface_level=unit
/// @trace_id_ad=AD_CRYPTO_02548
/// @trace_id_dd=DD_CRYPTO_00142
/// @trace_id_sr=SR_CRYPTO_06005
/// @needwork = dd
/// @endcode
template < typename T >
inline T *T_TransPtr(uint8_t *const pData) noexcept
{
    return static_cast< T * >(static_cast< void * >(pData));
}
/// @brief Pointer conversion: uint8_t const * => T const *
/// @param pData Data: starting address of the memory
/// @return T const pointer instance
/// @code{.isoft}
/// @tparam T
/// @interface_level=unit
/// @trace_id_ad=AD_CRYPTO_02548
/// @trace_id_dd=DD_CRYPTO_00143
/// @trace_id_sr=SR_CRYPTO_06005
/// @needwork = dd
/// @endcode
template < typename T >
inline T const *T_TransPtr(uint8_t const *const pData) noexcept
{
    return static_cast< T const * >(static_cast< void const * >(pData));
}
/// @brief Pointer conversion: T_Src * => T_Dst *
/// @param pData Data: starting address of the memory
/// @return T_Dst pointer instance
/// @code{.isoft}
/// @tparam T
/// @interface_level=unit
/// @trace_id_ad=AD_CRYPTO_02548
/// @trace_id_dd=DD_CRYPTO_00144
/// @trace_id_sr=SR_CRYPTO_06005
/// @needwork = dd
/// @endcode
template < typename T_Src, typename T_Dst >
inline T_Dst *T_TransPtr(T_Src *const pData) noexcept
{
    return static_cast< T_Dst * >(static_cast< void * >(pData));
}
/// @brief Pointer conversion: T_Src const * => T_Dst const *
/// @param pData Data: starting address of the memory
/// @return T_Dst const pointer instance
/// @code{.isoft}
/// @tparam T_Src
/// @tparam T_Dst
/// @interface_level=unit
/// @trace_id_ad=AD_CRYPTO_02548
/// @trace_id_dd=DD_CRYPTO_00145
/// @trace_id_sr=SR_CRYPTO_06005
/// @needwork = dd
/// @endcode
template < typename T_Src, typename T_Dst >
inline T_Dst const *T_TransPtr(T_Src const *const pData) noexcept
{
    return static_cast< T_Dst const * >(static_cast< void const * >(pData));
}
/// @brief Pointer conversion: array type to pointer type
/// @param array Array
/// @return T const pointer instance
/// @code{.isoft}
/// @tparam T
/// @interface_level=unit
/// @trace_id_ad=AD_CRYPTO_02548
/// @trace_id_dd=DD_CRYPTO_00146
/// @trace_id_sr=SR_CRYPTO_06005
/// @needwork = dd
/// @endcode
template < typename T >
inline T const *T_TransArray(T const array[]) noexcept
{
    return static_cast< T const * >(array);
}
/// @brief Pointer conversion: basic data type to corresponding pointer type
/// @param pData Data: starting address of the memory, including but not limited to: float, double, int32_t, uint8_t, etc.
/// @return T type pointer instance
/// @code{.isoft}
/// @tparam T
/// @interface_level=unit
/// @trace_id_ad=AD_CRYPTO_02548
/// @trace_id_dd=DD_CRYPTO_00147
/// @trace_id_sr=SR_CRYPTO_06005
/// @needwork = dd
/// @endcode
template < typename T >
inline T *T_TransPriDataType(T pData) noexcept
{
    return static_cast< T * >(pData);
}
/// @brief Pointer arithmetic
/// @param pData Data: starting address of the memory
/// @param nOffset Offset
/// @return pData + nOffset;
/// @code{.isoft}
/// @tparam T
/// @interface_level=unit
/// @trace_id_ad=AD_CRYPTO_02548
/// @trace_id_dd=DD_CRYPTO_00148
/// @trace_id_sr=SR_CRYPTO_06005
/// @needwork = dd
/// @endcode
template < typename T >
inline T *T_OffsetPtr(T *const pData, int32_t const nOffset) noexcept
{
    return pData + nOffset;
}
/// @brief Pointer arithmetic
/// @param pData Data: starting address of the memory
/// @param nOffset Offset
/// @return pData + nOffset;
/// @code{.isoft}
/// @tparam T
/// @interface_level=unit
/// @trace_id_ad=AD_CRYPTO_02548
/// @trace_id_dd=DD_CRYPTO_00149
/// @trace_id_sr=SR_CRYPTO_06005
/// @needwork = dd
/// @endcode
template < typename T >
inline T const *T_OffsetPtr(T const *const pData, int32_t const nOffset) noexcept
{
    return pData + nOffset;
}
/// @brief Pointer arithmetic pDataA - pDataB;
/// @param pVoidA Pointer A involved in the operation
/// @param pVoidB Pointer B involved in the operation
/// @return Return value is the difference between the two addresses: in bytes
/// @code{.isoft}
/// @tparam T_Src
/// @tparam T_Dst
/// @interface_level=unit
/// @trace_id_ad=AD_CRYPTO_02548
/// @trace_id_dd=DD_CRYPTO_00150
/// @trace_id_sr=SR_CRYPTO_06005
/// @needwork = dd
/// @endcode
template < typename T_Src, typename T_Dst >
inline int32_t T_SubPtr(T_Src const *const pVoidA, T_Dst const *const pVoidB) noexcept
{
    uint8_t const *const pDataA{T_TransBytes< T_Src >(pVoidA)};
    uint8_t const *const pDataB{T_TransBytes< T_Dst >(pVoidB)};
    return static_cast< int32_t >(pDataA - pDataB);
}
//********************************/
/// @brief ara::core::String => ara::core::StringView
/// @param stData String type data
/// @return StringView string
/// @code{.isoft}
/// @interface_level=unit
/// @trace_id_ad=AD_CRYPTO_02548
/// @trace_id_dd=DD_CRYPTO_00151
/// @trace_id_sr=SR_CRYPTO_06005
/// @needwork = dd
/// @endcode
inline ara::core::StringView T_StringView(ara::core::String const &stData) noexcept
{
    return ara::core::StringView{stData.data(), stData.size()};
}
/// @brief char8_t[] => ara::core::StringView
/// @param chData Starting address of the character array
/// @return StringView string
/// @code{.isoft}
/// @interface_level=unit
/// @trace_id_ad=AD_CRYPTO_02548
/// @trace_id_dd=DD_CRYPTO_00152
/// @trace_id_sr=SR_CRYPTO_06005
/// @needwork = dd
/// @endcode
inline ara::core::StringView T_StringView(ara::crypto::char8_t const chData[]) noexcept
{
    return ara::core::StringView{chData};
}
/// @brief uint8_t * => ara::core::StringView
/// @param pData Data: starting address of the memory
/// @param nLen Data length: in bytes
/// @return StringView string
/// @code{.isoft}
/// @interface_level=unit
/// @trace_id_ad=AD_CRYPTO_02548
/// @trace_id_dd=DD_CRYPTO_00153
/// @trace_id_sr=SR_CRYPTO_06005
/// @needwork = dd
/// @endcode
inline ara::core::StringView T_StringView(void const *const pData, size_t const nLen) noexcept
{
    return ara::core::StringView{T_TransPtr< void, ara::crypto::char8_t >(pData), nLen};
}
/// @brief ara::core::StringView => ara::core::String
/// @param stData String type data
/// @return String string
/// @code{.isoft}
/// @interface_level=unit
/// @trace_id_ad=AD_CRYPTO_02548
/// @trace_id_dd=DD_CRYPTO_00154
/// @trace_id_sr=SR_CRYPTO_06005
/// @needwork = dd
/// @endcode
inline ara::core::String T_String(ara::core::StringView const &stData) noexcept
{
    return ara::core::String{stData.data(), stData.size()};
}
/// @brief (void *, int32_t) => ara::core::String
/// @param pData Data: starting address of the memory
/// @param nLen Data length: in bytes
/// @return String string
/// @code{.isoft}
/// @interface_level=unit
/// @trace_id_ad=AD_CRYPTO_02548
/// @trace_id_dd=DD_CRYPTO_00155
/// @trace_id_sr=SR_CRYPTO_06005
/// @needwork = dd
/// @endcode
inline ara::core::String T_String(void const *const pData, size_t const nLen) noexcept
{
    return ara::core::String{T_TransPtr< void, ara::crypto::char8_t >(pData), nLen};
}
//********************************/
/// @brief Get current time: seconds since 1970-01-01
/// @return uint64_t integer
/// @code{.isoft}
/// @interface_level=unit
/// @trace_id_ad=AD_CRYPTO_02548
/// @trace_id_dd=DD_CRYPTO_00156
/// @trace_id_sr=SR_CRYPTO_06005
/// @needwork = dd
/// @endcode
inline uint64_t TM_NowSecond() noexcept
{
    std::chrono::time_point< std::chrono::system_clock, std::chrono::seconds > const tmSeconds{
        std::chrono::time_point_cast< std::chrono::seconds >(std::chrono::system_clock::now())};
    return static_cast< uint64_t >(tmSeconds.time_since_epoch().count());
}
//********************************/
#ifdef ARA_DEBUG_FUN
/// @brief Print output debug memory
/// @param pchMsg Log message string
/// @param nMsgData Log data: integer value
/// @param pBData Data start address
/// @param nDataLen Data length
inline void Debug_PrintfMemory(ara::crypto::char8_t const *const pchMsg,
                               int32_t const nMsgData,
                               uint8_t const *const pBData,
                               int32_t const nDataLen) noexcept
{
    ara::crypto::isoft_def::LogInfo() << "Begin. <<<<< " << pchMsg << "[" << nMsgData << "], Data = ";
    for (int32_t i{0}; i < nDataLen; ++i) {
        if ((i % kInt_64) == 0) {
            ara::crypto::isoft_def::LogInfo() << " ";
        }
        ara::crypto::isoft_def::LogInfo() << pBData[i];
    }
    ara::crypto::isoft_def::LogInfo() << pchMsg << "[" << nMsgData << "]>>>>>End.";
}
#endif
/// @brief ErrorID conversion
/// @param nErrorID Error code
/// @return error code
/// @code{.isoft}
/// @interface_level=unit
/// @trace_id_ad=AD_CRYPTO_02548
/// @trace_id_dd=DD_CRYPTO_00166
/// @trace_id_sr=SR_CRYPTO_06005
/// @needwork = dd
/// @endcode
inline ara::crypto::SecurityErrorDomain::Errc TransformErrorID(ara::core::ErrorDomain::CodeType const nErrorID) noexcept
{
    ara::crypto::SecurityErrorDomain::Errc kCode;
    switch (nErrorID) {
        case static_cast< ara::core::ErrorDomain::CodeType >(ara::crypto::SecurityErrorDomain::Errc::kResourceFault): {
            kCode = ara::crypto::SecurityErrorDomain::Errc::kResourceFault;
        } break;
        case static_cast< ara::core::ErrorDomain::CodeType >(ara::crypto::SecurityErrorDomain::Errc::kBusyResource): {
            kCode = ara::crypto::SecurityErrorDomain::Errc::kBusyResource;
        } break;
        case static_cast< ara::core::ErrorDomain::CodeType >(
            ara::crypto::SecurityErrorDomain::Errc::kInsufficientResource): {
            kCode = ara::crypto::SecurityErrorDomain::Errc::kInsufficientResource;
        } break;
        case static_cast< ara::core::ErrorDomain::CodeType >(
            ara::crypto::SecurityErrorDomain::Errc::kUnreservedResource): {
            kCode = ara::crypto::SecurityErrorDomain::Errc::kUnreservedResource;
        } break;
        case static_cast< ara::core::ErrorDomain::CodeType >(ara::crypto::SecurityErrorDomain::Errc::kLogicFault): {
            kCode = ara::crypto::SecurityErrorDomain::Errc::kLogicFault;
        } break;
        case static_cast< ara::core::ErrorDomain::CodeType >(
            ara::crypto::SecurityErrorDomain::Errc::kInvalidArgument): {
            kCode = ara::crypto::SecurityErrorDomain::Errc::kInvalidArgument;
        } break;
        case static_cast< ara::core::ErrorDomain::CodeType >(
            ara::crypto::SecurityErrorDomain::Errc::kUnknownIdentifier): {
            kCode = ara::crypto::SecurityErrorDomain::Errc::kUnknownIdentifier;
        } break;
        case static_cast< ara::core::ErrorDomain::CodeType >(
            ara::crypto::SecurityErrorDomain::Errc::kInsufficientCapacity): {
            kCode = ara::crypto::SecurityErrorDomain::Errc::kInsufficientCapacity;
        } break;
        case static_cast< ara::core::ErrorDomain::CodeType >(
            ara::crypto::SecurityErrorDomain::Errc::kInvalidInputSize): {
            kCode = ara::crypto::SecurityErrorDomain::Errc::kInvalidInputSize;
        } break;
        case static_cast< ara::core::ErrorDomain::CodeType >(
            ara::crypto::SecurityErrorDomain::Errc::kIncompatibleArguments): {
            kCode = ara::crypto::SecurityErrorDomain::Errc::kIncompatibleArguments;
        } break;
        case static_cast< ara::core::ErrorDomain::CodeType >(
            ara::crypto::SecurityErrorDomain::Errc::kInOutBuffersIntersect): {
            kCode = ara::crypto::SecurityErrorDomain::Errc::kInOutBuffersIntersect;
        } break;
        case static_cast< ara::core::ErrorDomain::CodeType >(ara::crypto::SecurityErrorDomain::Errc::kBelowBoundary): {
            kCode = ara::crypto::SecurityErrorDomain::Errc::kBelowBoundary;
        } break;
        case static_cast< ara::core::ErrorDomain::CodeType >(ara::crypto::SecurityErrorDomain::Errc::kAboveBoundary): {
            kCode = ara::crypto::SecurityErrorDomain::Errc::kAboveBoundary;
        } break;
        case static_cast< ara::core::ErrorDomain::CodeType >(ara::crypto::SecurityErrorDomain::Errc::kUnsupported): {
            kCode = ara::crypto::SecurityErrorDomain::Errc::kUnsupported;
        } break;
        case static_cast< ara::core::ErrorDomain::CodeType >(
            ara::crypto::SecurityErrorDomain::Errc::kInvalidUsageOrder): {
            kCode = ara::crypto::SecurityErrorDomain::Errc::kInvalidUsageOrder;
        } break;
        case static_cast< ara::core::ErrorDomain::CodeType >(
            ara::crypto::SecurityErrorDomain::Errc::kUninitializedContext): {
            kCode = ara::crypto::SecurityErrorDomain::Errc::kUninitializedContext;
        } break;
        case static_cast< ara::core::ErrorDomain::CodeType >(
            ara::crypto::SecurityErrorDomain::Errc::kProcessingNotStarted): {
            kCode = ara::crypto::SecurityErrorDomain::Errc::kProcessingNotStarted;
        } break;
        case static_cast< ara::core::ErrorDomain::CodeType >(
            ara::crypto::SecurityErrorDomain::Errc::kProcessingNotFinished): {
            kCode = ara::crypto::SecurityErrorDomain::Errc::kProcessingNotFinished;
        } break;
        case static_cast< ara::core::ErrorDomain::CodeType >(ara::crypto::SecurityErrorDomain::Errc::kRuntimeFault): {
            kCode = ara::crypto::SecurityErrorDomain::Errc::kRuntimeFault;
        } break;
        case static_cast< ara::core::ErrorDomain::CodeType >(
            ara::crypto::SecurityErrorDomain::Errc::kUnsupportedFormat): {
            kCode = ara::crypto::SecurityErrorDomain::Errc::kUnsupportedFormat;
        } break;
        case static_cast< ara::core::ErrorDomain::CodeType >(ara::crypto::SecurityErrorDomain::Errc::kBruteForceRisk): {
            kCode = ara::crypto::SecurityErrorDomain::Errc::kBruteForceRisk;
        } break;
        case static_cast< ara::core::ErrorDomain::CodeType >(
            ara::crypto::SecurityErrorDomain::Errc::kContentRestrictions): {
            kCode = ara::crypto::SecurityErrorDomain::Errc::kContentRestrictions;
        } break;
        case static_cast< ara::core::ErrorDomain::CodeType >(
            ara::crypto::SecurityErrorDomain::Errc::kBadObjectReference): {
            kCode = ara::crypto::SecurityErrorDomain::Errc::kBadObjectReference;
        } break;
        case static_cast< ara::core::ErrorDomain::CodeType >(
            ara::crypto::SecurityErrorDomain::Errc::kUnexpectedValue): {
            kCode = ara::crypto::SecurityErrorDomain::Errc::kUnexpectedValue;
        } break;
        case static_cast< ara::core::ErrorDomain::CodeType >(
            ara::crypto::SecurityErrorDomain::Errc::kIncompatibleObject): {
            kCode = ara::crypto::SecurityErrorDomain::Errc::kIncompatibleObject;
        } break;
        case static_cast< ara::core::ErrorDomain::CodeType >(
            ara::crypto::SecurityErrorDomain::Errc::kIncompleteArgState): {
            kCode = ara::crypto::SecurityErrorDomain::Errc::kIncompleteArgState;
        } break;
        case static_cast< ara::core::ErrorDomain::CodeType >(ara::crypto::SecurityErrorDomain::Errc::kEmptyContainer): {
            kCode = ara::crypto::SecurityErrorDomain::Errc::kEmptyContainer;
        } break;
        case static_cast< ara::core::ErrorDomain::CodeType >(ara::crypto::SecurityErrorDomain::Errc::kBadObjectType): {
            kCode = ara::crypto::SecurityErrorDomain::Errc::kBadObjectType;
        } break;
        case static_cast< ara::core::ErrorDomain::CodeType >(ara::crypto::SecurityErrorDomain::Errc::kUsageViolation): {
            kCode = ara::crypto::SecurityErrorDomain::Errc::kUsageViolation;
        } break;
        case static_cast< ara::core::ErrorDomain::CodeType >(
            ara::crypto::SecurityErrorDomain::Errc::kAccessViolation): {
            kCode = ara::crypto::SecurityErrorDomain::Errc::kAccessViolation;
        } break;
        case static_cast< ara::core::ErrorDomain::CodeType >(ara::crypto::SecurityErrorDomain::Errc::kIpcFault): {
            kCode = ara::crypto::SecurityErrorDomain::Errc::kIpcFault;
        } break;
        case static_cast< ara::core::ErrorDomain::CodeType >(
            ara::crypto::SecurityErrorDomain::Errc::kIpcSlotNotExist): {
            kCode = ara::crypto::SecurityErrorDomain::Errc::kIpcSlotNotExist;
        } break;
        case static_cast< ara::core::ErrorDomain::CodeType >(
            ara::crypto::SecurityErrorDomain::Errc::kIpcIoInterfaceNotExist): {
            kCode = ara::crypto::SecurityErrorDomain::Errc::kIpcIoInterfaceNotExist;
        } break;
        case static_cast< ara::core::ErrorDomain::CodeType >(
            ara::crypto::SecurityErrorDomain::Errc::kIpcSlotSaveData): {
            kCode = ara::crypto::SecurityErrorDomain::Errc::kIpcSlotSaveData;
        } break;
        case static_cast< ara::core::ErrorDomain::CodeType >(
            ara::crypto::SecurityErrorDomain::Errc::kMissingArgument): {
            kCode = ara::crypto::SecurityErrorDomain::Errc::kMissingArgument;
        } break;
        case static_cast< ara::core::ErrorDomain::CodeType >(ara::crypto::SecurityErrorDomain::Errc::kInitFailed): {
            kCode = ara::crypto::SecurityErrorDomain::Errc::kInitFailed;
        } break;
        case static_cast< ara::core::ErrorDomain::CodeType >(ara::crypto::SecurityErrorDomain::Errc::kUpdateFailed): {
            kCode = ara::crypto::SecurityErrorDomain::Errc::kUpdateFailed;
        } break;
        case static_cast< ara::core::ErrorDomain::CodeType >(
            ara::crypto::SecurityErrorDomain::Errc::kIncorrectInputSize): {
            kCode = ara::crypto::SecurityErrorDomain::Errc::kIncorrectInputSize;
        } break;
        default: {
            kCode = ara::crypto::SecurityErrorDomain::Errc::kUnknownIdentifier;
        } break;
    }
    return kCode;
}
/// @brief String increment  simple processing
/// @param counter Counter
/// @param len Length
/// @code{.isoft}
/// @interface_level=unit
/// @trace_id_ad=AD_CRYPTO_02548
/// @trace_id_dd=DD_CRYPTO_00170
/// @trace_id_sr=SR_CRYPTO_06005
/// @needwork = dd
/// @endcode
inline void Ctr_inc(uint8_t *const counter, uint32_t const len) noexcept
{
    size_t n{len};
    size_t c{1U};

    while (n > 0U) {
        --n;
        c += *(counter + n);
        *(counter + n) = static_cast< uint8_t >(c);
        c >>= kInt_8U;
    }
}
/// @brief String decrement  simple processing
/// @param counter Counter
/// @param len Length
/// @code{.isoft}
/// @interface_level=unit
/// @trace_id_ad=AD_CRYPTO_02548
/// @trace_id_dd=DD_CRYPTO_00171
/// @trace_id_sr=SR_CRYPTO_06005
/// @needwork = dd
/// @endcode
inline void Ctr_dec(uint8_t *const counter, uint32_t const len) noexcept
{
    size_t n{len};
    size_t const c{1U};

    while (n > 0U) {
        --n;
        if (*(counter + n) < c) {
            continue;
        }
        *(counter + n) -= c;
        break;
    }
}
//********************************/
}  // namespace crypto
}  // namespace ara
#endif  // ARA_CRYPTO_COMMON_PUHUA_COMMON_API_H_
