// Disclaimer
//
// This work (specification and/or software implementation) and the material
// contained in it, as released by AUTOSAR, is for the purpose of information
// only. AUTOSAR and the companies that have contributed to it shall not be
// liable for any use of the work.
//
// The material contained in this work is protected by copyright and other
// types of intellectual property rights. The commercial exploitation of the
// material contained in this work requires a license to such intellectual
// property rights.
//
// This work may be utilized or reproduced without any modification, in any
// form or by any means, for informational purposes only. For any other
// purpose, no part of the work may be utilized or reproduced, in any form
// or by any means, without permission in writing from the publisher.
//
// The work has been developed for automotive applications only. It has
// neither been developed, nor tested for non-automotive applications.
//
// The word AUTOSAR and the AUTOSAR logo are registered trademarks.
// --------------------------------------------------------------------------

/// ================================================================
///
/// File description:
/// ----------------
/// @file       condition_proxy.h
/// @brief      Generated by RPC script from API define.
/// @details
/// @date       2024-12-17
/// @author     zhanglipeng
/// @version    1.2.0
///
/// ================================================================

#ifndef __GEN_ConditionProxy_PROXY__
#define __GEN_ConditionProxy_PROXY__

#include <functional>

#include "ara/diag/condition.h"
#include "gen_code/defines.h"
#include "netProxy/bussiness_service_proxy.h"

namespace isoft {
namespace dm {
namespace dis {

class ConditionProxy : public BussinessServiceProxy
{
public:
    explicit ConditionProxy(uint32_t const& serviceInstanceId);
    void CallHandle(CallRequest&& callData) override;

public:
    /// @brief Register callback for AA side to set condition status
    /// @param callBack Callback function to be registered
    /// @return
    void RegisterSetCondition(std::function< void(ara::diag::ConditionType) > const& callBack);

    /// @brief Register callback for AA side to get condition status
    /// @param callBack Callback function to be registered
    /// @return
    void RegisterGetCondition(std::function< ara::diag::ConditionType() > const& callBack);

private:
    void _getCondition(CallRequest&& callData);
    void _setCondition(CallRequest&& callData);

private:
    std::function< void(ara::diag::ConditionType) > setConditionCb_{nullptr};
    std::function< ara::diag::ConditionType() > getConditionCb_{nullptr};
};

}  // namespace dis
}  // namespace dm
}  // namespace isoft

#endif  // __GEN_GenericDataIdentifier_AGENT__