// Disclaimer
//
// This work (specification and/or software implementation) and the material
// contained in it, as released by AUTOSAR, is for the purpose of information
// only. AUTOSAR and the companies that have contributed to it shall not be
// liable for any use of the work.
//
// The material contained in this work is protected by copyright and other
// types of intellectual property rights. The commercial exploitation of the
// material contained in this work requires a license to such intellectual
// property rights.
//
// This work may be utilized or reproduced without any modification, in any
// form or by any means, for informational purposes only. For any other
// purpose, no part of the work may be utilized or reproduced, in any form
// or by any means, without permission in writing from the publisher.
//
// The work has been developed for automotive applications only. It has
// neither been developed, nor tested for non-automotive applications.
//
// The word AUTOSAR and the AUTOSAR logo are registered trademarks.
// --------------------------------------------------------------------------

/// ================================================================
///
/// File description:
/// ----------------
/// @file       external_authentication_proxy.cpp
/// @brief      Generated by scallDataipt from API function define.
/// @details
/// @date       2025-09-12
/// @author     kai.ju
/// @version    1.2.0
///
/// ================================================================

#include "external_authentication_proxy.h"

#include "ara/diag/diag_error_domain.h"
#include "cancellation/cancellation_handler_factory.h"
#include "log/log.h"
#include "netProxy/net_proxy.h"
#include "serialization/serialization.h"
#include "thread_pool/thread_pool.h"
namespace isoft {
namespace dm {
namespace dic {

constexpr uint8_t kFuncIDHasClientAddress{1U};
constexpr uint8_t kFuncIDSetAuthState{2U};
constexpr uint8_t kFuncIDSetNotify{3U};
constexpr uint8_t kFuncIDAddDynamicAccessList{4U};
constexpr uint8_t kFuncIDClearDynamicAccessList{5U};
constexpr uint8_t kFuncIDRevoke{6U};
constexpr uint8_t kFuncIDRefresh{7U};
constexpr uint8_t kFuncIDGetAllAddress{8U};

ExternalAuthenticationProxy::ExternalAuthenticationProxy(uint16_t const &instanceId, uint32_t const &serviceInstanceId)
    : BussinessClientProxy{serviceInstanceId, instanceId}
{
    RegisterNotificationCallBack([this](FuncData const &funcData) { _notify(funcData); });
}

void ExternalAuthenticationProxy::RegisterService(ara::diag::ExternalAuthentication *const &gdi) { serviceObj_ = gdi; }

void ExternalAuthenticationProxy::SetReentrancyType(ara::diag::ReentrancyType const &reentrancyType) noexcept
{
    bool enable{true};
    enable = ara::diag::ReentrancyType::kFully == reentrancyType;
    // FullyReentrancy(enable);
    std::ignore     = enable;
    reentrancyType_ = reentrancyType;
}

bool ExternalAuthenticationProxy::HasClientAddress(std::uint16_t address) noexcept
{
    static uint8_t s_CallId{0U};
    ara::core::Result< bool > const result{SyncCallFunc< bool >(kFuncIDHasClientAddress, s_CallId, address)};
    if (result.HasValue()) {
        bool ret = result.Value();
        return ret;
    }
    return false;
}

void ExternalAuthenticationProxy::SetAuthState(std::uint16_t address,
                                               bool isAuth,
                                               std::vector< std::string > &roleList,  // NOLINE
                                               std::uint64_t msecond) noexcept
{
    static uint8_t s_CallId{0U};
    ara::core::Vector< ara::core::String > arRoleList{};
    for (auto &&role : roleList) {
        arRoleList.push_back(role.c_str());
    }

    ara::core::Result< void > const result{
        SyncCallFunc< void >(kFuncIDSetAuthState, s_CallId, address, isAuth, arRoleList, msecond)};
    if (result.HasValue()) {
        return;
    }
    ara::diag::common::LogWarn() << "ExternalAuthenticationProxy::SetAuthState|set auth state fails!";
    return;
}

bool ExternalAuthenticationProxy::SetNotify(std::function< void(std::uint16_t, bool) > notify) noexcept
{
    static uint8_t s_CallId{0U};

    ara::core::Result< void > result{RegisterCallBack(kFuncIDSetNotify, s_CallId)};
    if (!result.HasValue()) {
        ara::diag::common::LogWarn() << "ExternalAuthenticationProxy::SetNotify|register error";
        return false;
    }

    notify_ = std::move(notify);
    return true;
}

void ExternalAuthenticationProxy::AddDynamicAccessList(std::uint16_t address,
                                                       std::vector< std::uint8_t > dynamicAccessList) noexcept
{
    static uint8_t s_CallId{0U};
    ara::core::Result< void > const result{
        SyncCallFunc< void >(kFuncIDAddDynamicAccessList, s_CallId, address, std::move(dynamicAccessList))};
    if (result.HasValue()) {
        return;
    }
    ara::diag::common::LogWarn() << "ExternalAuthenticationProxy::AddDynamicAccessList|add dynamic access "
                                    "list fails!";
    return;
}

void ExternalAuthenticationProxy::SetDynamicAccessList(std::uint16_t address,
                                                       std::vector< std::uint8_t > dynamicAccessList) noexcept
{
    static uint8_t s_CallId{0U};
    ara::core::Result< void > const result{
        SyncCallFunc< void >(kFuncIDClearDynamicAccessList, s_CallId, address, std::move(dynamicAccessList))};
    if (result.HasValue()) {
        return;
    }
    ara::diag::common::LogWarn() << "ExternalAuthenticationProxy::SetDynamicAccessList|clear dynamic "
                                    "access list fails!";
    return;
}

void ExternalAuthenticationProxy::Revoke(std::uint16_t address) noexcept
{
    static uint8_t s_CallId{0U};
    ara::core::Result< void > const result{SyncCallFunc< void >(kFuncIDRevoke, s_CallId, address)};
    if (result.HasValue()) {
        return;
    }
    ara::diag::common::LogWarn() << "ExternalAuthenticationProxy::ClearDynamicAccessList|revoke fails!";
    return;
}

void ExternalAuthenticationProxy::Refresh(std::uint16_t address) noexcept
{
    static uint8_t s_CallId{0U};
    ara::core::Result< void > const result{SyncCallFunc< void >(kFuncIDRefresh, s_CallId, address)};
    if (result.HasValue()) {
        return;
    }
    ara::diag::common::LogWarn() << "ExternalAuthenticationProxy::Refresh|refresh fails!";
    return;
}

void ExternalAuthenticationProxy::_notify(FuncData const &funcData) const
{
    switch (static_cast< int >(funcData.funcId)) {
        case kFuncIDSetNotify: {
            if (nullptr != notify_) {
                std::uint16_t address{};
                bool state{};
                if (serialize::Deserialize(funcData.data, address, state) > 0) {
                    notify_(address, state);
                }
            } else {
                ara::diag::common::LogError() << "ExternalAuthenticationProxy::_notify|notify_ is nullptr";
            }
        } break;
        default: {
        } break;
    }
}

std::vector< std::uint16_t > ExternalAuthenticationProxy::GetAllAddress() noexcept
{
    static uint8_t s_CallId{0U};
    ara::core::Result< std::vector< std::uint16_t > > const result{
        SyncCallFunc< std::vector< std::uint16_t > >(kFuncIDGetAllAddress, s_CallId)};
    if (result.HasValue()) {
        return result.Value();
    }
    ara::diag::common::LogWarn() << "ExternalAuthenticationProxy::GetAllAddress|revoke fails!";
    return {};
}
}  // namespace dic
}  // namespace dm
}  // namespace isoft