// Disclaimer
//
// This work (specification and/or software implementation) and the material
// contained in it, as released by AUTOSAR, is for the purpose of information
// only. AUTOSAR and the companies that have contributed to it shall not be
// liable for any use of the work.
//
// The material contained in this work is protected by copyright and other
// types of intellectual property rights. The commercial exploitation of the
// material contained in this work requires a license to such intellectual
// property rights.
//
// This work may be utilized or reproduced without any modification, in any
// form or by any means, for informational purposes only. For any other
// purpose, no part of the work may be utilized or reproduced, in any form
// or by any means, without permission in writing from the publisher.
//
// The work has been developed for automotive applications only. It has
// neither been developed, nor tested for non-automotive applications.
//
// The word AUTOSAR and the AUTOSAR logo are registered trademarks.
// --------------------------------------------------------------------------

/// ================================================================
///
/// File description:
/// ----------------
/// @file       external_authentication_proxy.h
/// @brief      Generated by RPC script from API define.
/// @details
/// @date       2025-09-12
/// @author     kai.ju
/// @version    1.2.0
///
/// ================================================================

#ifndef __ExternalAuthenticationProxyCLIENTCOM_H_
#define __ExternalAuthenticationProxyCLIENTCOM_H_

#include <ara/diag/external_authentication.h>

#include <functional>

#include "ara/core/future.h"
#include "cancellation/cancellation_event_manager.h"
#include "gen_code/defines.h"
#include "netProxy/bussiness_client_proxy.h"
#include "netProxy/rpc_define.h"
namespace isoft {
namespace dm {
namespace dic {

class ExternalAuthenticationProxy : public BussinessClientProxy
{
public:
    explicit ExternalAuthenticationProxy(uint16_t const &instanceId, uint32_t const &serviceInstanceId);

    void RegisterService(ara::diag::ExternalAuthentication *const &gdi);
    void SetReentrancyType(ara::diag::ReentrancyType const &reentrancyType) noexcept;

    bool HasClientAddress(std::uint16_t address) noexcept;

    void SetAuthState(std::uint16_t address,
                      bool isAuth,
                      std::vector< std::string > &roleList,
                      std::uint64_t msecond) noexcept;

    bool SetNotify(std::function< void(std::uint16_t, bool) > notify) noexcept;

    void AddDynamicAccessList(std::uint16_t address, std::vector< std::uint8_t > dynamicAccessList) noexcept;

    void SetDynamicAccessList(std::uint16_t address, std::vector< std::uint8_t > dynamicAccessList) noexcept;

    void Revoke(std::uint16_t address) noexcept;

    void Refresh(std::uint16_t address) noexcept;

    std::vector< std::uint16_t > GetAllAddress() noexcept;

private:
    void _notify(FuncData const &funcData) const;

private:
    ara::diag::ExternalAuthentication *serviceObj_{};
    CancellationEventManager cancellationEventManager_{};
    ara::diag::ReentrancyType reentrancyType_{};
    std::function< void(std::uint16_t, bool) > notify_{};
};

}  // namespace dic
}  // namespace dm
}  // namespace isoft

#endif  // __ExternalAuthenticationProxyCLIENTCOM_H_