// Disclaimer
//
// This work (specification and/or software implementation) and the material
// contained in it, as released by AUTOSAR, is for the purpose of information
// only. AUTOSAR and the companies that have contributed to it shall not be
// liable for any use of the work.
//
// The material contained in this work is protected by copyright and other
// types of intellectual property rights. The commercial exploitation of the
// material contained in this work requires a license to such intellectual
// property rights.
//
// This work may be utilized or reproduced without any modification, in any
// form or by any means, for informational purposes only. For any other
// purpose, no part of the work may be utilized or reproduced, in any form
// or by any means, without permission in writing from the publisher.
//
// The work has been developed for automotive applications only. It has
// neither been developed, nor tested for non-automotive applications.
//
// The word AUTOSAR and the AUTOSAR logo are registered trademarks.
// --------------------------------------------------------------------------

/// ================================================================
///
/// File description:
/// ----------------
/// @file       ecu_reset_request_agent.h
/// @brief      Generated by RPC script from API define.
/// @details
/// @date       2024-12-13
/// @author     kai.ju
/// @version    1.2.0
///
/// ================================================================

#ifndef APIAGENT_ECURESETREQUESTAGENT_H_
#define APIAGENT_ECURESETREQUESTAGENT_H_

#include <functional>

#include "ara/core/future.h"
#include "ecu_reset_request_proxy.h"
namespace isoft {
namespace dm {
namespace dis {

class EcuResetRequestAgent
{
public:
    explicit EcuResetRequestAgent(uint32_t const& serviceInstanceId);

    void RegisterService(ara::diag::EcuResetRequest* const& gdi);

private:
    std::unique_ptr< EcuResetRequestProxy > proxy_{nullptr};
};

}  // namespace dis
}  // namespace dm
}  // namespace isoft

#endif  // APIAGENT_ECURESETREQUESTAGENT_H_