// Disclaimer
//
// This work (specification and/or software implementation) and the material
// contained in it, as released by AUTOSAR, is for the purpose of information
// only. AUTOSAR and the companies that have contributed to it shall not be
// liable for any use of the work.
//
// The material contained in this work is protected by copyright and other
// types of intellectual property rights. The commercial exploitation of the
// material contained in this work requires a license to such intellectual
// property rights.
//
// This work may be utilized or reproduced without any modification, in any
// form or by any means, for informational purposes only. For any other
// purpose, no part of the work may be utilized or reproduced, in any form
// or by any means, without permission in writing from the publisher.
//
// The work has been developed for automotive applications only. It has
// neither been developed, nor tested for non-automotive applications.
//
// The word AUTOSAR and the AUTOSAR logo are registered trademarks.
// --------------------------------------------------------------------------

/// ================================================================
///
/// File description:
/// ----------------
/// @file       ecu_reset_request_proxy.h
/// @brief      Generated by RPC script from API define.
/// @details
/// @date       2024-12-12
/// @author     kai.ju
/// @version    1.2.0
///
/// ================================================================

#ifndef APIAGENT_ECURESETREQUESTPROXY_H_
#define APIAGENT_ECURESETREQUESTPROXY_H_

#include <ara/diag/ecu_reset_request.h>

#include <functional>

#include "ara/core/future.h"
#include "cancellation/cancellation_event_manager.h"
#include "netProxy/bussiness_service_proxy.h"
#include "netProxy/rpc_define.h"
namespace isoft {
namespace dm {
namespace dis {

using isoft::dm::FuncData;

class EcuResetRequestProxy : public BussinessServiceProxy
{
public:
    explicit EcuResetRequestProxy(uint32_t const& serviceInstanceId);

    void RegisterService(ara::diag::EcuResetRequest* const& gdi);

private:
    void CallHandle(CallRequest&& callData) override;

    void _getLastResetCause(CallRequest&& callData);

    void _enableRapidShutdown(CallRequest&& callData);

    void _requestReset(CallRequest&& callData);

    void _executeReset(CallRequest&& callData);

private:
    ara::diag::EcuResetRequest* serviceObj_{};
    CancellationEventManager cancellationEventManager_{};
};

}  // namespace dis
}  // namespace dm
}  // namespace isoft

#endif  // APIAGENT_ECURESETREQUESTPROXY_H_