// Disclaimer
//
// This work (specification and/or software implementation) and the material
// contained in it, as released by AUTOSAR, is for the purpose of information
// only. AUTOSAR and the companies that have contributed to it shall not be
// liable for any use of the work.
//
// The material contained in this work is protected by copyright and other
// types of intellectual property rights. The commercial exploitation of the
// material contained in this work requires a license to such intellectual
// property rights.
//
// This work may be utilized or reproduced without any modification, in any
// form or by any means, for informational purposes only. For any other
// purpose, no part of the work may be utilized or reproduced, in any form
// or by any means, without permission in writing from the publisher.
//
// The work has been developed for automotive applications only. It has
// neither been developed, nor tested for non-automotive applications.
//
// The word AUTOSAR and the AUTOSAR logo are registered trademarks.
// --------------------------------------------------------------------------

/// ================================================================
///
/// File description:
/// ----------------
/// @file       ecu_reset_request_proxy.cpp
/// @brief      Generated by script from API function define.
/// @details
/// @date       2024-12-13
/// @author     kai.ju
/// @version    1.2.0
///
/// ================================================================

#include "ecu_reset_request_proxy.h"

#include "ara/diag/diag_error_domain.h"
#include "cancellation/cancellation_handler_factory.h"
#include "netProxy/net_proxy.h"
#include "serialization/serialization.h"
#include "thread_pool/thread_pool.h"

namespace isoft {
namespace dm {
namespace dis {

using ara::diag::DiagErrc;
using isoft::dm::FuncData;
using isoft::dm::RetData;

constexpr uint8_t kFuncIDGetLastResetCause{1U};
constexpr uint8_t kFuncIDEnableRapidShutdown{2U};
constexpr uint8_t kFuncIDRequestReset{3U};
constexpr uint8_t kFuncIDExecuteReset{4U};

EcuResetRequestProxy::EcuResetRequestProxy(uint32_t const &serviceInstanceId) : BussinessServiceProxy{serviceInstanceId}
{
}

void EcuResetRequestProxy::RegisterService(ara::diag::EcuResetRequest *const &gdi) { serviceObj_ = gdi; }

void EcuResetRequestProxy::CallHandle(CallRequest &&callData)
{
    if (callData.funcData.funcId == kFuncIDGetLastResetCause) {
        _getLastResetCause(std::move(callData));
    } else if (callData.funcData.funcId == kFuncIDEnableRapidShutdown) {
        _enableRapidShutdown(std::move(callData));
    } else if (callData.funcData.funcId == kFuncIDRequestReset) {
        _requestReset(std::move(callData));
    } else if (callData.funcData.funcId == kFuncIDExecuteReset) {
        _executeReset(std::move(callData));
    }
}

void EcuResetRequestProxy::_getLastResetCause(CallRequest &&callData)
{
    RetData retData;
    if (serviceObj_ != nullptr) {
        // build obj of param
        ara::core::Result< ara::diag::LastResetType > result{serviceObj_->GetLastResetCause()};
        if (result.HasValue()) {
            serialize::Serialize(retData.retData, static_cast< std::uint8_t >(result.Value()));
        } else {
            retData.errorCode = static_cast< int32_t >(result.Error().Value());
        }
    } else {
        retData.errorCode = static_cast< int32_t >(InnerErrorCode::kServiceNoFound);
    }
    isoft::dm::NetProxy::GetInstance().GetNetAccess()->ReturnResult(callData, std::move(retData));
}

void EcuResetRequestProxy::_enableRapidShutdown(CallRequest &&callData)
{
    bool enable{};
    ara::core::Map< ara::core::String, ara::core::String > metaInfoData;

    RetData retData;
    std::vector< uint8_t > buf;
    if (serviceObj_ != nullptr) {
        if (serialize::Deserialize(callData.funcData.data, enable, metaInfoData) > 0) {
            // build obj of param
            ara::diag::MetaInfo metaInfo{ara::diag::api::CreateMetaInfo(metaInfoData)};
            ara::diag::CancellationHandler cancellationHandler
                = CancellationHandlerFactory::Create(cancellationEventManager_, metaInfo);
            ara::core::Future< void > futureResult{
                serviceObj_->EnableRapidShutdown(enable, metaInfo, std::move(cancellationHandler))};
            ara::core::Result< void > result{futureResult.GetResult()};
            if (result.HasValue()) {
                retData.retData = std::move(buf);
            } else {
                retData.errorCode = static_cast< int32_t >(result.Error().Value());
            }
        }
    } else {
        retData.errorCode = static_cast< int32_t >(InnerErrorCode::kServiceNoFound);
    }
    isoft::dm::NetProxy::GetInstance().GetNetAccess()->ReturnResult(callData, std::move(retData));
}

void EcuResetRequestProxy::_requestReset(CallRequest &&callData)
{
    std::uint32_t resetTypeValue{};
    std::uint8_t id{};
    ara::core::Map< ara::core::String, ara::core::String > metaInfoData;

    RetData retData;
    std::vector< uint8_t > buf;
    if (serviceObj_ != nullptr) {
        if (serialize::Deserialize(callData.funcData.data, resetTypeValue, id, metaInfoData) > 0) {
            // build obj of param
            ara::diag::ResetRequestType resetType{static_cast< ara::diag::ResetRequestType >(resetTypeValue)};
            ara::core::Optional< std::uint8_t > opId{id};
            if (id == 0) {
                opId.reset();
            }
            ara::diag::MetaInfo metaInfo{ara::diag::api::CreateMetaInfo(metaInfoData)};
            ara::diag::CancellationHandler cancellationHandler
                = CancellationHandlerFactory::Create(cancellationEventManager_, metaInfo);
            ara::core::Future< void > futureResult{
                serviceObj_->RequestReset(resetType, opId, metaInfo, std::move(cancellationHandler))};
            ara::core::Result< void > result{futureResult.GetResult()};
            if (result.HasValue()) {
                retData.retData = std::move(buf);
            } else {
                retData.errorCode = static_cast< int32_t >(result.Error().Value());
            }
        }
    } else {
        retData.errorCode = static_cast< int32_t >(InnerErrorCode::kServiceNoFound);
    }
    isoft::dm::NetProxy::GetInstance().GetNetAccess()->ReturnResult(callData, std::move(retData));
}

void EcuResetRequestProxy::_executeReset(CallRequest &&callData)
{
    ara::core::Map< ara::core::String, ara::core::String > metaInfoData;
    RetData retData;
    std::vector< uint8_t > buf;
    if (serviceObj_ != nullptr) {
        if (serialize::Deserialize(callData.funcData.data, metaInfoData) > 0) {
            // build obj of param
            ara::diag::MetaInfo metaInfo{ara::diag::api::CreateMetaInfo(metaInfoData)};
            serviceObj_->ExecuteReset(std::move(metaInfo));
        }
    } else {
        retData.errorCode = static_cast< int32_t >(InnerErrorCode::kServiceNoFound);
    }
    isoft::dm::NetProxy::GetInstance().GetNetAccess()->ReturnResult(callData, std::move(retData));
}

}  // namespace dis
}  // namespace dm
}  // namespace isoft