// Disclaimer
//
// This work (specification and/or software implementation) and the material
// contained in it, as released by AUTOSAR, is for the purpose of information
// only. AUTOSAR and the companies that have contributed to it shall not be
// liable for any use of the work.
//
// The material contained in this work is protected by copyright and other
// types of intellectual property rights. The commercial exploitation of the
// material contained in this work requires a license to such intellectual
// property rights.
//
// This work may be utilized or reproduced without any modification, in any
// form or by any means, for informational purposes only. For any other
// purpose, no part of the work may be utilized or reproduced, in any form
// or by any means, without permission in writing from the publisher.
//
// The work has been developed for automotive applications only. It has
// neither been developed, nor tested for non-automotive applications.
//
// The word AUTOSAR and the AUTOSAR logo are registered trademarks.
// --------------------------------------------------------------------------

/// ================================================================
///
/// File description:
/// ----------------
/// @file       service_validation_proxy.cpp
/// @brief      Generated by script from API function define.
/// @details
/// @date       2024-12-23
/// @author     kai.ju
/// @version    1.2.0
///
/// ================================================================

#include "service_validation_proxy.h"

#include "ara/diag/diag_error_domain.h"
#include "cancellation/cancellation_handler_factory.h"
#include "netProxy/net_proxy.h"
#include "serialization/serialization.h"
#include "thread_pool/thread_pool.h"

namespace isoft {
namespace dm {
namespace dis {

using ara::diag::DiagErrc;
using isoft::dm::FuncData;
using isoft::dm::RetData;

constexpr uint8_t kFuncIDValidate{1U};
constexpr uint8_t kFuncIDConfirmation{2U};

ServiceValidationProxy::ServiceValidationProxy(uint32_t const &serviceInstanceId)
    : BussinessServiceProxy{serviceInstanceId}
{
}

void ServiceValidationProxy::RegisterService(ara::diag::ServiceValidation *const &gdi) { serviceObj_ = gdi; }

void ServiceValidationProxy::CallHandle(CallRequest &&callData)
{
    if (callData.funcData.funcId == kFuncIDValidate) {
        _validate(std::move(callData));
    } else if (callData.funcData.funcId == kFuncIDConfirmation) {
        _confirmation(std::move(callData));
    }
}

void ServiceValidationProxy::_validate(CallRequest &&callData) noexcept
{
    ara::core::Vector< uint8_t > requestData;
    ara::core::Map< ara::core::String, ara::core::String > metaInfoData;

    RetData retData;
    std::vector< uint8_t > buf;

    if (serviceObj_ != nullptr) {
        if (serialize::Deserialize(callData.funcData.data, requestData, metaInfoData) > 0) {
            // build obj of param
            ara::diag::MetaInfo metaInfo{ara::diag::api::CreateMetaInfo(metaInfoData)};
            ara::diag::CancellationHandler cancellationHandler
                = isoft::dm::CancellationHandlerFactory::Create(cancellationEventManager_, metaInfo);
            std::shared_ptr< isoft::dm::CancellationEvent > cancellationEventPtr
                = cancellationEventManager_.Get(metaInfo);
            RegisterOnCancel(callData.funcData.funcId, callData.funcData.callId,
                             [cancellationEventPtr]() { cancellationEventPtr->Notifier(); });
            ara::core::Future< void > futureResult{
                serviceObj_->Validate(ara::core::Span< uint8_t >(requestData), metaInfo)};
            ara::core::Result< void > result{futureResult.GetResult()};
            UnregisterOnCancel(callData.funcData.funcId, callData.funcData.callId);
            if (result.HasValue()) {
                retData.retData.clear();
            } else {
                retData.errorCode = static_cast< int32_t >(result.Error().Value());
            }
        }
    } else {
        retData.errorCode = static_cast< int32_t >(InnerErrorCode::kServiceNoFound);
    }
    isoft::dm::NetProxy::GetInstance().GetNetAccess()->ReturnResult(callData, std::move(retData));
}
void ServiceValidationProxy::_confirmation(CallRequest &&callData) noexcept
{
    std::uint32_t status{};
    ara::core::Map< ara::core::String, ara::core::String > metaInfoData;

    RetData retData;
    std::vector< uint8_t > buf;

    if (serviceObj_ != nullptr) {
        if (serialize::Deserialize(callData.funcData.data, status, metaInfoData) > 0) {
            // build obj of param
            ara::diag::ConfirmationStatusType confirmStatus{static_cast< ara::diag::ConfirmationStatusType >(status)};
            ara::diag::MetaInfo metaInfo{ara::diag::api::CreateMetaInfo(metaInfoData)};
            ara::diag::CancellationHandler cancellationHandler
                = isoft::dm::CancellationHandlerFactory::Create(cancellationEventManager_, metaInfo);
            std::shared_ptr< isoft::dm::CancellationEvent > cancellationEventPtr
                = cancellationEventManager_.Get(metaInfo);
            RegisterOnCancel(callData.funcData.funcId, callData.funcData.callId,
                             [cancellationEventPtr]() { cancellationEventPtr->Notifier(); });
            ara::core::Future< void > futureResult{serviceObj_->Confirmation(confirmStatus, metaInfo)};
            ara::core::Result< void > result{futureResult.GetResult()};
            UnregisterOnCancel(callData.funcData.funcId, callData.funcData.callId);
            if (result.HasValue()) {
                retData.retData.clear();
            } else {
                retData.errorCode = static_cast< int32_t >(result.Error().Value());
            }
        }
    } else {
        retData.errorCode = static_cast< int32_t >(InnerErrorCode::kServiceNoFound);
    }
    isoft::dm::NetProxy::GetInstance().GetNetAccess()->ReturnResult(callData, std::move(retData));
}

}  // namespace dis
}  // namespace dm
}  // namespace isoft