// Disclaimer
//
// This work (specification and/or software implementation) and the material
// contained in it, as released by AUTOSAR, is for the purpose of information
// only. AUTOSAR and the companies that have contributed to it shall not be
// liable for any use of the work.
//
// The material contained in this work is protected by copyright and other
// types of intellectual property rights. The commercial exploitation of the
// material contained in this work requires a license to such intellectual
// property rights.
//
// This work may be utilized or reproduced without any modification, in any
// form or by any means, for informational purposes only. For any other
// purpose, no part of the work may be utilized or reproduced, in any form
// or by any means, without permission in writing from the publisher.
//
// The work has been developed for automotive applications only. It has
// neither been developed, nor tested for non-automotive applications.
//
// The word AUTOSAR and the AUTOSAR logo are registered trademarks.
// --------------------------------------------------------------------------

/// ================================================================
///
/// File description:
/// ----------------
/// @file       activation_line_proxy.h
/// @brief      Generated by RPC script from API define.
/// @details
/// @date       2024-12-27
/// @author     zhanglipeng
/// @version    1.2.0
///
/// ================================================================

#ifndef __GEN_ActivationLineProxy_H_
#define __GEN_ActivationLineProxy_H_

#include <functional>

#include "ara/core/result.h"
#include "gen_code/defines.h"
#include "netProxy/bussiness_client_proxy.h"

namespace isoft {
namespace dm {
namespace dic {

class ActivationLineProxy : public BussinessClientProxy
{
public:
    explicit ActivationLineProxy(uint16_t const& instanceId, uint32_t const& serviceInstanceId);
    ara::core::Result< std::uint8_t > GetNetworkInterfaceId();
    ara::core::Result< bool > GetActivationLineState();

    void RegisterActivationLineStateNotifier(std::function< void(bool) > const& notifier);

    void RegisterOnReady(std::function< void(bool) > const& callback) noexcept;

private:
    void _notify(FuncData const& funcData) const;

private:
    std::function< void(bool) > activationLineStateCb_{nullptr};
};

}  // namespace dic
}  // namespace dm
}  // namespace isoft

#endif  // __COMMUNICATIONCONTROLSERVICECOM_H_