// Disclaimer
//
// This work (specification and/or software implementation) and the material
// contained in it, as released by AUTOSAR, is for the purpose of information
// only. AUTOSAR and the companies that have contributed to it shall not be
// liable for any use of the work.
//
// The material contained in this work is protected by copyright and other
// types of intellectual property rights. The commercial exploitation of the
// material contained in this work requires a license to such intellectual
// property rights.
//
// This work may be utilized or reproduced without any modification, in any
// form or by any means, for informational purposes only. For any other
// purpose, no part of the work may be utilized or reproduced, in any form
// or by any means, without permission in writing from the publisher.
//
// The work has been developed for automotive applications only. It has
// neither been developed, nor tested for non-automotive applications.
//
// The word AUTOSAR and the AUTOSAR logo are registered trademarks.
// --------------------------------------------------------------------------

/// ================================================================
///
/// File description:
/// ----------------
/// @file       operationCycle_agent.h
/// @brief      Generated by RPC script from API define.
/// @details
/// @date       2024-12-06
/// @author     xuhua
/// @version    1.2.0
///
/// ================================================================

#ifndef __GEN_OperationAgent_AGENT__
#define __GEN_OperationAgent_AGENT__

#include <functional>

#include "operationCycle_proxy.h"

namespace isoft {
namespace dm {
namespace dis {

class OperationCycleAgent
{
public:
    explicit OperationCycleAgent(uint32_t const& serviceInstanceId);

public:
    /// @brief Notify AA side of operation cycle status change
    /// @param operation Operation cycle status
    /// @return
    void NotifyOperationCycle(ara::diag::OperationCycleType const& operation);

    /// @brief Register callback for AA side to get operation cycle status
    /// @param callBack Callback function to be registered
    /// @return
    void RegisterGetOperationCycle(std::function< ara::diag::OperationCycleType() > const& callBack);

    /// @brief Register callback for AA side to set operation cycle status
    /// @param callBack Callback function to be registered
    /// @return
    void RegisterSetOperationCycle(std::function< void(ara::diag::OperationCycleType) > const& callBack);

private:
    std::unique_ptr< OperationCycleProxy > proxy_{nullptr};
};

}  // namespace dis
}  // namespace dm
}  // namespace isoft

#endif  // __GEN_GenericDataIdentifier_AGENT__