// Disclaimer
//
// This work (specification and/or software implementation) and the material
// contained in it, as released by AUTOSAR, is for the purpose of information
// only. AUTOSAR and the companies that have contributed to it shall not be
// liable for any use of the work.
//
// The material contained in this work is protected by copyright and other
// types of intellectual property rights. The commercial exploitation of the
// material contained in this work requires a license to such intellectual
// property rights.
//
// This work may be utilized or reproduced without any modification, in any
// form or by any means, for informational purposes only. For any other
// purpose, no part of the work may be utilized or reproduced, in any form
// or by any means, without permission in writing from the publisher.
//
// The work has been developed for automotive applications only. It has
// neither been developed, nor tested for non-automotive applications.
//
// The word AUTOSAR and the AUTOSAR logo are registered trademarks.
// --------------------------------------------------------------------------

/// ================================================================
///
/// File description:
/// ----------------
/// @file       authentication_proxy.cpp
/// @brief      Generated by scallDataipt from API function define.
/// @details
/// @date       2025-09-12
/// @author     kai.ju
/// @version    1.2.0
///
/// ================================================================

#include "authentication_proxy.h"

#include "ara/diag/diag_error_domain.h"
#include "cancellation/cancellation_handler_factory.h"
#include "netProxy/net_proxy.h"
#include "serialization/serialization.h"
#include "thread_pool/thread_pool.h"

namespace isoft {
namespace dm {
namespace dis {

constexpr uint8_t kFuncIDVerifyCertificateUnidirectional{1U};
constexpr uint8_t kFuncIDVerifyCertificateBidirectional{2U};
constexpr uint8_t kFuncIDVerifyOwnership{3U};
constexpr uint8_t kFuncIDTransmitCertificate{4U};

ara::core::Vector< uint8_t > ToVector(ara::core::Span< ara::core::Byte > value)
{
    ara::core::Vector< uint8_t > result{};
    for (auto &&i : value) {
        result.push_back(static_cast< std::uint8_t >(i));
    }
    return result;
}
AuthenticationProxy::AuthenticationProxy(uint32_t const &serviceInstanceId) : BussinessServiceProxy{serviceInstanceId}
{
}

void AuthenticationProxy::RegisterService(ara::diag::Authentication *const &gdi) { serviceObj_ = gdi; }

void AuthenticationProxy::SetReentrancyType(ara::diag::ReentrancyType const &reentrancyType) noexcept
{
    bool enable{true};
    enable = ara::diag::ReentrancyType::kFully == reentrancyType;
    FullyReentrancy(enable);
    reentrancyType_ = reentrancyType;
}

void AuthenticationProxy::CallHandle(CallRequest &&callData)
{
    if (callData.funcData.funcId == kFuncIDVerifyCertificateUnidirectional) {
        _verifyCertificateUnidirectional(std::move(callData));
    } else if (callData.funcData.funcId == kFuncIDVerifyCertificateBidirectional) {
        _verifyCertificateBidirectional(std::move(callData));
    } else if (callData.funcData.funcId == kFuncIDVerifyOwnership) {
        _verifyOwnership(std::move(callData));
    } else if (callData.funcData.funcId == kFuncIDTransmitCertificate) {
        _transmitCertificate(std::move(callData));
    }
}

void AuthenticationProxy::_verifyCertificateUnidirectional(CallRequest &&callData)
{
    std::uint8_t communicationConfiguration{};
    ara::core::Vector< std::uint8_t > clientCertificate;
    ara::core::Vector< std::uint8_t > clientChallenge;
    ara::core::Map< ara::core::String, ara::core::String > metaInfoData;
    RetData retData;
    std::vector< uint8_t > buf;

    if (serviceObj_ != nullptr) {
        if (serialize::Deserialize(callData.funcData.data, communicationConfiguration, clientCertificate,
                                   clientChallenge, metaInfoData)
            > 0) {
            ara::core::Byte communicationConfigurationByte{communicationConfiguration};
            ara::core::Span< ara::core::Byte > clientCertificateSpan{
                reinterpret_cast< ara::core::Byte * >(clientCertificate.data()), clientCertificate.size()};
            ara::core::Span< ara::core::Byte > clientChallengeSpan{
                reinterpret_cast< ara::core::Byte * >(clientChallenge.data()), clientChallenge.size()};
            ara::diag::MetaInfo metaInfo{ara::diag::api::CreateMetaInfo(metaInfoData)};
            ara::diag::CancellationHandler cancellationHandler
                = isoft::dm::CancellationHandlerFactory::Create(cancellationEventManager_, metaInfo);
            std::shared_ptr< isoft::dm::CancellationEvent > cancellationEventPtr
                = cancellationEventManager_.Get(metaInfo);
            RegisterOnCancel(callData.funcData.funcId, callData.funcData.callId,
                             [cancellationEventPtr]() { cancellationEventPtr->Notifier(); });
            ara::core::Future< std::tuple< ara::core::Span< ara::core::Byte >, ara::core::Span< ara::core::Byte > > >
                futureResult{serviceObj_->VerifyCertificateUnidirectional(communicationConfigurationByte,
                                                                          clientCertificateSpan, clientChallengeSpan,
                                                                          metaInfo, std::move(cancellationHandler))};
            ara::core::Result< std::tuple< ara::core::Span< ara::core::Byte >, ara::core::Span< ara::core::Byte > > >
                result{futureResult.GetResult()};
            UnregisterOnCancel(callData.funcData.funcId, callData.funcData.callId);
            if (result.HasValue()) {
                std::tuple< ara::core::Span< ara::core::Byte >, ara::core::Span< ara::core::Byte > > value{
                    result.Value()};
                VerifyCertificateUnidirectionalResponse rsp{};
                rsp.challengeServer          = ToVector(std::get< 0 >(value));
                rsp.ephemeralPublicKeyServer = ToVector(std::get< 1 >(value));
                serialize::Serialize(retData.retData, rsp);
            } else {
                retData.errorCode = static_cast< int32_t >(result.Error().Value());
            }
        } else {
            retData.errorCode = static_cast< int32_t >(InnerErrorCode::kServiceNoFound);
        }
    } else {
        retData.errorCode = static_cast< int32_t >(InnerErrorCode::kServiceNoFound);
    }
    isoft::dm::NetProxy::GetInstance().GetNetAccess()->ReturnResult(callData, std::move(retData));
}
void AuthenticationProxy::_verifyCertificateBidirectional(CallRequest &&callData)
{
    std::uint8_t communicationConfiguration{};
    ara::core::Vector< std::uint8_t > clientCertificate;
    ara::core::Vector< std::uint8_t > clientChallenge;
    ara::core::Map< ara::core::String, ara::core::String > metaInfoData;
    RetData retData;
    std::vector< uint8_t > buf;

    if (serviceObj_ != nullptr) {
        if (serialize::Deserialize(callData.funcData.data, communicationConfiguration, clientCertificate,
                                   clientChallenge, metaInfoData)
            > 0) {
            ara::core::Byte communicationConfigurationByte{communicationConfiguration};
            ara::core::Span< ara::core::Byte > clientCertificateSpan{
                reinterpret_cast< ara::core::Byte * >(clientCertificate.data()), clientCertificate.size()};
            ara::core::Span< ara::core::Byte > clientChallengeSpan{
                reinterpret_cast< ara::core::Byte * >(clientChallenge.data()), clientChallenge.size()};
            ara::diag::MetaInfo metaInfo{ara::diag::api::CreateMetaInfo(metaInfoData)};
            ara::diag::CancellationHandler cancellationHandler
                = isoft::dm::CancellationHandlerFactory::Create(cancellationEventManager_, metaInfo);
            std::shared_ptr< isoft::dm::CancellationEvent > cancellationEventPtr
                = cancellationEventManager_.Get(metaInfo);
            RegisterOnCancel(callData.funcData.funcId, callData.funcData.callId,
                             [cancellationEventPtr]() { cancellationEventPtr->Notifier(); });
            ara::core::Future< std::tuple< ara::core::Span< ara::core::Byte >, ara::core::Span< ara::core::Byte >,
                                           ara::core::Span< ara::core::Byte >, ara::core::Span< ara::core::Byte > > >
                futureResult{serviceObj_->VerifyCertificateBidirectional(communicationConfigurationByte,
                                                                         clientCertificateSpan, clientChallengeSpan,
                                                                         metaInfo, std::move(cancellationHandler))};
            ara::core::Result< std::tuple< ara::core::Span< ara::core::Byte >, ara::core::Span< ara::core::Byte >,
                                           ara::core::Span< ara::core::Byte >, ara::core::Span< ara::core::Byte > > >
                result{futureResult.GetResult()};
            UnregisterOnCancel(callData.funcData.funcId, callData.funcData.callId);
            if (result.HasValue()) {
                std::tuple< ara::core::Span< ara::core::Byte >, ara::core::Span< ara::core::Byte >,
                            ara::core::Span< ara::core::Byte >, ara::core::Span< ara::core::Byte > >
                    value{result.Value()};
                VerifyCertificateBidirectionalResponse rsp{};
                rsp.challengeServer          = ToVector(std::get< 0 >(value));
                rsp.certificateServer        = ToVector(std::get< 1 >(value));
                rsp.proofOfOwnershipServer   = ToVector(std::get< 2 >(value));
                rsp.ephemeralPublicKeyServer = ToVector(std::get< 3 >(value));
                serialize::Serialize(retData.retData, rsp);
            } else {
                retData.errorCode = static_cast< int32_t >(result.Error().Value());
            }
        } else {
            retData.errorCode = static_cast< int32_t >(InnerErrorCode::kServiceNoFound);
        }
    } else {
        retData.errorCode = static_cast< int32_t >(InnerErrorCode::kServiceNoFound);
    }
    isoft::dm::NetProxy::GetInstance().GetNetAccess()->ReturnResult(callData, std::move(retData));
}

void AuthenticationProxy::_verifyOwnership(CallRequest &&callData)
{
    ara::core::Vector< std::uint8_t > clientPOWN;
    ara::core::Vector< std::uint8_t > clientChallenge;
    ara::core::Map< ara::core::String, ara::core::String > metaInfoData;
    RetData retData;
    std::vector< uint8_t > buf;

    if (serviceObj_ != nullptr) {
        if (serialize::Deserialize(callData.funcData.data, clientPOWN, clientChallenge, metaInfoData) > 0) {
            ara::core::Span< ara::core::Byte > clientPOWNSpan{reinterpret_cast< ara::core::Byte * >(clientPOWN.data()),
                                                              clientPOWN.size()};
            ara::core::Span< ara::core::Byte > clientChallengeSpan{
                reinterpret_cast< ara::core::Byte * >(clientChallenge.data()), clientChallenge.size()};
            ara::diag::MetaInfo metaInfo{ara::diag::api::CreateMetaInfo(metaInfoData)};
            ara::diag::CancellationHandler cancellationHandler
                = isoft::dm::CancellationHandlerFactory::Create(cancellationEventManager_, metaInfo);
            std::shared_ptr< isoft::dm::CancellationEvent > cancellationEventPtr
                = cancellationEventManager_.Get(metaInfo);
            RegisterOnCancel(callData.funcData.funcId, callData.funcData.callId,
                             [cancellationEventPtr]() { cancellationEventPtr->Notifier(); });
            ara::core::Future< ara::core::Span< ara::core::Byte > > futureResult{serviceObj_->VerifyOwnership(
                clientPOWNSpan, clientChallengeSpan, metaInfo, std::move(cancellationHandler))};
            ara::core::Result< ara::core::Span< ara::core::Byte > > result{futureResult.GetResult()};
            UnregisterOnCancel(callData.funcData.funcId, callData.funcData.callId);
            if (result.HasValue()) {
                ara::core::Vector< std::uint8_t > value{};
                value = ToVector(result.Value());
                serialize::Serialize(retData.retData, value);
            } else {
                retData.errorCode = static_cast< int32_t >(result.Error().Value());
            }
        } else {
            retData.errorCode = static_cast< int32_t >(InnerErrorCode::kServiceNoFound);
        }
    } else {
        retData.errorCode = static_cast< int32_t >(InnerErrorCode::kServiceNoFound);
    }
    isoft::dm::NetProxy::GetInstance().GetNetAccess()->ReturnResult(callData, std::move(retData));
}

void AuthenticationProxy::_transmitCertificate(CallRequest &&callData)
{
    ara::core::Vector< std::uint8_t > certificateData;
    ara::core::Map< ara::core::String, ara::core::String > metaInfoData;
    RetData retData;
    std::vector< uint8_t > buf;

    if (serviceObj_ != nullptr) {
        if (serialize::Deserialize(callData.funcData.data, certificateData, metaInfoData) > 0) {
            ara::core::Span< ara::core::Byte > certificateDataSpan{
                reinterpret_cast< ara::core::Byte * >(certificateData.data()), certificateData.size()};
            ara::diag::MetaInfo metaInfo{ara::diag::api::CreateMetaInfo(metaInfoData)};
            ara::diag::CancellationHandler cancellationHandler
                = isoft::dm::CancellationHandlerFactory::Create(cancellationEventManager_, metaInfo);
            std::shared_ptr< isoft::dm::CancellationEvent > cancellationEventPtr
                = cancellationEventManager_.Get(metaInfo);
            RegisterOnCancel(callData.funcData.funcId, callData.funcData.callId,
                             [cancellationEventPtr]() { cancellationEventPtr->Notifier(); });
            ara::core::Future< void > futureResult{
                serviceObj_->TransmitCertificate(certificateDataSpan, metaInfo, std::move(cancellationHandler))};
            ara::core::Result< void > result{futureResult.GetResult()};
            UnregisterOnCancel(callData.funcData.funcId, callData.funcData.callId);
            if (result.HasValue()) {
                retData.retData = buf;
            } else {
                retData.errorCode = static_cast< int32_t >(result.Error().Value());
            }
        } else {
            retData.errorCode = static_cast< int32_t >(InnerErrorCode::kServiceNoFound);
        }
    } else {
        retData.errorCode = static_cast< int32_t >(InnerErrorCode::kServiceNoFound);
    }
    isoft::dm::NetProxy::GetInstance().GetNetAccess()->ReturnResult(callData, std::move(retData));
}

}  // namespace dis
}  // namespace dm
}  // namespace isoft