// Disclaimer
//
// This work (specification and/or software implementation) and the material
// contained in it, as released by AUTOSAR, is for the purpose of information
// only. AUTOSAR and the companies that have contributed to it shall not be
// liable for any use of the work.
//
// The material contained in this work is protected by copyright and other
// types of intellectual property rights. The commercial exploitation of the
// material contained in this work requires a license to such intellectual
// property rights.
//
// This work may be utilized or reproduced without any modification, in any
// form or by any means, for informational purposes only. For any other
// purpose, no part of the work may be utilized or reproduced, in any form
// or by any means, without permission in writing from the publisher.
//
// The work has been developed for automotive applications only. It has
// neither been developed, nor tested for non-automotive applications.
//
// The word AUTOSAR and the AUTOSAR logo are registered trademarks.
// --------------------------------------------------------------------------

/// ================================================================
///
/// File description:
/// ----------------
/// @file       raw_routine_agent.h
/// @brief      Generated by RPC script from API define.
/// @details
/// @date       2024-12-28
/// @author     kai.ju
/// @version    1.2.0
///
/// ================================================================

#ifndef __GEN_APIAGENT_RAWROUTINEAGENT__
#define __GEN_APIAGENT_RAWROUTINEAGENT__

#include <functional>

#include "ara/core/future.h"
#include "raw_routine_proxy.h"

namespace isoft {
namespace dm {
namespace dis {

class RawRoutineAgent
{
public:
    explicit RawRoutineAgent(uint32_t const& serviceId);
    void RegisterService(ara::diag::internal::RawRoutine* const& gdi);

    /// @brief Set reentrancy type
    /// @param reentrancyType Reentrancy type
    inline void SetReentrancyType(ara::diag::ReentrancyType const reentrancyType) noexcept
    {
        bool enable{true};
        enable = ara::diag::ReentrancyType::kFully == reentrancyType;
        proxy_->FullyReentrancy(enable);
        reentrancyType_ = reentrancyType;
    }

private:
    std::unique_ptr< RawRoutineProxy > proxy_{nullptr};
    ara::diag::ReentrancyType reentrancyType_{};
};

}  // namespace dis
}  // namespace dm
}  // namespace isoft

#endif  // __GEN_APIAGENT_RAWROUTINEAGENT__