// Disclaimer
//
// This work (specification and/or software implementation) and the material
// contained in it, as released by AUTOSAR, is for the purpose of information
// only. AUTOSAR and the companies that have contributed to it shall not be
// liable for any use of the work.
//
// The material contained in this work is protected by copyright and other
// types of intellectual property rights. The commercial exploitation of the
// material contained in this work requires a license to such intellectual
// property rights.
//
// This work may be utilized or reproduced without any modification, in any
// form or by any means, for informational purposes only. For any other
// purpose, no part of the work may be utilized or reproduced, in any form
// or by any means, without permission in writing from the publisher.
//
// The work has been developed for automotive applications only. It has
// neither been developed, nor tested for non-automotive applications.
//
// The word AUTOSAR and the AUTOSAR logo are registered trademarks.
// --------------------------------------------------------------------------

/// ================================================================
///
/// File description:
/// ----------------
/// @file       external_authentication_proxy.h
/// @brief      Generated by RPC script from API define.
/// @details
/// @date       2025-09-12
/// @author     kai.ju
/// @version    1.2.0
///
/// ================================================================

#ifndef __ExternalAuthenticationSERVICECOM_H_
#define __ExternalAuthenticationSERVICECOM_H_

#include <ara/core/span.h>

#include <functional>

#include "ara/core/future.h"
#include "cancellation/cancellation_event.h"
#include "gen_code/defines.h"
#include "netProxy/bussiness_service_proxy.h"

namespace isoft {
namespace dm {
namespace dis {
using HasClientAddressCallback = std::function< bool(std::uint16_t) >;
using SetAuthStateCallback     = std::function< void(std::uint16_t, bool, std::vector< std::string >, std::uint64_t) >;
using AddDynamicAccessListCallback = std::function< void(std::uint16_t, std::vector< std::uint8_t >) >;
using SetDynamicAccessListCallback = std::function< void(std::uint16_t, std::vector< std::uint8_t >) >;
using RevokeCallback               = std::function< void(std::uint16_t) >;
using RefreshCallback              = std::function< void(std::uint16_t) >;
using GetAllAddressCallback        = std::function< std::vector< std::uint16_t >() >;
class ExternalAuthenticationProxy : public BussinessServiceProxy
{
public:
    explicit ExternalAuthenticationProxy(uint32_t const& serviceInstanceId);

    void RegisterHasClientAddressCallback(HasClientAddressCallback callback) noexcept;
    void RegisterSetAuthStateCallback(SetAuthStateCallback callback) noexcept;
    void RegisterAddDynamicAccessListCallback(AddDynamicAccessListCallback callback) noexcept;
    void RegisterSetDynamicAccessListCallback(SetDynamicAccessListCallback callback) noexcept;
    void RegisterRevokeCallback(RevokeCallback callback) noexcept;
    void RegisterRefreshCallback(RefreshCallback callback) noexcept;
    void RegisterGetAllAddressCallback(GetAllAddressCallback callback) noexcept;

    void UpdateAuthState(std::uint16_t address, bool isAuth) noexcept;

private:
    void CallHandle(CallRequest&& callData) override;

    void _hasClientAddress(CallRequest&& callData) noexcept;

    void _setAuthState(CallRequest&& callData) noexcept;

    void _addDynamicAccessList(CallRequest&& callData) noexcept;

    void _setDynamicAccessList(CallRequest&& callData) noexcept;

    void _revoke(CallRequest&& callData) noexcept;

    void _refresh(CallRequest&& callData) noexcept;

    void _getAllAddress(CallRequest&& callData) noexcept;

    HasClientAddressCallback hasClientAddressCallback_{};
    SetAuthStateCallback setAuthStateCallback_{};
    AddDynamicAccessListCallback addDynamicAccessListCallback_{};
    SetDynamicAccessListCallback setDynamicAccessListCallback_{};
    RevokeCallback revokeCallback_{};
    RefreshCallback refreshCallback_{};
    GetAllAddressCallback getAllAddressCallback_{};
};

}  // namespace dis
}  // namespace dm
}  // namespace isoft

#endif  // __ExternalAuthenticationSERVICECOM_H_