// Disclaimer
//
// This work (specification and/or software implementation) and the material
// contained in it, as released by AUTOSAR, is for the purpose of information
// only. AUTOSAR and the companies that have contributed to it shall not be
// liable for any use of the work.
//
// The material contained in this work is protected by copyright and other
// types of intellectual property rights. The commercial exploitation of the
// material contained in this work requires a license to such intellectual
// property rights.
//
// This work may be utilized or reproduced without any modification, in any
// form or by any means, for informational purposes only. For any other
// purpose, no part of the work may be utilized or reproduced, in any form
// or by any means, without permission in writing from the publisher.
//
// The work has been developed for automotive applications only. It has
// neither been developed, nor tested for non-automotive applications.
//
// The word AUTOSAR and the AUTOSAR logo are registered trademarks.
// --------------------------------------------------------------------------

/// ================================================================
///
/// File description:
/// ----------------
/// @file       event_proxy.h
/// @brief      Generated by RPC script from API define.
/// @details
/// @date       2024-12-17
/// @author     zhanglipeng
/// @version    1.2.0
///
/// ================================================================

#ifndef __GEN_EventProxy_PROXY__
#define __GEN_EventProxy_PROXY__

#include <functional>

#include "ara/diag/event.h"
#include "gen_code/defines.h"
#include "netProxy/bussiness_service_proxy.h"

namespace isoft {
namespace dm {
namespace dis {

class EventProxy : public BussinessServiceProxy
{
public:
    explicit EventProxy(uint32_t const& serviceInstanceId);
    void CallHandle(CallRequest&& callData) override;

public:
    /// @brief Notify AA of event status change
    /// @param status Event status
    /// @return
    void NotifyEventStatus(uint8_t const status);

    /// @brief Register callback for AA side to get event status
    /// @param callBack Callback function to be registered
    /// @return
    void RegisterGetEventStatus(std::function< std::uint8_t() > const& callBack);

    /// @brief Register callback for AA side to get WIR status
    /// @param callBack Callback function to be registered
    /// @return
    void RegisterGetLatchedWIRStatus(std::function< bool() > const& callBack);

    /// @brief Register callback for AA side to set WIR status
    /// @param callBack Callback function to be registered
    /// @return
    void RegisterSetLatchedWIRStatus(std::function< int32_t(bool) > const& callBack);

    /// @brief Register callback for AA side to get DTC number
    /// @param callBack Callback function to be registered
    /// @return
    void RegisterGetDTCNumber(std::function< std::int32_t(std::uint8_t, std::uint32_t&) > const& callBack);

    /// @brief Register callback for AA side to get debounce status
    /// @param callBack Callback function to be registered
    /// @return
    void RegisterGetDebouncingStatus(std::function< uint8_t() > const& callBack);

    /// @brief Register callback for AA side to get FDC
    /// @param callBack Callback function to be registered
    /// @return
    void RegisterGetFaultDetectionCounter(std::function< std::int8_t() > const& callBack);

    /// @brief Register callback for AA side to get event test status
    /// @param callBack Callback function to be registered
    /// @return
    void RegisterGetTestComplete(std::function< bool() > const& callBack);

private:
    void _getEventStatus(CallRequest&& callData);
    void _getLatchedWIRStatus(CallRequest&& callData);
    void _setLatchedWIRStatus(CallRequest&& callData);
    void _getDTCNumber(CallRequest&& callData);
    void _getDebouncingStatus(CallRequest&& callData);
    void _getFaultDetectionCounter(CallRequest&& callData);
    void _getTestComplete(CallRequest&& callData);

private:
    std::function< std::uint8_t() > getEventStatusCb_{nullptr};
    std::function< bool() > getLatchedWIRStatusCb_{nullptr};
    std::function< int32_t(bool const) > setLatchedWIRStatusCb_{nullptr};
    std::function< std::int32_t(std::uint8_t, std::uint32_t&) > getDTCNumberCb_{nullptr};
    std::function< uint8_t() > getDebouncingStatusCb_{nullptr};
    std::function< std::int8_t() > getFaultDetectionCounterCb_{nullptr};
    std::function< bool() > getTestCompleteCb_{nullptr};
};

}  // namespace dis
}  // namespace dm
}  // namespace isoft

#endif  // __GEN_GenericDataIdentifier_AGENT__