// Disclaimer
//
// This work (specification and/or software implementation) and the material
// contained in it, as released by AUTOSAR, is for the purpose of information
// only. AUTOSAR and the companies that have contributed to it shall not be
// liable for any use of the work.
//
// The material contained in this work is protected by copyright and other
// types of intellectual property rights. The commercial exploitation of the
// material contained in this work requires a license to such intellectual
// property rights.
//
// This work may be utilized or reproduced without any modification, in any
// form or by any means, for informational purposes only. For any other
// purpose, no part of the work may be utilized or reproduced, in any form
// or by any means, without permission in writing from the publisher.
//
// The work has been developed for automotive applications only. It has
// neither been developed, nor tested for non-automotive applications.
//
// The word AUTOSAR and the AUTOSAR logo are registered trademarks.
// --------------------------------------------------------------------------

/// ================================================================
///
/// File description:
/// ----------------
/// @file       authentication_proxy.h
/// @brief      Generated by RPC script from API define.
/// @details
/// @date       2025-09-12
/// @author     kai.ju
/// @version    1.2.0
///
/// ================================================================

#ifndef __AuthenticationSERVICECOM_H_
#define __AuthenticationSERVICECOM_H_

#include <ara/core/span.h>

#include <functional>

#include "ara/core/future.h"
#include "cancellation/cancellation_event.h"
#include "gen_code/defines.h"
#include "netProxy/bussiness_client_proxy.h"

namespace isoft {
namespace dm {
namespace dic {

class AuthenticationProxy : public BussinessClientProxy
{
public:
    explicit AuthenticationProxy(uint16_t const& instanceId, uint32_t const& serviceInstanceId);

    ara::core::Future< VerifyCertificateUnidirectionalResponse > VerifyCertificateUnidirectional(
        std::uint8_t communicationConfiguration,
        ara::core::Vector< std::uint8_t > clientCertificate,
        ara::core::Vector< std::uint8_t > clientChallenge,
        MetaInfoMap metaInfo,
        std::shared_ptr< CancellationEvent >& cancellationEventPtr);

    ara::core::Future< VerifyCertificateBidirectionalResponse > VerifyCertificateBidirectional(
        std::uint8_t communicationConfiguration,
        ara::core::Vector< std::uint8_t > clientCertificate,
        ara::core::Vector< std::uint8_t > clientChallenge,
        MetaInfoMap metaInfo,
        std::shared_ptr< CancellationEvent >& cancellationEventPtr);

    ara::core::Future< ara::core::Vector< std::uint8_t > > VerifyOwnership(
        ara::core::Vector< std::uint8_t > clientPOWN,
        ara::core::Vector< std::uint8_t > clientEphemeralPublicKey,
        MetaInfoMap metaInfo,
        std::shared_ptr< CancellationEvent >& cancellationEventPtr);

    ara::core::Future< void > TransmitCertificate(ara::core::Vector< std::uint8_t > certificateData,
                                                  MetaInfoMap metaInfo,
                                                  std::shared_ptr< CancellationEvent >& cancellationEventPtr);

private:
};

}  // namespace dic
}  // namespace dm
}  // namespace isoft

#endif  // __AuthenticationSERVICECOM_H_