// Disclaimer
//
// This work (specification and/or software implementation) and the material
// contained in it, as released by AUTOSAR, is for the purpose of information
// only. AUTOSAR and the companies that have contributed to it shall not be
// liable for any use of the work.
//
// The material contained in this work is protected by copyright and other
// types of intellectual property rights. The commercial exploitation of the
// material contained in this work requires a license to such intellectual
// property rights.
//
// This work may be utilized or reproduced without any modification, in any
// form or by any means, for informational purposes only. For any other
// purpose, no part of the work may be utilized or reproduced, in any form
// or by any means, without permission in writing from the publisher.
//
// The work has been developed for automotive applications only. It has
// neither been developed, nor tested for non-automotive applications.
//
// The word AUTOSAR and the AUTOSAR logo are registered trademarks.
// --------------------------------------------------------------------------

/// ================================================================
///
/// File description:
/// ----------------
/// @file       security_access_proxy.cpp
/// @brief      Generated by script from API function define.
/// @details
/// @date       2024-12-23
/// @author     kai.ju
/// @version    1.2.0
///
/// ================================================================

#include "security_access_proxy.h"

#include "ara/diag/diag_error_domain.h"
#include "cancellation/cancellation_handler_factory.h"
#include "netProxy/net_proxy.h"
#include "serialization/serialization.h"
#include "thread_pool/thread_pool.h"

namespace isoft {
namespace dm {
namespace dis {

using ara::diag::DiagErrc;
using isoft::dm::FuncData;
using isoft::dm::RetData;

constexpr uint8_t kFuncIDGetSeed{1U};
constexpr uint8_t kFuncIDCompareKey{2U};
SecurityAccessProxy::SecurityAccessProxy(uint32_t const &serviceInstanceId) : BussinessServiceProxy{serviceInstanceId}
{
}

void SecurityAccessProxy::RegisterService(ara::diag::SecurityAccess *const &gdi) { serviceObj_ = gdi; }

void SecurityAccessProxy::SetReentrancyType(ara::diag::ReentrancyType const &reentrancyType) noexcept
{
    bool enable{true};
    enable = ara::diag::ReentrancyType::kFully == reentrancyType;
    FullyReentrancy(enable);
    reentrancyType_ = reentrancyType;
}

void SecurityAccessProxy::CallHandle(CallRequest &&callData)
{
    if (callData.funcData.funcId == kFuncIDGetSeed) {
        _getSeed(std::move(callData));
    } else if (callData.funcData.funcId == kFuncIDCompareKey) {
        _compareKey(std::move(callData));
    }
}

void SecurityAccessProxy::_getSeed(CallRequest &&callData) noexcept
{
    ara::core::Vector< std::uint8_t > securityAccessDataRecord;
    ara::core::Map< ara::core::String, ara::core::String > metaInfoData;

    RetData retData;
    std::vector< uint8_t > buf;

    if (serviceObj_ != nullptr) {
        if (serialize::Deserialize(callData.funcData.data, securityAccessDataRecord, metaInfoData) > 0) {
            // build obj of param
            ara::diag::MetaInfo metaInfo{ara::diag::api::CreateMetaInfo(metaInfoData)};
            ara::diag::CancellationHandler cancellationHandler
                = isoft::dm::CancellationHandlerFactory::Create(cancellationEventManager_, metaInfo);
            std::shared_ptr< isoft::dm::CancellationEvent > cancellationEventPtr
                = cancellationEventManager_.Get(metaInfo);
            RegisterOnCancel(callData.funcData.funcId, callData.funcData.callId,
                             [cancellationEventPtr]() { cancellationEventPtr->Notifier(); });
            ara::core::Future< ara::core::Span< uint8_t > > futureResult{serviceObj_->GetSeed(
                ara::core::Span< uint8_t >(securityAccessDataRecord), metaInfo, std::move(cancellationHandler))};
            ara::core::Result< ara::core::Span< uint8_t > > result{futureResult.GetResult()};
            UnregisterOnCancel(callData.funcData.funcId, callData.funcData.callId);
            if (result.HasValue()) {
                std::vector< uint8_t > seed{};
                seed.assign(result.Value().begin(), result.Value().end());
                serialize::Serialize(retData.retData, seed);
            } else {
                retData.errorCode = static_cast< int32_t >(result.Error().Value());
            }
        }
    } else {
        retData.errorCode = static_cast< int32_t >(InnerErrorCode::kServiceNoFound);
    }
    isoft::dm::NetProxy::GetInstance().GetNetAccess()->ReturnResult(callData, std::move(retData));
}
void SecurityAccessProxy::_compareKey(CallRequest &&callData) noexcept
{
    ara::core::Vector< std::uint8_t > key;
    ara::core::Map< ara::core::String, ara::core::String > metaInfoData;

    RetData retData;
    std::vector< uint8_t > buf;

    if (serviceObj_ != nullptr) {
        if (serialize::Deserialize(callData.funcData.data, key, metaInfoData) > 0) {
            // build obj of param
            ara::diag::MetaInfo metaInfo{ara::diag::api::CreateMetaInfo(metaInfoData)};
            ara::diag::CancellationHandler cancellationHandler
                = isoft::dm::CancellationHandlerFactory::Create(cancellationEventManager_, metaInfo);
            std::shared_ptr< isoft::dm::CancellationEvent > cancellationEventPtr
                = cancellationEventManager_.Get(metaInfo);
            RegisterOnCancel(callData.funcData.funcId, callData.funcData.callId,
                             [cancellationEventPtr]() { cancellationEventPtr->Notifier(); });
            ara::core::Future< ara::diag::KeyCompareResultType > futureResult{
                serviceObj_->CompareKey(ara::core::Span< uint8_t >(key), metaInfo, std::move(cancellationHandler))};
            ara::core::Result< ara::diag::KeyCompareResultType > result{futureResult.GetResult()};
            UnregisterOnCancel(callData.funcData.funcId, callData.funcData.callId);
            if (result.HasValue()) {
                std::uint32_t const resultType{static_cast< std::uint32_t >(result.Value())};
                serialize::Serialize(retData.retData, resultType);
            } else {
                retData.errorCode = static_cast< int32_t >(result.Error().Value());
            }
        }
    } else {
        retData.errorCode = static_cast< int32_t >(InnerErrorCode::kServiceNoFound);
    }
    isoft::dm::NetProxy::GetInstance().GetNetAccess()->ReturnResult(callData, std::move(retData));
}
}  // namespace dis
}  // namespace dm
}  // namespace isoft