// Disclaimer
//
// This work (specification and/or software implementation) and the material
// contained in it, as released by AUTOSAR, is for the purpose of information
// only. AUTOSAR and the companies that have contributed to it shall not be
// liable for any use of the work.
//
// The material contained in this work is protected by copyright and other
// types of intellectual property rights. The commercial exploitation of the
// material contained in this work requires a license to such intellectual
// property rights.
//
// This work may be utilized or reproduced without any modification, in any
// form or by any means, for informational purposes only. For any other
// purpose, no part of the work may be utilized or reproduced, in any form
// or by any means, without permission in writing from the publisher.
//
// The work has been developed for automotive applications only. It has
// neither been developed, nor tested for non-automotive applications.
//
// The word AUTOSAR and the AUTOSAR logo are registered trademarks.
// --------------------------------------------------------------------------

/// ================================================================
///
/// File description:
/// ----------------
/// @file       dtc_information_proxy.h
/// @brief      Generated by RPC script from API define.
/// @details
/// @date       2024-12-17
/// @author     zhanglipeng
/// @version    1.2.0
///
/// ================================================================

#ifndef __GEN_DtcInformationProxy_PROXY__
#define __GEN_DtcInformationProxy_PROXY__

#include <functional>

#include "ara/diag/dtc_information.h"
#include "gen_code/defines.h"
#include "netProxy/bussiness_service_proxy.h"

namespace isoft {
namespace dm {
namespace dis {

class DtcInformationProxy : public BussinessServiceProxy
{
public:
    explicit DtcInformationProxy(uint32_t const& serviceInstanceId);
    void CallHandle(CallRequest&& callData) override;

public:
    /// @brief Notify DTC status change
    /// @param dtcStatus DTC status
    /// @return
    void NotifyDTCStatusChanged(std::uint32_t dtc, std::uint8_t udsStatusByteOld, std::uint8_t udsStatusByteNew);

    /// @brief Notify snapshot data change
    /// @param dtcSnapshot Snapshot
    /// @return
    void NotifySnapshotRecordUpdated(SnapshotRecordUpdatedType const& dtcSnapshot);

    /// @brief Notify the change of the number of entities stored in the database
    /// @param numberOfStoredEntries Number of entities
    /// @return
    void NotifyNumberOfStoredEntries(std::uint32_t const numberOfStoredEntries);

    /// @brief Notify whether the database overflows
    /// @param isOverflow Overflow flag
    /// @return
    void NotifyEventMemoryOverflow(bool const isOverflow);

    /// @brief Notify the change of the DTC control flag
    /// @param dtcStatusType Flag
    /// @return
    void NotifyControlDtcStatus(uint8_t const dtcStatusType);

    /// @brief Register callback for AA side to get the number of stored entities in the database
    /// @param callBack Callback function to be registered
    /// @return
    void RegisterGetNumberOfStoredEntries(std::function< std::uint32_t() > const& callBack);

    /// @brief Register callback for AA side to clear DTC
    /// @param callBack Callback function to be registered
    /// @return
    void RegisterClear(std::function< int32_t(std::uint32_t const) > const& callBack);

    /// @brief Register callback for AA side to get DTC control status
    /// @param callBack Callback function to be registered
    /// @return
    void RegisterGetControlDTCStatus(std::function< std::uint8_t() > const& callBack);

    /// @brief Register callback for AA side to restore DTC status change
    /// @param callBack Callback function to be registered
    /// @return
    void RegisterEnableControlDtc(std::function< std::int32_t() > const& callBack);

    /// @brief Register callback for AA side to get current DTC status code
    /// @param callBack Callback function to be registered
    /// @return
    void RegisterGetCurrentStatus(std::function< std::int32_t(std::uint32_t const, uint8_t&) > const& callBack);

    /// @brief Register callback for AA side to get database overflow flag
    /// @param callBack Callback function to be registered
    /// @return
    void RegisterGetEventMemoryOverflow(std::function< bool() > const& callBack);

    /// @brief Register callback to get DTC suppression status
    /// @param callback Callback function to be registered
    void RegisterGetDtcSuppression(
        std::function< std::int32_t(std::uint32_t, std::uint8_t&) > const& callback) noexcept;

    /// @brief Register callback to set DTC suppression status
    /// @param callback Callback function to be registered
    void RegisterSetDtcSuppression(std::function< std::int32_t(std::uint32_t, std::uint8_t) > const& callback) noexcept;

private:
    void _getNumberOfStoredEntries(CallRequest&& callData);
    void _clear(CallRequest&& callData);
    void _getControlDTCStatus(CallRequest&& callData);
    void _enableControlDtc(CallRequest&& callData);
    void _getCurrentStatus(CallRequest&& callData);
    void _getEventMemoryOverflow(CallRequest&& callData);
    void _getDtcSuppression(CallRequest&& callData);
    void _setDtcSuppression(CallRequest&& callData);

private:
    std::function< std::uint32_t() > getNumberOfStoredEntriesCb_{nullptr};
    std::function< int32_t(std::uint32_t const) > clearCb_{nullptr};
    std::function< std::uint8_t() > getControlDTCStatusCb_{nullptr};
    std::function< std::int32_t() > enableControlDtcCb_{nullptr};
    std::function< std::int32_t(std::uint32_t const, uint8_t&) > getCurrentStatusCb_{nullptr};
    std::function< bool() > getEventMemoryOverflowCb_{nullptr};
    std::function< std::int32_t(std::uint32_t, std::uint8_t&) > getDtcSuppressionCb_{nullptr};
    std::function< std::int32_t(std::uint32_t, std::uint8_t) > setDtcSuppressionCb_{nullptr};
};

}  // namespace dis
}  // namespace dm
}  // namespace isoft

#endif  // __GEN_GenericDataIdentifier_AGENT__