// Disclaimer
//
// This work (specification and/or software implementation) and the material
// contained in it, as released by AUTOSAR, is for the purpose of information
// only. AUTOSAR and the companies that have contributed to it shall not be
// liable for any use of the work.
//
// The material contained in this work is protected by copyright and other
// types of intellectual property rights. The commercial exploitation of the
// material contained in this work requires a license to such intellectual
// property rights.
//
// This work may be utilized or reproduced without any modification, in any
// form or by any means, for informational purposes only. For any other
// purpose, no part of the work may be utilized or reproduced, in any form
// or by any means, without permission in writing from the publisher.
//
// The work has been developed for automotive applications only. It has
// neither been developed, nor tested for non-automotive applications.
//
// The word AUTOSAR and the AUTOSAR logo are registered trademarks.
// --------------------------------------------------------------------------

/// ================================================================
///
/// File description:
/// ----------------
/// @file       activation_line_proxy.cpp
/// @brief      Generated by script from API function define.
/// @details
/// @date       2024-12-27
/// @author     zhanglipeng
/// @version    1.2.0
///
/// ================================================================

#include "activation_line_proxy.h"

#include "ara/diag/diag_error_domain.h"
#include "netProxy/net_proxy.h"
#include "serialization/serialization.h"
#include "thread_pool/thread_pool.h"

namespace isoft {
namespace dm {
namespace dis {

constexpr uint8_t kFuncIDGetNetworkInterfaceId{1U};
constexpr uint8_t kFuncIDGetActivationLineState{2U};
constexpr uint8_t kFuncIDUpdateActivationLineState{3U};

ActivationLineProxy::ActivationLineProxy(uint32_t const &serviceInstanceId) : BussinessServiceProxy{serviceInstanceId}
{
    NetProxy::GetInstance().GetNetAccess()->RegisterService(
        serviceInstanceId, [this](CallRequest &&callData) { CallHandle(std::move(callData)); });
}

void ActivationLineProxy::RegisterService(ara::diag::DoIPActivationLine *const &gdi) { serviceObj_ = gdi; }

void ActivationLineProxy::UpdateActivationLineState(bool const state) noexcept
{
    std::vector< uint8_t > payLoad;
    if (serialize::Serialize(payLoad, state) < 0) {
        return;
    }
    Notify(kFuncIDUpdateActivationLineState, std::move(payLoad));
}

void ActivationLineProxy::CallHandle(CallRequest &&callData)
{
    switch (callData.funcData.funcId) {
        case kFuncIDGetNetworkInterfaceId: {
            _getNetworkInterfaceId(std::move(callData));
        } break;
        case kFuncIDGetActivationLineState: {
            _getActivationLineState(std::move(callData));
        } break;
        case kFuncIDUpdateActivationLineState: {
            Subscribe(std::move(callData));
        } break;
        default: {
        } break;
    }
}

void ActivationLineProxy::_getNetworkInterfaceId(CallRequest &&callData)
{
    RetData retData;
    std::vector< uint8_t > buf;

    if (serviceObj_ != nullptr) {
        ara::core::Future< std::uint8_t > futureResult{serviceObj_->GetNetworkInterfaceId()};
        ara::core::Result< std::uint8_t > result{futureResult.GetResult()};
        if (result.HasValue()) {
            if (serialize::Serialize(buf, result.Value()) > 0) {
                retData.retData = std::move(buf);
            }
        } else {
            retData.errorCode = static_cast< int32_t >(result.Error().Value());
        }
    } else {
        retData.errorCode = static_cast< int32_t >(InnerErrorCode::kServiceNoFound);
    }
    isoft::dm::NetProxy::GetInstance().GetNetAccess()->ReturnResult(callData, std::move(retData));
}

void ActivationLineProxy::_getActivationLineState(CallRequest &&callData)
{
    RetData retData;
    std::vector< uint8_t > buf;

    if (serviceObj_ != nullptr) {
        ara::core::Future< bool > futureResult{serviceObj_->GetActivationLineState()};
        ara::core::Result< bool > result{futureResult.GetResult()};
        if (result.HasValue()) {
            if (serialize::Serialize(buf, result.Value()) > 0) {
                retData.retData = std::move(buf);
            }
        } else {
            retData.errorCode = static_cast< int32_t >(result.Error().Value());
        }
    } else {
        retData.errorCode = static_cast< int32_t >(InnerErrorCode::kServiceNoFound);
    }
    isoft::dm::NetProxy::GetInstance().GetNetAccess()->ReturnResult(callData, std::move(retData));
}

}  // namespace dis
}  // namespace dm
}  // namespace isoft