// Disclaimer
//
// This work (specification and/or software implementation) and the material
// contained in it, as released by AUTOSAR, is for the purpose of information
// only. AUTOSAR and the companies that have contributed to it shall not be
// liable for any use of the work.
//
// The material contained in this work is protected by copyright and other
// types of intellectual property rights. The commercial exploitation of the
// material contained in this work requires a license to such intellectual
// property rights.
//
// This work may be utilized or reproduced without any modification, in any
// form or by any means, for informational purposes only. For any other
// purpose, no part of the work may be utilized or reproduced, in any form
// or by any means, without permission in writing from the publisher.
//
// The work has been developed for automotive applications only. It has
// neither been developed, nor tested for non-automotive applications.
//
// The word AUTOSAR and the AUTOSAR logo are registered trademarks.
// --------------------------------------------------------------------------

/// ================================================================
///
/// File description:
/// ----------------
/// @file       monitor_proxy.h
/// @brief      Generated by RPC script from API define.
/// @details
/// @date       2024-12-06
/// @author     xuhua
/// @version    1.2.0
///
/// ================================================================

#ifndef __GEN_MonitorProxy_PROXY__
#define __GEN_MonitorProxy_PROXY__

#include <functional>

#include "ara/diag/monitor.h"
#include "gen_code/defines.h"
#include "netProxy/bussiness_client_proxy.h"
#include "netProxy/rpc_define.h"

namespace isoft {
namespace dm {
namespace dic {

class MonitorProxy : public BussinessClientProxy
{
public:
    MonitorProxy(uint16_t const& instanceId, uint32_t const& serviceInstanceId);

    /// @brief Register callback function for AA side that monitor needs to be reinitialized
    /// @param notifier Callback function to be registered
    /// @return
    void RegisterInitMonitorNotify(std::function< void(ara::diag::InitMonitorReason reasonType) > const& notifier);

    /// @brief Register callback function for AA side of FDC change notifycation
    /// @param notifier Callback function to be registered
    /// @return
    void RegisterFaultDetectionCounterNotify(std::function< void() > const& notifier);

    /// @brief AA report an event
    /// @param ac MonitorAction type to be report
    /// @return Return void for successful
    ara::core::Result< void > SetMonitorAction(ara::diag::MonitorAction const ac);

    /// @brief Set fault detection counter(FDC)
    /// @param fdc fdc value
    /// @return Return void for successful
    ara::core::Result< void > SetFaultDetectionCounter(std::int8_t const fdc);

    /// @brief Set counter-based debounce parameters
    /// @param counter Counter value to be set
    /// @return Return void for successful
    ara::core::Result< void > SetCounterBased(ara::diag::Monitor::CounterBased const& counter);

    /// @brief Set timer-based debounce parameters
    /// @param time Time value to be set
    /// @return Return void for successful setting
    ara::core::Result< void > SetTimeBased(ara::diag::Monitor::TimeBased const& time);

private:
    void _notify(FuncData const& funcData) const;

private:
    std::function< void() > fdcNotiferCb_{nullptr};
    std::function< void(ara::diag::InitMonitorReason const) > initMonitorCb_{nullptr};
};

}  // namespace dic
}  // namespace dm
}  // namespace isoft

#endif  // __GEN_GenericDataIdentifier_PROXY__