// Disclaimer
//
// This work (specification and/or software implementation) and the material
// contained in it, as released by AUTOSAR, is for the purpose of information
// only. AUTOSAR and the companies that have contributed to it shall not be
// liable for any use of the work.
//
// The material contained in this work is protected by copyright and other
// types of intellectual property rights. The commercial exploitation of the
// material contained in this work requires a license to such intellectual
// property rights.
//
// This work may be utilized or reproduced without any modification, in any
// form or by any means, for informational purposes only. For any other
// purpose, no part of the work may be utilized or reproduced, in any form
// or by any means, without permission in writing from the publisher.
//
// The work has been developed for automotive applications only. It has
// neither been developed, nor tested for non-automotive applications.
//
// The word AUTOSAR and the AUTOSAR logo are registered trademarks.
// --------------------------------------------------------------------------

/// ================================================================
///
/// File description:
/// ----------------
/// @file       file_transfer_agent.h
/// @brief      Generated by RPC script from API define.
/// @details
/// @date       2024-12-23
/// @author     kai.ju
/// @version    1.2.0
///
/// ================================================================

#ifndef __APIAGENT_FILETRANSFERAGENT_H_
#define __APIAGENT_FILETRANSFERAGENT_H_

#include <ara/diag/file_transfer.h>

#include <functional>

#include "ara/core/future.h"
#include "file_transfer_proxy.h"
namespace isoft {
namespace dm {
namespace dis {
class ReleaseHandlerImpl;
inline void Uint8FromByte(ara::core::Vector< std::uint8_t >& output, ara::core::Vector< ara::core::Byte > const& input)
{
    ara::core::Byte const* pData{input.data()};
    std::uint8_t const* pByteData{reinterpret_cast< std::uint8_t const* >(pData)};
    output.assign(pByteData, pByteData + input.size());
}

class FileTransferServiceAgent
{
public:
    explicit FileTransferServiceAgent(uint32_t const& serviceInstanceId);

    void RegisterService(ara::diag::FileTransferService* const& gdi);
    void SetReentrancyType(ara::diag::ReentrancyType const& reentrancyType) noexcept;

    auto RequestReadFile(ara::core::String fileName,
                         ara::core::Byte dataFormatIdentifier,
                         ara::diag::MetaInfo const& metaInfo,
                         ara::diag::CancellationHandler cancellationHandler) noexcept
        -> ara::core::Result< ara::diag::FileTransferService::FileSizes >;

    auto RequestReadDirectory(ara::core::String directoryName,
                              ara::diag::MetaInfo const& metaInfo,
                              ara::diag::CancellationHandler cancellationHandler) noexcept
        -> ara::core::Result< std::uint64_t >;

    auto RequestWriteFile(ara::core::String fileName,
                          ara::core::Byte dataFormatIdentifier,
                          ara::diag::FileTransferService::FileSizes fileSizes,
                          ara::diag::FileTransferService::WriteFileMode mode,
                          ara::diag::MetaInfo const& metaInfo,
                          ara::diag::CancellationHandler cancellationHandler) noexcept -> ara::core::Result< void >;

    auto RequestResumeWriteFile(ara::core::String fileName,
                                ara::core::Byte dataFormatIdentifier,
                                ara::diag::FileTransferService::FileSizes fileSizes,
                                ara::diag::MetaInfo const& metaInfo,
                                ara::diag::CancellationHandler cancellationHandler) noexcept
        -> ara::core::Result< std::uint64_t >;

    auto DeleteFile(ara::core::String fileName,
                    ara::diag::MetaInfo const& metaInfo,
                    ara::diag::CancellationHandler cancellationHandler) noexcept -> ara::core::Result< void >;

    auto Read(std::size_t numBytesToReturn,
              ara::diag::MetaInfo const& metaInfo,
              ara::diag::CancellationHandler cancellationHandler) noexcept
        -> ara::core::Result< ara::core::Vector< ara::core::Byte > >;

    auto ExitRead(ara::diag::DataTransferExitType exitType,
                  ara::core::Span< ara::core::Byte > transferRequestParameterRecord,
                  ara::diag::MetaInfo const& metaInfo,
                  ara::diag::CancellationHandler cancellationHandler) noexcept
        -> ara::core::Result< ara::core::Vector< ara::core::Byte > >;

    auto Write(ara::core::Span< ara::core::Byte > requestData,
               ara::diag::MetaInfo const& metaInfo,
               ara::diag::CancellationHandler cancellationHandler) noexcept -> ara::core::Result< void >;

    auto ExitWrite(ara::diag::DataTransferExitType exitType,
                   ara::core::Span< ara::core::Byte > transferRequestParameterRecord,
                   ara::diag::MetaInfo const& metaInfo,
                   ara::diag::CancellationHandler cancellationHandler) noexcept
        -> ara::core::Result< ara::core::Vector< ara::core::Byte > >;

    // Extended interface
public:
    void ClearMD5()
    {
        if (serviceObj_ == nullptr) {
            return;
        }

        if (serviceObj_->GetMD5().empty()) {
            return;
        }

        serviceObj_->SetMD5(ara::core::Vector< uint8_t >{});
    }

    /// @brief Get MD5
    /// @return MD5
    ara::core::Vector< uint8_t > GetMD5()
    {
        if (serviceObj_ == nullptr) {
            return {};
        }

        return serviceObj_->GetMD5();
    }

private:
    std::unique_ptr< FileTransferServiceProxy > proxy_{nullptr};
    ara::diag::FileTransferService* serviceObj_{nullptr};
    std::shared_ptr< ara::diag::DataTransferReadSession > readSession_{};
    std::shared_ptr< ara::diag::DataTransferWriteSession > writeSession_{};
    ara::core::Span< ara::core::Byte > sharedData_{};
    std::shared_ptr< ReleaseHandlerImpl > releaseHandlerImpl_{};
};

}  // namespace dis
}  // namespace dm
}  // namespace isoft

#endif  // __APIAGENTFILETRANSFERAGENT_H_