// Disclaimer
//
// This work (specification and/or software implementation) and the material
// contained in it, as released by AUTOSAR, is for the purpose of information
// only. AUTOSAR and the companies that have contributed to it shall not be
// liable for any use of the work.
//
// The material contained in this work is protected by copyright and other
// types of intellectual property rights. The commercial exploitation of the
// material contained in this work requires a license to such intellectual
// property rights.
//
// This work may be utilized or reproduced without any modification, in any
// form or by any means, for informational purposes only. For any other
// purpose, no part of the work may be utilized or reproduced, in any form
// or by any means, without permission in writing from the publisher.
//
// The work has been developed for automotive applications only. It has
// neither been developed, nor tested for non-automotive applications.
//
// The word AUTOSAR and the AUTOSAR logo are registered trademarks.
// --------------------------------------------------------------------------

/// ================================================================
///
/// File description:
/// ----------------
/// @file       file_transfer_proxy.cpp
/// @brief      Generated by script from API function define.
/// @details
/// @date       2024-12-23
/// @author     kai.ju
/// @version    1.2.0
///
/// ================================================================

#include "file_transfer_proxy.h"

#include "ara/diag/diag_error_domain.h"
#include "cancellation/cancellation_handler_factory.h"
#include "file_transfer_agent.h"
#include "netProxy/net_proxy.h"
#include "serialization/serialization.h"
#include "thread_pool/thread_pool.h"
namespace isoft {
namespace dm {
namespace dis {

using ara::diag::DiagErrc;
using isoft::dm::FuncData;
using isoft::dm::RetData;

constexpr uint8_t kFuncIDRequestReadFile{1U};
constexpr uint8_t kFuncIDRequestReadDirectory{2U};
constexpr uint8_t kFuncIDRequestWriteFile{3U};
constexpr uint8_t kFuncIDRequestResumeWriteFile{4U};
constexpr uint8_t kFuncIDDeleteFile{5U};
constexpr uint8_t kFuncIDRead{6U};
constexpr uint8_t kFuncIDExitRead{7U};
constexpr uint8_t kFuncIDWrite{8U};
constexpr uint8_t kFuncIDExitWrite{9U};

FileTransferServiceProxy::FileTransferServiceProxy(uint32_t const &serviceInstanceId)
    : BussinessServiceProxy{serviceInstanceId}
{
}

void FileTransferServiceProxy::RegisterService(FileTransferServiceAgent *const &gdi) { serviceObj_ = gdi; }

void FileTransferServiceProxy::SetReentrancyType(ara::diag::ReentrancyType const &reentrancyType) noexcept
{
    bool enable{true};
    enable = ara::diag::ReentrancyType::kFully == reentrancyType;
    FullyReentrancy(enable);
    reentrancyType_ = reentrancyType;
}

void FileTransferServiceProxy::CallHandle(CallRequest &&callData)
{
    if (serviceObj_ == nullptr) {
        return;
    }

    /// Clear MD5 before message processing
    serviceObj_->ClearMD5();

    if (callData.funcData.funcId == kFuncIDRequestReadFile) {
        _requestReadFile(std::move(callData));
    } else if (callData.funcData.funcId == kFuncIDRequestReadDirectory) {
        _requestReadDirectory(std::move(callData));
    } else if (callData.funcData.funcId == kFuncIDRequestWriteFile) {
        _requestWriteFile(std::move(callData));
    } else if (callData.funcData.funcId == kFuncIDRequestResumeWriteFile) {
        _requestResumeWriteFile(std::move(callData));
    } else if (callData.funcData.funcId == kFuncIDDeleteFile) {
        _deleteFile(std::move(callData));
    } else if (callData.funcData.funcId == kFuncIDRead) {
        _read(std::move(callData));
    } else if (callData.funcData.funcId == kFuncIDExitRead) {
        _exitRead(std::move(callData));
    } else if (callData.funcData.funcId == kFuncIDWrite) {
        _write(std::move(callData));
    } else if (callData.funcData.funcId == kFuncIDExitWrite) {
        _exitWrite(std::move(callData));
    }

    /// Clear MD5 after message processing
    serviceObj_->ClearMD5();
}

void FileTransferServiceProxy::_requestReadFile(CallRequest &&callData) noexcept
{
    ara::core::String fileName;
    std::uint8_t dataFormatIdentifier{};
    ara::core::Map< ara::core::String, ara::core::String > metaInfoData;

    RetData retData;
    std::vector< uint8_t > buf;

    if (serviceObj_ != nullptr) {
        if (serialize::Deserialize(callData.funcData.data, fileName, dataFormatIdentifier, metaInfoData) > 0) {
            // build obj of param
            ara::diag::MetaInfo metaInfo{ara::diag::api::CreateMetaInfo(metaInfoData)};
            ara::diag::CancellationHandler cancellationHandler
                = isoft::dm::CancellationHandlerFactory::Create(cancellationEventManager_, metaInfo);
            std::shared_ptr< isoft::dm::CancellationEvent > cancellationEventPtr
                = cancellationEventManager_.Get(metaInfo);
            RegisterOnCancel(callData.funcData.funcId, callData.funcData.callId,
                             [cancellationEventPtr]() { cancellationEventPtr->Notifier(); });
            ara::core::Result< ara::diag::FileTransferService::FileSizes > result{serviceObj_->RequestReadFile(
                fileName, ara::core::Byte(dataFormatIdentifier), metaInfo, std::move(cancellationHandler))};
            UnregisterOnCancel(callData.funcData.funcId, callData.funcData.callId);
            if (result.HasValue()) {
                ara::core::Vector< uint8_t > const &vecMD5 = serviceObj_->GetMD5();
                serialize::Serialize(retData.retData, result.Value().uncompressed_size, result.Value().compressed_size,
                                     vecMD5);  /// NOLINT
            } else {
                retData.errorCode = static_cast< int32_t >(result.Error().Value());
            }
        }
    } else {
        retData.errorCode = static_cast< int32_t >(InnerErrorCode::kServiceNoFound);
    }
    isoft::dm::NetProxy::GetInstance().GetNetAccess()->ReturnResult(callData, std::move(retData));
}

void FileTransferServiceProxy::_requestReadDirectory(CallRequest &&callData) noexcept
{
    ara::core::String directoryName;
    ara::core::Map< ara::core::String, ara::core::String > metaInfoData;

    RetData retData;
    std::vector< uint8_t > buf;

    if (serviceObj_ != nullptr) {
        if (serialize::Deserialize(callData.funcData.data, directoryName, metaInfoData) > 0) {
            // build obj of param
            ara::diag::MetaInfo metaInfo{ara::diag::api::CreateMetaInfo(metaInfoData)};
            ara::diag::CancellationHandler cancellationHandler
                = isoft::dm::CancellationHandlerFactory::Create(cancellationEventManager_, metaInfo);
            std::shared_ptr< isoft::dm::CancellationEvent > cancellationEventPtr
                = cancellationEventManager_.Get(metaInfo);
            RegisterOnCancel(callData.funcData.funcId, callData.funcData.callId,
                             [cancellationEventPtr]() { cancellationEventPtr->Notifier(); });
            ara::core::Result< uint64_t > result{
                serviceObj_->RequestReadDirectory(directoryName, metaInfo, std::move(cancellationHandler))};
            UnregisterOnCancel(callData.funcData.funcId, callData.funcData.callId);
            if (result.HasValue()) {
                ara::core::Vector< uint8_t > const &vecMD5 = serviceObj_->GetMD5();
                serialize::Serialize(retData.retData, result.Value(), vecMD5);
            } else {
                retData.errorCode = static_cast< int32_t >(result.Error().Value());
            }
        }
    } else {
        retData.errorCode = static_cast< int32_t >(InnerErrorCode::kServiceNoFound);
    }
    isoft::dm::NetProxy::GetInstance().GetNetAccess()->ReturnResult(callData, std::move(retData));
}
void FileTransferServiceProxy::_requestWriteFile(CallRequest &&callData) noexcept
{
    ara::core::String fileName;
    std::uint8_t dataFormatIdentifier{};
    ara::diag::FileTransferService::FileSizes fileSizes{};
    std::uint32_t modeValue{};
    ara::core::Map< ara::core::String, ara::core::String > metaInfoData;
    ara::core::Vector< uint8_t > vecTemMD5;

    RetData retData;
    std::vector< uint8_t > buf;

    if (serviceObj_ != nullptr) {
        if (serialize::Deserialize(callData.funcData.data, fileName, dataFormatIdentifier, fileSizes.uncompressed_size,
                                   fileSizes.compressed_size, vecTemMD5, modeValue, metaInfoData)
            > 0) {
            // build obj of param
            ara::diag::FileTransferService::WriteFileMode mode{
                static_cast< ara::diag::FileTransferService::WriteFileMode >(modeValue)};
            ara::diag::MetaInfo metaInfo{ara::diag::api::CreateMetaInfo(metaInfoData)};
            ara::diag::CancellationHandler cancellationHandler
                = isoft::dm::CancellationHandlerFactory::Create(cancellationEventManager_, metaInfo);
            std::shared_ptr< isoft::dm::CancellationEvent > cancellationEventPtr
                = cancellationEventManager_.Get(metaInfo);
            RegisterOnCancel(callData.funcData.funcId, callData.funcData.callId,
                             [cancellationEventPtr]() { cancellationEventPtr->Notifier(); });
            ara::core::Result< void > result{
                serviceObj_->RequestWriteFile(fileName, ara::core::Byte(dataFormatIdentifier), fileSizes, mode,
                                              metaInfo, std::move(cancellationHandler))};
            UnregisterOnCancel(callData.funcData.funcId, callData.funcData.callId);
            if (result.HasValue()) {
                retData.retData.clear();
                ara::core::Vector< uint8_t > const &vecMD5 = serviceObj_->GetMD5();
                serialize::Serialize(retData.retData, vecMD5);
            } else {
                retData.errorCode = static_cast< int32_t >(result.Error().Value());
            }
        }
    } else {
        retData.errorCode = static_cast< int32_t >(InnerErrorCode::kServiceNoFound);
    }
    isoft::dm::NetProxy::GetInstance().GetNetAccess()->ReturnResult(callData, std::move(retData));
}
void FileTransferServiceProxy::_requestResumeWriteFile(CallRequest &&callData) noexcept
{
    ara::core::String fileName;
    std::uint8_t dataFormatIdentifier{};
    ara::diag::FileTransferService::FileSizes fileSizes{};
    ara::core::Map< ara::core::String, ara::core::String > metaInfoData;
    ara::core::Vector< uint8_t > vecTemMD5;

    RetData retData;
    std::vector< uint8_t > buf;

    if (serviceObj_ != nullptr) {
        if (serialize::Deserialize(callData.funcData.data, fileName, dataFormatIdentifier, fileSizes.uncompressed_size,
                                   fileSizes.compressed_size, vecTemMD5, metaInfoData)
            > 0) {
            // build obj of param
            ara::diag::MetaInfo metaInfo{ara::diag::api::CreateMetaInfo(metaInfoData)};
            ara::diag::CancellationHandler cancellationHandler
                = isoft::dm::CancellationHandlerFactory::Create(cancellationEventManager_, metaInfo);
            std::shared_ptr< isoft::dm::CancellationEvent > cancellationEventPtr
                = cancellationEventManager_.Get(metaInfo);
            RegisterOnCancel(callData.funcData.funcId, callData.funcData.callId,
                             [cancellationEventPtr]() { cancellationEventPtr->Notifier(); });
            ara::core::Result< std::uint64_t > result{serviceObj_->RequestResumeWriteFile(
                fileName, ara::core::Byte(dataFormatIdentifier), fileSizes, metaInfo, std::move(cancellationHandler))};
            UnregisterOnCancel(callData.funcData.funcId, callData.funcData.callId);
            if (result.HasValue()) {
                ara::core::Vector< uint8_t > const &vecMD5 = serviceObj_->GetMD5();
                serialize::Serialize(retData.retData, result.Value(), vecMD5);
            } else {
                retData.errorCode = static_cast< int32_t >(result.Error().Value());
            }
        }
    } else {
        retData.errorCode = static_cast< int32_t >(InnerErrorCode::kServiceNoFound);
    }
    isoft::dm::NetProxy::GetInstance().GetNetAccess()->ReturnResult(callData, std::move(retData));
}
void FileTransferServiceProxy::_deleteFile(CallRequest &&callData) noexcept
{
    ara::core::String fileName;
    ara::core::Map< ara::core::String, ara::core::String > metaInfoData;

    RetData retData;
    std::vector< uint8_t > buf;

    if (serviceObj_ != nullptr) {
        if (serialize::Deserialize(callData.funcData.data, fileName, metaInfoData) > 0) {
            // build obj of param
            ara::diag::MetaInfo metaInfo{ara::diag::api::CreateMetaInfo(metaInfoData)};
            ara::diag::CancellationHandler cancellationHandler
                = isoft::dm::CancellationHandlerFactory::Create(cancellationEventManager_, metaInfo);
            std::shared_ptr< isoft::dm::CancellationEvent > cancellationEventPtr
                = cancellationEventManager_.Get(metaInfo);
            RegisterOnCancel(callData.funcData.funcId, callData.funcData.callId,
                             [cancellationEventPtr]() { cancellationEventPtr->Notifier(); });
            ara::core::Result< void > result{
                serviceObj_->DeleteFile(fileName, metaInfo, std::move(cancellationHandler))};
            UnregisterOnCancel(callData.funcData.funcId, callData.funcData.callId);
            if (result.HasValue()) {
                retData.retData.clear();
                ara::core::Vector< uint8_t > const &vecMD5 = serviceObj_->GetMD5();
                serialize::Serialize(retData.retData, vecMD5);
            } else {
                retData.errorCode = static_cast< int32_t >(result.Error().Value());
            }
        }
    } else {
        retData.errorCode = static_cast< int32_t >(InnerErrorCode::kServiceNoFound);
    }
    isoft::dm::NetProxy::GetInstance().GetNetAccess()->ReturnResult(callData, std::move(retData));
}
void FileTransferServiceProxy::_read(CallRequest &&callData) noexcept
{
    std::size_t numBytesToReturn{};
    ara::core::Map< ara::core::String, ara::core::String > metaInfoData;

    RetData retData;
    std::vector< uint8_t > buf;

    if (serviceObj_ != nullptr) {
        if (serialize::Deserialize(callData.funcData.data, numBytesToReturn, metaInfoData) > 0) {
            // build obj of param
            ara::diag::MetaInfo metaInfo{ara::diag::api::CreateMetaInfo(metaInfoData)};
            ara::diag::CancellationHandler cancellationHandler
                = isoft::dm::CancellationHandlerFactory::Create(cancellationEventManager_, metaInfo);
            std::shared_ptr< isoft::dm::CancellationEvent > cancellationEventPtr
                = cancellationEventManager_.Get(metaInfo);
            RegisterOnCancel(callData.funcData.funcId, callData.funcData.callId,
                             [cancellationEventPtr]() { cancellationEventPtr->Notifier(); });
            ara::core::Result< ara::core::Vector< ara::core::Byte > > result{
                serviceObj_->Read(numBytesToReturn, metaInfo, std::move(cancellationHandler))};
            UnregisterOnCancel(callData.funcData.funcId, callData.funcData.callId);
            if (result.HasValue()) {
                std::vector< uint8_t > tranferBuf;
                Uint8FromByte(tranferBuf, result.Value());
                if (serialize::Serialize(buf, tranferBuf) > 0) {
                    retData.retData = std::move(buf);
                }
            } else {
                retData.errorCode = static_cast< int32_t >(result.Error().Value());
            }
        }
    } else {
        retData.errorCode = static_cast< int32_t >(InnerErrorCode::kServiceNoFound);
    }
    isoft::dm::NetProxy::GetInstance().GetNetAccess()->ReturnResult(callData, std::move(retData));
}
void FileTransferServiceProxy::_exitRead(CallRequest &&callData) noexcept
{
    std::uint32_t exitTypeValue{};
    ara::core::Vector< std::uint8_t > transferRequestParameterRecord;
    ara::core::Map< ara::core::String, ara::core::String > metaInfoData;

    RetData retData;
    std::vector< uint8_t > buf;

    if (serviceObj_ != nullptr) {
        if (serialize::Deserialize(callData.funcData.data, exitTypeValue, transferRequestParameterRecord, metaInfoData)
            > 0) {
            // build obj of param
            ara::core::Span< std::uint8_t > requestDataSpan{transferRequestParameterRecord};
            ara::diag::DataTransferExitType exitType{static_cast< ara::diag::DataTransferExitType >(exitTypeValue)};
            ara::diag::MetaInfo metaInfo{ara::diag::api::CreateMetaInfo(metaInfoData)};
            ara::diag::CancellationHandler cancellationHandler
                = isoft::dm::CancellationHandlerFactory::Create(cancellationEventManager_, metaInfo);
            std::shared_ptr< isoft::dm::CancellationEvent > cancellationEventPtr
                = cancellationEventManager_.Get(metaInfo);
            RegisterOnCancel(callData.funcData.funcId, callData.funcData.callId,
                             [cancellationEventPtr]() { cancellationEventPtr->Notifier(); });
            ara::core::Result< ara::core::Vector< ara::core::Byte > > result{serviceObj_->ExitRead(
                exitType, ara::core::as_writable_bytes(requestDataSpan), metaInfo, std::move(cancellationHandler))};
            UnregisterOnCancel(callData.funcData.funcId, callData.funcData.callId);
            if (result.HasValue()) {
                std::vector< uint8_t > tranferBuf;
                Uint8FromByte(tranferBuf, result.Value());
                if (serialize::Serialize(buf, tranferBuf) > 0) {
                    retData.retData = std::move(buf);
                }
            } else {
                retData.errorCode = static_cast< int32_t >(result.Error().Value());
            }
        }
    } else {
        retData.errorCode = static_cast< int32_t >(InnerErrorCode::kServiceNoFound);
    }
    isoft::dm::NetProxy::GetInstance().GetNetAccess()->ReturnResult(callData, std::move(retData));
}
void FileTransferServiceProxy::_write(CallRequest &&callData) noexcept
{
    ara::core::Vector< std::uint8_t > requestData;
    ara::core::Map< ara::core::String, ara::core::String > metaInfoData;

    RetData retData;
    std::vector< uint8_t > buf;

    if (serviceObj_ != nullptr) {
        if (serialize::Deserialize(callData.funcData.data, requestData, metaInfoData) > 0) {
            // build obj of param
            ara::diag::MetaInfo metaInfo{ara::diag::api::CreateMetaInfo(metaInfoData)};
            ara::diag::CancellationHandler cancellationHandler
                = isoft::dm::CancellationHandlerFactory::Create(cancellationEventManager_, metaInfo);
            std::shared_ptr< isoft::dm::CancellationEvent > cancellationEventPtr
                = cancellationEventManager_.Get(metaInfo);
            RegisterOnCancel(callData.funcData.funcId, callData.funcData.callId,
                             [cancellationEventPtr]() { cancellationEventPtr->Notifier(); });
            ara::core::Span< std::uint8_t > requestDataSpan{requestData};
            ara::core::Result< void > result{serviceObj_->Write(ara::core::as_writable_bytes(requestDataSpan), metaInfo,
                                                                std::move(cancellationHandler))};
            UnregisterOnCancel(callData.funcData.funcId, callData.funcData.callId);
            if (result.HasValue()) {
                retData.retData.clear();
            } else {
                retData.errorCode = static_cast< int32_t >(result.Error().Value());
            }
        }
    } else {
        retData.errorCode = static_cast< int32_t >(InnerErrorCode::kServiceNoFound);
    }
    isoft::dm::NetProxy::GetInstance().GetNetAccess()->ReturnResult(callData, std::move(retData));
}
void FileTransferServiceProxy::_exitWrite(CallRequest &&callData) noexcept
{
    std::uint32_t exitTypeValue{};
    ara::core::Vector< std::uint8_t > transferRequestParameterRecord;
    ara::core::Map< ara::core::String, ara::core::String > metaInfoData;

    RetData retData;
    std::vector< uint8_t > buf;

    if (serviceObj_ != nullptr) {
        if (serialize::Deserialize(callData.funcData.data, exitTypeValue, transferRequestParameterRecord, metaInfoData)
            > 0) {
            // build obj of param
            ara::core::Span< std::uint8_t > requestDataSpan{transferRequestParameterRecord};
            ara::diag::DataTransferExitType exitType{static_cast< ara::diag::DataTransferExitType >(exitTypeValue)};
            ara::diag::MetaInfo metaInfo{ara::diag::api::CreateMetaInfo(metaInfoData)};
            ara::diag::CancellationHandler cancellationHandler
                = isoft::dm::CancellationHandlerFactory::Create(cancellationEventManager_, metaInfo);
            std::shared_ptr< isoft::dm::CancellationEvent > cancellationEventPtr
                = cancellationEventManager_.Get(metaInfo);
            RegisterOnCancel(callData.funcData.funcId, callData.funcData.callId,
                             [cancellationEventPtr]() { cancellationEventPtr->Notifier(); });
            ara::core::Result< ara::core::Vector< ara::core::Byte > > result{serviceObj_->ExitWrite(
                exitType, ara::core::as_writable_bytes(requestDataSpan), metaInfo, std::move(cancellationHandler))};
            UnregisterOnCancel(callData.funcData.funcId, callData.funcData.callId);
            if (result.HasValue()) {
                std::vector< uint8_t > tranferBuf;
                Uint8FromByte(tranferBuf, result.Value());
                if (serialize::Serialize(buf, tranferBuf) > 0) {
                    retData.retData = std::move(buf);
                }
            } else {
                retData.errorCode = static_cast< int32_t >(result.Error().Value());
            }
        }
    } else {
        retData.errorCode = static_cast< int32_t >(InnerErrorCode::kServiceNoFound);
    }
    isoft::dm::NetProxy::GetInstance().GetNetAccess()->ReturnResult(callData, std::move(retData));
}
}  // namespace dis
}  // namespace dm
}  // namespace isoft