// Disclaimer
//
// This work (specification and/or software implementation) and the material
// contained in it, as released by AUTOSAR, is for the purpose of information
// only. AUTOSAR and the companies that have contributed to it shall not be
// liable for any use of the work.
//
// The material contained in this work is protected by copyright and other
// types of intellectual property rights. The commercial exploitation of the
// material contained in this work requires a license to such intellectual
// property rights.
//
// This work may be utilized or reproduced without any modification, in any
// form or by any means, for informational purposes only. For any other
// purpose, no part of the work may be utilized or reproduced, in any form
// or by any means, without permission in writing from the publisher.
//
// The work has been developed for automotive applications only. It has
// neither been developed, nor tested for non-automotive applications.
//
// The word AUTOSAR and the AUTOSAR logo are registered trademarks.
// --------------------------------------------------------------------------

/// ================================================================
///
/// File description:
/// ----------------
/// @file       file_transfer_proxy.h
/// @brief      Generated by RPC script from API define.
/// @details
/// @date       2024-12-23
/// @author     kai.ju
/// @version    1.2.0
///
/// ================================================================

#ifndef __APIAGENT_FILETRANSFERPROXY_H_
#define __APIAGENT_FILETRANSFERPROXY_H_

#include <ara/diag/reentrancy.h>

#include <functional>

#include "ara/core/future.h"
#include "cancellation/cancellation_event_manager.h"
#include "gen_code/defines.h"
#include "netProxy/bussiness_service_proxy.h"
#include "netProxy/rpc_define.h"
namespace isoft {
namespace dm {
namespace dis {

using isoft::dm::FuncData;
class FileTransferServiceAgent;
class FileTransferServiceProxy : public BussinessServiceProxy
{
public:
    explicit FileTransferServiceProxy(uint32_t const& serviceInstanceId);

    void RegisterService(FileTransferServiceAgent* const& gdi);
    void SetReentrancyType(ara::diag::ReentrancyType const& reentrancyType) noexcept;

private:
    void CallHandle(CallRequest&& callData) override;
    void _requestReadFile(CallRequest&& callData) noexcept;
    void _requestReadDirectory(CallRequest&& callData) noexcept;
    void _requestWriteFile(CallRequest&& callData) noexcept;
    void _requestResumeWriteFile(CallRequest&& callData) noexcept;
    void _deleteFile(CallRequest&& callData) noexcept;
    void _read(CallRequest&& callData) noexcept;
    void _exitRead(CallRequest&& callData) noexcept;
    void _write(CallRequest&& callData) noexcept;
    void _exitWrite(CallRequest&& callData) noexcept;

private:
    FileTransferServiceAgent* serviceObj_{};
    CancellationEventManager cancellationEventManager_{};
    ara::diag::ReentrancyType reentrancyType_{};
};

}  // namespace dis
}  // namespace dm
}  // namespace isoft

#endif  // __APIAGENT_FILETRANSFERPROXY_H_