// Disclaimer
//
// This work (specification and/or software implementation) and the material
// contained in it, as released by AUTOSAR, is for the purpose of information
// only. AUTOSAR and the companies that have contributed to it shall not be
// liable for any use of the work.
//
// The material contained in this work is protected by copyright and other
// types of intellectual property rights. The commercial exploitation of the
// material contained in this work requires a license to such intellectual
// property rights.
//
// This work may be utilized or reproduced without any modification, in any
// form or by any means, for informational purposes only. For any other
// purpose, no part of the work may be utilized or reproduced, in any form
// or by any means, without permission in writing from the publisher.
//
// The work has been developed for automotive applications only. It has
// neither been developed, nor tested for non-automotive applications.
//
// The word AUTOSAR and the AUTOSAR logo are registered trademarks.
// --------------------------------------------------------------------------

/// ================================================================
///
/// File description:
/// ----------------
/// @file       conversation_manager_proxy.h
/// @brief      Generated by RPC script from API define.
/// @details
/// @date       2024-12-18
/// @author     kai.ju
/// @version    1.2.0
///
/// ================================================================

#ifndef __GEN_CONVERSATIONMANAGER_PROXY__
#define __GEN_CONVERSATIONMANAGER_PROXY__

#include <functional>

#include "ara/core/future.h"
#include "ara/diag/generic_data_identifier.h"
#include "gen_code/defines.h"
#include "netProxy/bussiness_client_proxy.h"
#include "netProxy/rpc_define.h"

namespace isoft {
namespace dm {
namespace dic {

class ConversationManagerProxy : public BussinessClientProxy
{
public:
    explicit ConversationManagerProxy(uint16_t const& instanceId, uint32_t const& serviceInstanceId);

    void RegisterUpdateActiveStatusCallback(std::function< void(std::uint8_t, std::uint8_t) > callback) noexcept;

    void RegisterUpdateSessionIdCallback(std::function< void(std::uint8_t) > callback) noexcept;

    void RegisterUpdateSecurityLevelIdCallback(std::function< void(std::uint8_t) > callback) noexcept;

    ara::core::Result< std::uint8_t > GetConversationNumber() noexcept;

    ara::core::Result< std::uint8_t > GetActiveStatus(std::uint8_t index) noexcept;

    ara::core::Result< std::uint8_t > GetSessionId() noexcept;

    ara::core::Result< std::uint8_t > GetSecurityLevelId() noexcept;

    ara::core::Result< std::uint64_t > GetIdentifier(std::uint8_t const index) noexcept;

    /// @brief Get diagnostic Session name
    /// @param[in] index Conversation index value
    /// @param[in] session Session ID
    /// @return Session name
    /// @throws on overflow
    ara::core::Result< ara::core::String > GetDiagnosticSessionShortName(std::uint8_t const session) noexcept;

    /// @brief Get diagnostic SecurityLevel name
    /// @param[in] index Conversation index value
    /// @param[in] securityLevel Security level
    /// @return SecurityLevel name
    /// @throws on overflow
    ara::core::Result< ara::core::String > GetDiagnosticSecurityLevelShortName(
        std::uint8_t const securityLevel) noexcept;

    /// @brief Set to default Session
    /// @param[in] identifier Conversation identifier
    /// @return Setting result
    /// @throws on overflow
    ara::core::Result< void > ResetToDefaultSession() const noexcept;

    /// @brief Register the callback function when the network service is Ready, the callback will be called according to the current network status only after calling Start to start
    /// @return callback Callback function when the network service is Ready
    /// @throw unknown
    void RegisterOnReady(FuncOnReadyCallBack const& callback) noexcept;

    void Notify(FuncData const& funcData);
    void UpdateActiveStatus(FuncData const& funcData);
    void UpdateSessionId(FuncData const& funcData);
    void UpdateSecurityLevelId(FuncData const& funcData);

private:
    std::function< void(std::uint8_t, std::uint8_t) > updateActiveStatus_;
    std::function< void(std::uint8_t) > updateSessionId_;
    std::function< void(std::uint8_t) > updateSecurityLevelId_;
    std::mutex lock_;
};

}  // namespace dic
}  // namespace dm
}  // namespace isoft

#endif  // __GEN_CONVERSATIONMANAGER_PROXY__