// Disclaimer
//
// This work (specification and/or software implementation) and the material
// contained in it, as released by AUTOSAR, is for the purpose of information
// only. AUTOSAR and the companies that have contributed to it shall not be
// liable for any use of the work.
//
// The material contained in this work is protected by copyright and other
// types of intellectual property rights. The commercial exploitation of the
// material contained in this work requires a license to such intellectual
// property rights.
//
// This work may be utilized or reproduced without any modification, in any
// form or by any means, for informational purposes only. For any other
// purpose, no part of the work may be utilized or reproduced, in any form
// or by any means, without permission in writing from the publisher.
//
// The work has been developed for automotive applications only. It has
// neither been developed, nor tested for non-automotive applications.
//
// The word AUTOSAR and the AUTOSAR logo are registered trademarks.
// --------------------------------------------------------------------------

/// ================================================================
///
/// File description:
/// ----------------
/// @file       monitor_agent.h
/// @brief      Generated by RPC script from API define.
/// @details
/// @date       2024-12-12
/// @author     zhanglipeng
/// @version    1.2.0
///
/// ================================================================

#ifndef __GEN_MonitorAgent_AGENT__
#define __GEN_MonitorAgent_AGENT__

#include <functional>

#include "ara/core/future.h"
#include "monitor_proxy.h"

namespace isoft {
namespace dm {
namespace dis {

class MonitorAgent
{
public:
    explicit MonitorAgent(uint32_t const& serviceInstanceId);

public:
    /// @brief Notify AA side that the monitor needs to be reinitialized
    /// @param reasonType Initialization reason
    /// @return
    void NotifyInitMonitor(ara::diag::InitMonitorReason const reasonType);

    /// @brief Notify AA side to get FDC
    /// @param iFdc fdc
    /// @return
    void NotifyFaultDetectionCounter();

    /// @brief Register callback for AA side to report events
    /// @param callBack Callback function to be registered
    /// @return
    void RegisterSetMonitorAction(std::function< int32_t(ara::diag::MonitorAction) > const& callBack);

    /// @brief Register callback for AA side to set FDC
    /// @param callBack Callback function to be registered
    /// @return
    void RegisterSetFaultDetectionCounter(std::function< void(std::int8_t) > const& callBack);

    /// @brief Register callback for AA side to set counter-based debounce parameters
    /// @param callBack Callback function to be registered
    /// @return
    void RegisterSetCounterBased(std::function< void(CounterBased) > const& callBack);

    /// @brief Register callback for AA side to set timer-based debounce parameters
    /// @param callBack Callback function to be registered
    /// @return
    void RegisterSetTimeBased(std::function< void(TimeBased) > const& callBack);

private:
    std::unique_ptr< MonitorProxy > proxy_{nullptr};
};

}  // namespace dis
}  // namespace dm
}  // namespace isoft

#endif  // __GEN_GenericDataIdentifier_AGENT__