// Disclaimer
//
// This work (specification and/or software implementation) and the material
// contained in it, as released by AUTOSAR, is for the purpose of information
// only. AUTOSAR and the companies that have contributed to it shall not be
// liable for any use of the work.
//
// The material contained in this work is protected by copyright and other
// types of intellectual property rights. The commercial exploitation of the
// material contained in this work requires a license to such intellectual
// property rights.
//
// This work may be utilized or reproduced without any modification, in any
// form or by any means, for informational purposes only. For any other
// purpose, no part of the work may be utilized or reproduced, in any form
// or by any means, without permission in writing from the publisher.
//
// The work has been developed for automotive applications only. It has
// neither been developed, nor tested for non-automotive applications.
//
// The word AUTOSAR and the AUTOSAR logo are registered trademarks.
// --------------------------------------------------------------------------

/// ================================================================
///
/// File description:
/// ----------------
/// @file       download_proxy.cpp
/// @brief      Generated by script from API function define.
/// @details
/// @date       2024-12-23
/// @author     kai.ju
/// @version    1.2.0
///
/// ================================================================

#include "download_proxy.h"

#include "ara/diag/diag_error_domain.h"
#include "cancellation/cancellation_handler_factory.h"
#include "netProxy/net_proxy.h"
#include "serialization/serialization.h"
#include "thread_pool/thread_pool.h"

namespace isoft {
namespace dm {
namespace dis {

using ara::diag::DiagErrc;
using isoft::dm::FuncData;
using isoft::dm::RetData;

constexpr uint8_t kFuncIDRequestDownload{1U};
constexpr uint8_t kFuncIDDownloadData{2U};
constexpr uint8_t kFuncIDRequestDownloadExit{3U};
DownloadServiceProxy::DownloadServiceProxy(uint32_t const &serviceInstanceId) : BussinessServiceProxy{serviceInstanceId}
{
}

void DownloadServiceProxy::RegisterService(ara::diag::DownloadService *const &gdi) { serviceObj_ = gdi; }

void DownloadServiceProxy::SetReentrancyType(ara::diag::ReentrancyType const &reentrancyType) noexcept
{
    bool enable{true};
    enable = ara::diag::ReentrancyType::kFully == reentrancyType;
    FullyReentrancy(enable);
    reentrancyType_ = reentrancyType;
}

void DownloadServiceProxy::CallHandle(CallRequest &&callData)
{
    if (callData.funcData.funcId == kFuncIDRequestDownload) {
        _requestDownload(std::move(callData));
    } else if (callData.funcData.funcId == kFuncIDDownloadData) {
        _downloadData(std::move(callData));
    } else if (callData.funcData.funcId == kFuncIDRequestDownloadExit) {
        _requestDownloadExit(std::move(callData));
    }
}

void DownloadServiceProxy::_requestDownload(CallRequest &&callData)
{
    uint8_t dataFormatIdentifier{};
    uint8_t addressAndLengthFormatIdentifier{};
    ara::core::Vector< std::uint8_t > memoryAddressAndSize;
    ara::core::Map< ara::core::String, ara::core::String > metaInfoData;

    RetData retData;
    std::vector< uint8_t > buf;

    if (serviceObj_ != nullptr) {
        if (serialize::Deserialize(callData.funcData.data, dataFormatIdentifier, addressAndLengthFormatIdentifier,
                                   memoryAddressAndSize, metaInfoData)
            > 0) {
            // build obj of param
            ara::diag::MetaInfo metaInfo{ara::diag::api::CreateMetaInfo(metaInfoData)};
            ara::diag::CancellationHandler cancellationHandler
                = isoft::dm::CancellationHandlerFactory::Create(cancellationEventManager_, metaInfo);
            std::shared_ptr< isoft::dm::CancellationEvent > cancellationEventPtr
                = cancellationEventManager_.Get(metaInfo);
            RegisterOnCancel(callData.funcData.funcId, callData.funcData.callId,
                             [cancellationEventPtr]() { cancellationEventPtr->Notifier(); });
            ara::core::Future< void > futureResult{serviceObj_->RequestDownload(
                dataFormatIdentifier, addressAndLengthFormatIdentifier,
                ara::core::Span< std::uint8_t >(memoryAddressAndSize), metaInfo, std::move(cancellationHandler))};
            ara::core::Result< void > result{futureResult.GetResult()};
            UnregisterOnCancel(callData.funcData.funcId, callData.funcData.callId);
            if (result.HasValue()) {
                retData.retData.clear();
            } else {
                retData.errorCode = static_cast< int32_t >(result.Error().Value());
            }
        }
    } else {
        retData.errorCode = static_cast< int32_t >(InnerErrorCode::kServiceNoFound);
    }
    isoft::dm::NetProxy::GetInstance().GetNetAccess()->ReturnResult(callData, std::move(retData));
}
void DownloadServiceProxy::_downloadData(CallRequest &&callData)
{
    ara::core::Vector< std::uint8_t > transferRequestParameterRecord;
    ara::core::Map< ara::core::String, ara::core::String > metaInfoData;

    RetData retData;
    std::vector< uint8_t > buf;

    if (serviceObj_ != nullptr) {
        if (serialize::Deserialize(callData.funcData.data, transferRequestParameterRecord, metaInfoData) > 0) {
            // build obj of param
            ara::diag::MetaInfo metaInfo{ara::diag::api::CreateMetaInfo(metaInfoData)};
            ara::diag::CancellationHandler cancellationHandler
                = isoft::dm::CancellationHandlerFactory::Create(cancellationEventManager_, metaInfo);
            std::shared_ptr< isoft::dm::CancellationEvent > cancellationEventPtr
                = cancellationEventManager_.Get(metaInfo);
            RegisterOnCancel(callData.funcData.funcId, callData.funcData.callId,
                             [cancellationEventPtr]() { cancellationEventPtr->Notifier(); });
            ara::core::Future< ara::diag::DownloadService::OperationOutput > futureResult{
                serviceObj_->DownloadData(ara::core::Span< std::uint8_t >(transferRequestParameterRecord), metaInfo,
                                          std::move(cancellationHandler))};
            ara::core::Result< ara::diag::DownloadService::OperationOutput > result{futureResult.GetResult()};
            UnregisterOnCancel(callData.funcData.funcId, callData.funcData.callId);
            if (result.HasValue()) {
                serialize::Serialize(retData.retData, result.Value().responseData);
            } else {
                retData.errorCode = static_cast< int32_t >(result.Error().Value());
            }
        }
    } else {
        retData.errorCode = static_cast< int32_t >(InnerErrorCode::kServiceNoFound);
    }
    isoft::dm::NetProxy::GetInstance().GetNetAccess()->ReturnResult(callData, std::move(retData));
}
void DownloadServiceProxy::_requestDownloadExit(CallRequest &&callData)
{
    ara::core::Vector< std::uint8_t > transferRequestParameterRecord;
    ara::core::Map< ara::core::String, ara::core::String > metaInfoData;

    RetData retData;
    std::vector< uint8_t > buf;

    if (serviceObj_ != nullptr) {
        if (serialize::Deserialize(callData.funcData.data, transferRequestParameterRecord, metaInfoData) > 0) {
            // build obj of param
            ara::diag::MetaInfo metaInfo{ara::diag::api::CreateMetaInfo(metaInfoData)};
            ara::diag::CancellationHandler cancellationHandler
                = isoft::dm::CancellationHandlerFactory::Create(cancellationEventManager_, metaInfo);
            std::shared_ptr< isoft::dm::CancellationEvent > cancellationEventPtr
                = cancellationEventManager_.Get(metaInfo);
            RegisterOnCancel(callData.funcData.funcId, callData.funcData.callId,
                             [cancellationEventPtr]() { cancellationEventPtr->Notifier(); });
            ara::core::Future< ara::diag::DownloadService::OperationOutput > futureResult{
                serviceObj_->RequestDownloadExit(ara::core::Span< std::uint8_t >(transferRequestParameterRecord),
                                                 metaInfo, std::move(cancellationHandler))};
            ara::core::Result< ara::diag::DownloadService::OperationOutput > result{futureResult.GetResult()};
            UnregisterOnCancel(callData.funcData.funcId, callData.funcData.callId);
            if (result.HasValue()) {
                serialize::Serialize(retData.retData, result.Value().responseData);
            } else {
                retData.errorCode = static_cast< int32_t >(result.Error().Value());
            }
        }
    } else {
        retData.errorCode = static_cast< int32_t >(InnerErrorCode::kServiceNoFound);
    }
    isoft::dm::NetProxy::GetInstance().GetNetAccess()->ReturnResult(callData, std::move(retData));
}

}  // namespace dis
}  // namespace dm
}  // namespace isoft