// Disclaimer
//
// This work (specification and/or software implementation) and the material
// contained in it, as released by AUTOSAR, is for the purpose of information
// only. AUTOSAR and the companies that have contributed to it shall not be
// liable for any use of the work.
//
// The material contained in this work is protected by copyright and other
// types of intellectual property rights. The commercial exploitation of the
// material contained in this work requires a license to such intellectual
// property rights.
//
// This work may be utilized or reproduced without any modification, in any
// form or by any means, for informational purposes only. For any other
// purpose, no part of the work may be utilized or reproduced, in any form
// or by any means, without permission in writing from the publisher.
//
// The work has been developed for automotive applications only. It has
// neither been developed, nor tested for non-automotive applications.
//
// The word AUTOSAR and the AUTOSAR logo are registered trademarks.
// --------------------------------------------------------------------------

/// ================================================================
///
/// File description:
/// ----------------
/// @file       dtc_information_agent.h
/// @brief      Generated by RPC script from API define.
/// @details
/// @date       2024-12-17
/// @author     zhanglipeng
/// @version    1.2.0
///
/// ================================================================

#ifndef __GEN_DtcInformationAgent_AGENT__
#define __GEN_DtcInformationAgent_AGENT__

#include <functional>

#include "dtc_information_proxy.h"

namespace isoft {
namespace dm {
namespace dic {

class DtcInformationAgent
{
public:
    DtcInformationAgent(uint16_t const& instanceId, uint32_t const& serviceInstanceId);

public:
    /// @brief Register the callback function when DTC status changed
    /// @param notifier Callback function to be register
    /// @return
    void RegisterDTCStatusChangedNotifier(
        std::function< void(std::uint32_t dtc,
                            ara::diag::DTCInformation::UdsDtcStatusByteType,
                            ara::diag::DTCInformation::UdsDtcStatusByteType) > const& notifier);

    /// @brief Register the callback function when snapshot data updated
    /// @param notifier Callback function to be register
    /// @return
    void RegisterSnapshotRecordUpdatedNotifier(
        std::function< void(ara::diag::DTCInformation::SnapshotRecordUpdatedType) > const& notifier);

    /// @brief Register the callback function when the number of entities stored in the database changed
    /// @param notifier Callback function to be register
    /// @return
    void RegisterNumberOfStoredEntriesNotifier(std::function< void(std::uint32_t) > const& notifier);

    /// @brief Register the callback function when the database has overflowed
    /// @param notifier Callback function to be register
    /// @return
    void RegisterEventMemoryOverflowNotifier(std::function< void(bool) > const& notifier);

    /// @brief Register the callback function when controlling DTC flag changed
    /// @param notifier Callback function to be register
    /// @return
    void RegisterControlDtcStatusNotifier(std::function< void(ara::diag::ControlDtcStatusType) > const& notifier);

    /// @brief Get the number of entities stored in the database
    /// @return Return 0 for success
    ara::core::Result< std::uint32_t > GetNumberOfStoredEntries();

    /// @brief Clear a group of DTCs
    /// @param dtcGroup the group id to be clear
    /// @return Return 0 for success
    ara::core::Result< void > Clear(std::uint32_t const& dtcGroup);

    /// @brief Get the control status of DTC
    /// @return Return 0 for success
    ara::core::Result< ara::diag::ControlDtcStatusType > GetControlDTCStatus();

    /// @brief restore control DTC status
    /// @return Return 0 for success
    ara::core::Result< void > EnableControlDtc();

    /// @brief Get the current status code of DTC
    /// @param dtc DTC value to be obtained
    /// @return Return 0 for success
    ara::core::Result< ara::diag::DTCInformation::UdsDtcStatusByteType > GetCurrentStatus(std::uint32_t const& dtc);

    /// @brief Get the database overflow flag
    /// @return Return 0 for success
    ara::core::Result< bool > GetEventMemoryOverflow();

    /// @brief Get the suppression status of DTC
    /// @param dtc DTC value to be obtained
    /// @return Return specific status
    ara::core::Result< ara::diag::DTCInformation::DtcSuppressionType > GetDtcSuppression(
        std::uint32_t const& dtc) noexcept;

    /// @brief Set the suppression status of DTC
    /// @param dtc dtcValue to be set
    /// @param suppressionStatus Suppression status
    /// @return Execution result
    ara::core::Result< void > SetDtcSuppression(
        std::uint32_t dtc, ara::diag::DTCInformation::DtcSuppressionType suppressionStatus) noexcept;

    /// @brief Determine whether the service is ready
    /// @return true: Ready
    bool IsServiceReady();

private:
    std::unique_ptr< DtcInformationProxy > proxy_{nullptr};
    uint16_t const kServiceId{1U};
};

}  // namespace dic
}  // namespace dm
}  // namespace isoft

#endif  // __GEN_GenericDataIdentifier_AGENT__