// Disclaimer
//
// This work (specification and/or software implementation) and the material
// contained in it, as released by AUTOSAR, is for the purpose of information
// only. AUTOSAR and the companies that have contributed to it shall not be
// liable for any use of the work.
//
// The material contained in this work is protected by copyright and other
// types of intellectual property rights. The commercial exploitation of the
// material contained in this work requires a license to such intellectual
// property rights.
//
// This work may be utilized or reproduced without any modification, in any
// form or by any means, for informational purposes only. For any other
// purpose, no part of the work may be utilized or reproduced, in any form
// or by any means, without permission in writing from the publisher.
//
// The work has been developed for automotive applications only. It has
// neither been developed, nor tested for non-automotive applications.
//
// The word AUTOSAR and the AUTOSAR logo are registered trademarks.
// --------------------------------------------------------------------------

/// ================================================================
///
/// File description:
/// ----------------
/// @file       dtc_information_proxy.h
/// @brief      Generated by RPC script from API define.
/// @details
/// @date       2024-12-17
/// @author     zhanglipeng
/// @version    1.2.0
///
/// ================================================================

#ifndef __GEN_DtcInformationProxy_PROXY__
#define __GEN_DtcInformationProxy_PROXY__

#include <functional>

#include "ara/diag/dtc_information.h"
#include "gen_code/defines.h"
#include "netProxy/bussiness_client_proxy.h"
#include "netProxy/rpc_define.h"

namespace isoft {
namespace dm {
namespace dic {

class DtcInformationProxy : public BussinessClientProxy
{
public:
    DtcInformationProxy(uint16_t const& instanceId, uint32_t const& serviceInstanceId);

    /// @brief Register callback function for DTC status change notification
    /// @param dtcStatus Callback function to be registered
    /// @return
    void RegisterDTCStatusChangedNotifier(
        std::function< void(std::uint32_t dtc,
                            ara::diag::DTCInformation::UdsDtcStatusByteType,
                            ara::diag::DTCInformation::UdsDtcStatusByteType) > const& notifier);

    /// @brief Register callback function for snapshot data updated notification
    /// @param notifier Callback function to be registered
    /// @return
    void RegisterSnapshotRecordUpdatedNotifier(
        std::function< void(ara::diag::DTCInformation::SnapshotRecordUpdatedType) > const& notifier);

    /// @brief Register callback function for the change of the number of entities stored in the database notification
    /// @param notifier Callback function to be registered
    /// @return
    void RegisterNumberOfStoredEntriesNotifier(std::function< void(std::uint32_t) > const& notifier);

    /// @brief Register callback function for whether the database has overflowed notification
    /// @param notifier Callback function to be registered
    /// @return
    void RegisterEventMemoryOverflowNotifier(std::function< void(bool) > const& notifier);

    /// @brief Register callback function for the change of the flag controlling DTC notification
    /// @param notifier Callback function to be registered
    /// @return Return 0 for success
    void RegisterControlDtcStatusNotifier(std::function< void(ara::diag::ControlDtcStatusType) > const& notifier);

    /// @brief Get the number of entities stored in the database
    /// @param
    /// @return Return 0 for success
    ara::core::Result< std::uint32_t > GetNumberOfStoredEntries();

    /// @brief Clear a group of DTCs
    /// @param dtcGroup the group id to be clear
    /// @return Return 0 for success
    ara::core::Result< void > Clear(std::uint32_t const& dtcGroup);

    /// @brief Get the control status of DTC
    /// @param
    /// @return Return 0 for success
    ara::core::Result< ara::diag::ControlDtcStatusType > GetControlDTCStatus();

    /// @brief Restore DTC status change
    /// @param
    /// @return Return 0 for success
    ara::core::Result< void > EnableControlDtc();

    /// @brief Get the current status code of DTC
    /// @param
    /// @return Return 0 for success
    ara::core::Result< ara::diag::DTCInformation::UdsDtcStatusByteType > GetCurrentStatus(std::uint32_t const& dtc);

    /// @brief Get the database overflow flag
    /// @param
    /// @return Return 0 for success
    ara::core::Result< bool > GetEventMemoryOverflow();

    /// @brief Get the suppression status of DTC
    /// @param dtc dtcValue to be obtained
    /// @return Return specific status
    ara::core::Result< ara::diag::DTCInformation::DtcSuppressionType > GetDtcSuppression(
        std::uint32_t const& dtc) noexcept;

    /// @brief Set the suppression status of DTC
    /// @param dtc dtcValue to be set
    /// @param suppressionStatus Suppression status
    /// @return Execution result
    ara::core::Result< void > SetDtcSuppression(
        std::uint32_t dtc, ara::diag::DTCInformation::DtcSuppressionType suppressionStatus) noexcept;

private:
    void _notify(FuncData const& funcData) const;

private:
    std::function< void(std::uint32_t dtc,
                        ara::diag::DTCInformation::UdsDtcStatusByteType,
                        ara::diag::DTCInformation::UdsDtcStatusByteType) >
        dtcStatusChangedNotifierCb_{nullptr};
    std::function< void(ara::diag::DTCInformation::SnapshotRecordUpdatedType) > snapshotRecordUpdatedNotifierCb_{
        nullptr};
    std::function< void(std::uint32_t) > numberOfStoredEntriesNotifierCb_{nullptr};
    std::function< void(bool) > eventMemoryOverflowNotifierCb_{nullptr};
    std::function< void(ara::diag::ControlDtcStatusType) > controlDtcStatusNotifierCb_{nullptr};
};

}  // namespace dic
}  // namespace dm
}  // namespace isoft

#endif  // __GEN_GenericDataIdentifier_PROXY__