// Disclaimer
//
// This work (specification and/or software implementation) and the material
// contained in it, as released by AUTOSAR, is for the purpose of information
// only. AUTOSAR and the companies that have contributed to it shall not be
// liable for any use of the work.
//
// The material contained in this work is protected by copyright and other
// types of intellectual property rights. The commercial exploitation of the
// material contained in this work requires a license to such intellectual
// property rights.
//
// This work may be utilized or reproduced without any modification, in any
// form or by any means, for informational purposes only. For any other
// purpose, no part of the work may be utilized or reproduced, in any form
// or by any means, without permission in writing from the publisher.
//
// The work has been developed for automotive applications only. It has
// neither been developed, nor tested for non-automotive applications.
//
// The word AUTOSAR and the AUTOSAR logo are registered trademarks.
// --------------------------------------------------------------------------

/// ================================================================
///
/// File description:
/// ----------------
/// @file       isoft_ctx_mac_hash_md5.cpp
/// @brief      AutoSar-Crypto Encryption and Decryption Module
/// @details
/// @date       2022-04-15
/// @author     Zheng Chang
/// @version    1.2.0
///
/// ================================================================
///
/// @code{.isoft}
/// @module_path=/CRYPTO/Default Encryption and Decryption/Message Authentication Code
/// @interface_level=unit
/// @trace_id_sr=SR_CRYPTO_01007
/// @unit_name=PCtxMacHashMd5
/// @unit_description=Hash MD5-based Message Authentication Code
/// @endcode
///
/// ================================================================

#include "ara/crypto/cryp/mac/isoft_ctx_mac_hash_md5.h"

#include "ara/crypto/cryp/cryobj/isoft_crypto_primitive_id.h"
#include "ara/crypto/cryp/cryobj/isoft_key_symmetric_aes.h"
#include "ara/crypto/cryp/hash/isoft_ctx_hash_function_md5.h"
#include "ara/crypto/cryp/isoft_crypto_provider.h"
#include "ara/crypto/cryp/isoft_service_digest_mac.h"

namespace ara {
namespace crypto {
namespace cryp {
namespace isoft_def {

/// @brief Get the MAC length
/// @name  GetMacLength
/// @returns MAC length
uint32_t PCtxMacHashMd5::GetMacLength() const noexcept { return static_cast< uint32_t >(sizeof(macData_)); }

/// @brief Return a CryptoPrimitivId instance containing the instance identifier.
/// @brief [SWS_CRYPT_01208] If the signature object is generated by a plain hash function, the dependent COUID of the "signature" should be set to the COUID of the context used
/// @name  GetCryptoPrimitiveId
/// @returns CryptoPrimitiveId instance
CryptoPrimitiveId::Uptr PCtxMacHashMd5::GetCryptoPrimitiveId() const noexcept
{
    return {std::make_unique< PAlgId_MacHashMd5 >()};
}

/// @brief Get the hash algorithm ID of the digest information, using md5 here
/// @brief [SWS_CRYPT_01208] If the signature object is generated by a hash function, the hash algorithm ID field of the signature should be set according to the algorithm ID used
/// @return Hash algorithm ID
CryptoPrimitiveId::AlgId PCtxMacHashMd5::GetHashAlgId() const noexcept
{
    return static_cast< CryptoAlgId >(cryp::isoft_def::EPhCtxTypeID::kHashMd5);
}

}  // namespace  isoft_def
}  // namespace cryp
}  // namespace crypto
}  // namespace ara