// Disclaimer
//
// This work (specification and/or software implementation) and the material
// contained in it, as released by AUTOSAR, is for the purpose of information
// only. AUTOSAR and the companies that have contributed to it shall not be
// liable for any use of the work.
//
// The material contained in this work is protected by copyright and other
// types of intellectual property rights. The commercial exploitation of the
// material contained in this work requires a license to such intellectual
// property rights.
//
// This work may be utilized or reproduced without any modification, in any
// form or by any means, for informational purposes only. For any other
// purpose, no part of the work may be utilized or reproduced, in any form
// or by any means, without permission in writing from the publisher.
//
// The work has been developed for automotive applications only. It has
// neither been developed, nor tested for non-automotive applications.
//
// The word AUTOSAR and the AUTOSAR logo are registered trademarks.
// --------------------------------------------------------------------------

/// ================================================================
///
/// File description:
/// ----------------
/// @file       isoft_ctx_mac_aes_cbc.cpp
/// @brief      AutoSar-Crypto Encryption and Decryption Module
/// @details
/// @date       2022-04-15
/// @author     Zheng Chang
/// @version    1.2.0
///
/// ================================================================
///
/// @code{.isoft}
/// @module_path=/CRYPTO/Default Encryption and Decryption/Message Authentication Code
/// @interface_level=unit
/// @trace_id_sr=SR_CRYPTO_01005
/// @unit_name=PCtxMacAesCbc_128
/// @unit_description=AES-CBC-128-based Message Authentication Code Context
/// @endcode
///
/// ================================================================

#include "ara/crypto/cryp/mac/isoft_ctx_mac_aes_cbc.h"

#include "ara/crypto/cryp/cryobj/isoft_crypto_primitive_id.h"
#include "ara/crypto/cryp/cryobj/isoft_key_symmetric_aes.h"
#include "ara/crypto/cryp/isoft_crypto_provider.h"
#include "ara/crypto/cryp/isoft_service_digest_mac.h"

namespace ara {
namespace crypto {
namespace cryp {
namespace isoft_def {

///****************/// PCtxMacAesCbc_128
/// @brief Get the EVP_CIPHER structure pointer
/// @name  GetEvpCipher
/// @returns EVP_CIPHER structure pointer
EVP_CIPHER const* PCtxMacAesCbc_128::GetEvpCipher() const noexcept { return EVP_aes_128_cbc(); }
/// @brief Return a CryptoPrimitivId instance containing the instance identifier.
/// @brief [SWS_CRYPT_01209] If the signature object is generated by a keyed MAC/HMAC/AE/AEAD algorithm, the dependent COUID of the signature
/// should be set to the COUID of the symmetric key used
/// @name  GetCryptoPrimitiveId
/// @returns CryptoPrimitiveId instance
CryptoPrimitiveId::Uptr PCtxMacAesCbc_128::GetCryptoPrimitiveId() const noexcept
{
    return {std::make_unique< PAlgId_MacAesCbc_128 >()};
}
/// @brief Check the key
/// @name  CheckKey
/// @param key Symmetric key
/// @returns  true if check key sucess false otherwise
bool PCtxMacAesCbc_128::CheckKey(SymmetricKey const& key) const noexcept
{
    PAlgId_Symmetric_AesKey128 const cryptoKey;
    return cryptoKey.IsMinePrimitiveId(key.GetCryptoPrimitiveId()->GetPrimitiveId());
}
///****************/// PCtxMacAesCbc_192
/// @brief Get the EVP_CIPHER structure pointer
/// @return EVP_CIPHER structure pointer
EVP_CIPHER const* PCtxMacAesCbc_192::GetEvpCipher() const noexcept { return EVP_aes_192_cbc(); }
/// @brief Return a CryptoPrimitivId instance containing the instance identifier.
/// @brief [SWS_CRYPT_01209] If the signature object is generated by a keyed MAC/HMAC/AE/AEAD algorithm, the dependent COUID of the signature
/// should be set to the COUID of the symmetric key used
/// @return Crypto primitive ID
CryptoPrimitiveId::Uptr PCtxMacAesCbc_192::GetCryptoPrimitiveId() const noexcept
{
    return {std::make_unique< PAlgId_MacAesCbc_192 >()};
}
/// @brief Check the key
/// @param key Symmetric key
/// @return true if check key sucess false otherwise
bool PCtxMacAesCbc_192::CheckKey(SymmetricKey const& key) const noexcept
{
    PAlgId_Symmetric_AesKey192 const cryptoKey;
    return cryptoKey.IsMinePrimitiveId(key.GetCryptoPrimitiveId()->GetPrimitiveId());
}
///****************/// PCtxMacAesCbc_256
/// @brief Get the EVP_CIPHER structure pointer
/// @return EVP_CIPHER structure pointer
EVP_CIPHER const* PCtxMacAesCbc_256::GetEvpCipher() const noexcept { return EVP_aes_256_cbc(); }
/// @brief Return a CryptoPrimitivId instance containing the instance identifier.
/// @brief [SWS_CRYPT_01209] If the signature object is generated by a keyed MAC/HMAC/AE/AEAD algorithm, the dependent COUID of the signature
/// should be set to the COUID of the symmetric key used
/// @return CryptoPrimitiveId instance
CryptoPrimitiveId::Uptr PCtxMacAesCbc_256::GetCryptoPrimitiveId() const noexcept
{
    return {std::make_unique< PAlgId_MacAesCbc_256 >()};
}
/// @brief Check the key
/// @param key Symmetric key
/// @return true if check key sucess false otherwise
bool PCtxMacAesCbc_256::CheckKey(SymmetricKey const& key) const noexcept
{
    PAlgId_Symmetric_AesKey256 const cryptoKey;
    return cryptoKey.IsMinePrimitiveId(key.GetCryptoPrimitiveId()->GetPrimitiveId());
}
///****************/
}  // namespace  isoft_def
}  // namespace cryp
}  // namespace crypto
}  // namespace ara
