// Disclaimer
//
// This work (specification and/or software implementation) and the material
// contained in it, as released by AUTOSAR, is for the purpose of information
// only. AUTOSAR and the companies that have contributed to it shall not be
// liable for any use of the work.
//
// The material contained in this work is protected by copyright and other
// types of intellectual property rights. The commercial exploitation of the
// material contained in this work requires a license to such intellectual
// property rights.
//
// This work may be utilized or reproduced without any modification, in any
// form or by any means, for informational purposes only. For any other
// purpose, no part of the work may be utilized or reproduced, in any form
// or by any means, without permission in writing from the publisher.
//
// The work has been developed for automotive applications only. It has
// neither been developed, nor tested for non-automotive applications.
//
// The word AUTOSAR and the AUTOSAR logo are registered trademarks.
// --------------------------------------------------------------------------

/// ================================================================
///
/// File description:
/// ----------------
/// @file       isoft_ctx_mac_hash_sha.cpp
/// @brief      AutoSar-Crypto Encryption and Decryption Module
/// @details
/// @date       2022-04-15
/// @author     Zheng Chang
/// @version    1.2.0
///
/// ================================================================
///
/// @code{.isoft}
/// @module_path=/CRYPTO/Default Encryption and Decryption/Message Authentication Code
/// @interface_level=unit
/// @trace_id_sr=SR_CRYPTO_01007
/// @unit_name=PCtxMacHashSha1
/// @unit_description=SHA1-based Message Authentication Code
/// @endcode
///
/// ================================================================

#include "ara/crypto/cryp/mac/isoft_ctx_mac_hash_sha.h"

#include "ara/crypto/cryp/cryobj/isoft_crypto_primitive_id.h"
#include "ara/crypto/cryp/cryobj/isoft_key_symmetric_aes.h"
#include "ara/crypto/cryp/hash/isoft_ctx_hash_function_sha.h"
#include "ara/crypto/cryp/isoft_crypto_provider.h"
#include "ara/crypto/cryp/isoft_service_digest_mac.h"

namespace ara {
namespace crypto {
namespace cryp {
namespace isoft_def {
// PCtxMacHashSha1
/// @brief Get the MAC result length
/// @name  GetMacLength
/// @returns MAC result length
uint32_t PCtxMacHashSha1::GetMacLength() const noexcept { return static_cast< uint32_t >(sizeof(macData_)); }

/// @brief Return a CryptoPrimitivId instance containing the instance identifier.
/// @brief [SWS_CRYPT_01208] If the signature object is generated by a plain hash function, the dependent COUID of the "signature" should be set to the COUID of the context used
/// @name  GetCryptoPrimitiveId
/// @returns CryptoPrimitiveId instance
CryptoPrimitiveId::Uptr PCtxMacHashSha1::GetCryptoPrimitiveId() const noexcept
{
    return {std::make_unique< PAlgId_MacHashSha1 >()};
}
/// @brief Get the hash algorithm ID of the digest information, here it is sha1
/// @brief [SWS_CRYPT_01208] If the signature object is generated by a hash function, the hash algorithm ID field of the signature should be set according to the algorithm ID used
/// @return Crypto primitive ID of the hash algorithm
CryptoPrimitiveId::AlgId PCtxMacHashSha1::GetHashAlgId() const noexcept
{
    PCtxHashFunctionSha1 const hashCtxSha1{cryptoProvider_};
    return hashCtxSha1.GetCryptoPrimitiveId()->GetPrimitiveId();
}

/****************/  // PCtxMacHashSha2_224
/// @brief Get the MAC result length
/// @return MAC result length
uint32_t PCtxMacHashSha2_224::GetMacLength() const noexcept { return static_cast< uint32_t >(sizeof(macData_)); }

/// @brief Return a CryptoPrimitivId instance containing the instance identifier.
/// @brief [SWS_CRYPT_01208] If the signature object is generated by a plain hash function, the dependent COUID of the "signature" should be set to the COUID of the context used
/// @return CryptoPrimitivId instance
CryptoPrimitiveId::Uptr PCtxMacHashSha2_224::GetCryptoPrimitiveId() const noexcept
{
    return {std::make_unique< PAlgId_MacHashSha2_224 >()};
}

/// @brief Get the hash algorithm ID of the digest information, here it is sha2_224
/// @brief [SWS_CRYPT_01208] If the signature object is generated by a hash function, the hash algorithm ID field of the signature should be set according to the algorithm ID used
/// @return Crypto primitive ID of the hash algorithm used by MAC
CryptoPrimitiveId::AlgId PCtxMacHashSha2_224::GetHashAlgId() const noexcept
{
    PCtxHashFunctionSha2_224 const hashCtxSha224{cryptoProvider_};
    return hashCtxSha224.GetCryptoPrimitiveId()->GetPrimitiveId();
}

///****************/// PCtxMacHashSha2_256
/// @brief Get the MAC result length
/// @return MAC result length
uint32_t PCtxMacHashSha2_256::GetMacLength() const noexcept { return static_cast< uint32_t >(sizeof(macData_)); }

/// @brief Return a CryptoPrimitivId instance containing the instance identifier.
/// @brief [SWS_CRYPT_01208] If the signature object is generated by a plain hash function, the dependent COUID of the "signature" should be set to the COUID of the context used
/// @return CryptoPrimitivId instance
CryptoPrimitiveId::Uptr PCtxMacHashSha2_256::GetCryptoPrimitiveId() const noexcept
{
    return {std::make_unique< PAlgId_MacHashSha2_256 >()};
}
/// @brief Get the hash algorithm ID of the digest information, here it is sha2_224
/// @brief [SWS_CRYPT_01208] If the signature object is generated by a hash function, the hash algorithm ID field of the signature should be set according to the algorithm ID used
/// @return Crypto primitive ID of the hash algorithm used by MAC
CryptoPrimitiveId::AlgId PCtxMacHashSha2_256::GetHashAlgId() const noexcept
{
    PCtxHashFunctionSha2_256 const hashCtxSha256{cryptoProvider_};
    return hashCtxSha256.GetCryptoPrimitiveId()->GetPrimitiveId();
}
///****************/// PCtxMacHashSha2_384
/// @brief Get the MAC result length
/// @return MAC result length
uint32_t PCtxMacHashSha2_384::GetMacLength() const noexcept { return static_cast< uint32_t >(sizeof(macData_)); }

/// @brief Return a CryptoPrimitivId instance containing the instance identifier.
/// @brief [SWS_CRYPT_01208] If the signature object is generated by a plain hash function, the dependent COUID of the "signature" should be set to the COUID of the context used
/// @return CryptoPrimitivId instance
CryptoPrimitiveId::Uptr PCtxMacHashSha2_384::GetCryptoPrimitiveId() const noexcept
{
    return {std::make_unique< PAlgId_MacHashSha2_384 >()};
}
/// @brief Get the hash algorithm ID of the digest information, here it is sha2_384
/// @brief [SWS_CRYPT_01208] If the signature object is generated by a hash function, the hash algorithm ID field of the signature should be set according to the algorithm ID used
/// @return Crypto primitive ID of the hash algorithm used by MAC
CryptoPrimitiveId::AlgId PCtxMacHashSha2_384::GetHashAlgId() const noexcept
{
    PCtxHashFunctionSha2_384 const hashCtxSha384{cryptoProvider_};
    return hashCtxSha384.GetCryptoPrimitiveId()->GetPrimitiveId();
}

///****************/// PCtxMacHashSha2_512
/// @brief Get the MAC result length
/// @return MAC result length
uint32_t PCtxMacHashSha2_512::GetMacLength() const noexcept { return static_cast< uint32_t >(sizeof(macData_)); }

/// @brief Return a CryptoPrimitivId instance containing the instance identifier.
/// @brief [SWS_CRYPT_01208] If the signature object is generated by a plain hash function, the dependent COUID of the "signature" should be set to the COUID of the context used
/// @return CryptoPrimitivId instance
CryptoPrimitiveId::Uptr PCtxMacHashSha2_512::GetCryptoPrimitiveId() const noexcept
{
    return {std::make_unique< PAlgId_MacHashSha2_512 >()};
}
/// @brief Get the hash algorithm ID of the digest information, here it is sha2_512
/// @brief [SWS_CRYPT_01208] If the signature object is generated by a hash function, the hash algorithm ID field of the signature should be set according to the algorithm ID used
/// @return Crypto primitive ID of the hash algorithm used by MAC
CryptoPrimitiveId::AlgId PCtxMacHashSha2_512::GetHashAlgId() const noexcept
{
    PCtxHashFunctionSha2_512 const hashCtxSha512{cryptoProvider_};
    return hashCtxSha512.GetCryptoPrimitiveId()->GetPrimitiveId();
}

}  // namespace  isoft_def
}  // namespace cryp
}  // namespace crypto
}  // namespace ara