// Disclaimer
//
// This work (specification and/or software implementation) and the material
// contained in it, as released by AUTOSAR, is for the purpose of information
// only. AUTOSAR and the companies that have contributed to it shall not be
// liable for any use of the work.
//
// The material contained in this work is protected by copyright and other
// types of intellectual property rights. The commercial exploitation of the
// material contained in this work requires a license to such intellectual
// property rights.
//
// This work may be utilized or reproduced without any modification, in any
// form or by any means, for informational purposes only. For any other
// purpose, no part of the work may be utilized or reproduced, in any form
// or by any means, without permission in writing from the publisher.
//
// The work has been developed for automotive applications only. It has
// neither been developed, nor tested for non-automotive applications.
//
// The word AUTOSAR and the AUTOSAR logo are registered trademarks.
// --------------------------------------------------------------------------

/// ================================================================
///
/// File description:
/// ----------------
/// @file       conversation_manager_proxy.h
/// @brief      Generated by RPC script from API define.
/// @details
/// @date       2024-12-18
/// @author     kai.ju
/// @version    1.2.0
///
/// ================================================================

#ifndef __GEN_CONVERSATIONMANAGER_PROXY__
#define __GEN_CONVERSATIONMANAGER_PROXY__

#include <functional>

#include "ara/core/future.h"
#include "gen_code/defines.h"
#include "netProxy/bussiness_service_proxy.h"
#include "netProxy/rpc_define.h"

namespace isoft {
namespace dm {
namespace dis {

class ConversationManagerProxy : public BussinessServiceProxy
{
public:
    explicit ConversationManagerProxy(uint32_t const& serviceInstanceId);

    void RegisterGetConversationNumberCallback(std::function< std::uint8_t() > callback) noexcept;

    void RegisterGetActiveStatusCallback(std::function< std::uint8_t(std::uint8_t) > callback) noexcept;

    void RegisterGetSessionIdCallback(std::function< std::uint8_t() > callback) noexcept;

    void RegisterGetSecurityLevelIdCallback(std::function< std::uint8_t() > callback) noexcept;

    void RegisterGetIdentifierCallback(std::function< std::uint64_t(std::uint8_t) > callback) noexcept;

    void RegisterGetDiagnosticSessionShortNameCallback(
        std::function< ara::core::StringView(std::uint8_t) > callback) noexcept;

    void RegisterGetDiagnosticSecurityLevelShortNameCallback(
        std::function< ara::core::StringView(std::uint8_t) > callback) noexcept;

    void RegisterResetToDefaultSessionCallback(std::function< void() > callback) noexcept;

    void UpdateActiveState(std::uint8_t index, std::uint8_t activeStatus) noexcept;

    void UpdateSessionId(std::uint8_t sessionId) noexcept;

    void UpdateSecurityLevelId(std::uint8_t securityLevelId) noexcept;

private:
    void CallHandle(CallRequest&& callData) override;

    void _getConversationNumber(CallRequest&& callData) noexcept;

    void _getActiveStatus(CallRequest&& callData);

    void _getSessionId(CallRequest&& callData);

    void _getSecurityLevelId(CallRequest&& callData);

    void _getIdentifier(CallRequest&& callData);

    void _getDiagnosticSessionShortName(CallRequest&& callData);

    void _getDiagnosticSecurityLevelShortName(CallRequest&& callData);

    void _resetToDefaultSession(CallRequest&& callData);

    void _updateActiveState(CallRequest&& callData);

    void _updateSessionId(CallRequest&& callData);

    void _updateSecurityLevelId(CallRequest&& callData);

private:
    std::function< std::uint8_t() > getConversationNumberCallback_;
    std::function< std::uint8_t(std::uint8_t) > getActiveStatusCallback_;
    std::function< std::uint8_t() > getSessionIdCallback_;
    std::function< std::uint8_t() > getSecurityLevelIdCallback_;
    std::function< std::uint64_t(std::uint8_t) > getIdentifierCallback_;
    std::function< ara::core::StringView(std::uint8_t) > getDiagnosticSessionShortNameCallback_;
    std::function< ara::core::StringView(std::uint8_t) > getDiagnosticSecurityLevelShortNameCallback_;
    std::function< void() > resetToDefaultSessionCallback_;
};

}  // namespace dis
}  // namespace dm
}  // namespace isoft

#endif  // __GEN_CONVERSATIONMANAGER_PROXY__