// Disclaimer
//
// This work (specification and/or software implementation) and the material
// contained in it, as released by AUTOSAR, is for the purpose of information
// only. AUTOSAR and the companies that have contributed to it shall not be
// liable for any use of the work.
//
// The material contained in this work is protected by copyright and other
// types of intellectual property rights. The commercial exploitation of the
// material contained in this work requires a license to such intellectual
// property rights.
//
// This work may be utilized or reproduced without any modification, in any
// form or by any means, for informational purposes only. For any other
// purpose, no part of the work may be utilized or reproduced, in any form
// or by any means, without permission in writing from the publisher.
//
// The work has been developed for automotive applications only. It has
// neither been developed, nor tested for non-automotive applications.
//
// The word AUTOSAR and the AUTOSAR logo are registered trademarks.
// --------------------------------------------------------------------------

/// ================================================================
///
/// File description:
/// ----------------
/// @file       shared_ptr_manager.h
/// @brief      AutoSar-AP Data Persistence Storage Module
/// @details    Map template for saving SharedHandle pointers generated by the Per module
/// @date       2021-06-09
/// @author     hanjingjing
/// @version    1.2.0
///
/// ================================================================
///
/// @code{.isoft}
/// @module_path=/per/Common/Reusable Features
/// @interface_level=module
/// @trace_id_sr=
/// @unit_name=PSharedPtrManager
/// @unit_description=Map template for saving SharedHandle pointers generated by the Per module
/// @endcode
///
/// ================================================================
///
/// @par Modification Log:
/// <table>
/// <tr><th>Date        <th>Version  <th>Author      <th>Description
/// | 2021-06-09 | 1.0.0   | hanjingjing  | Initial version created                   |
/// | 2021-08-30 | 1.0.0   | hanjingjing  | Integrated PHKV implementation into AutoSar interface |
///
/// ================================================================

#ifndef ARA_PER_PHKV_KV_SHARED_PTR_MANAGER_H_
#define ARA_PER_PHKV_KV_SHARED_PTR_MANAGER_H_

#include <mutex>

#include "ara/core/map.h"
#include "ara/core/string.h"
#include "ara/core/string_view.h"

namespace ara {
namespace per {
namespace isoftkv {

/// @brief
/// @tparam T_Storage
template < typename T_Storage >
/// @brief
/// @tparam T_Storage
class PSharedPtrManager final
{
private:
    /// @brief
    ara::core::Map< ara::core::String, std::weak_ptr< T_Storage > > mapInstances_;
    /// @brief
    mutable std::recursive_mutex guard_;

public:
    /// @brief Find
    /// @param stSpecifier
    /// @return
    /// @throws
    std::shared_ptr< T_Storage > Find(ara::core::String const& stSpecifier)
    {
        std::lock_guard< std::recursive_mutex > const lock{guard_};
        typename ara::core::Map< ara::core::String, std::weak_ptr< T_Storage > >::iterator itFind;
        itFind = mapInstances_.find(stSpecifier);
        if (itFind != mapInstances_.end()) {
            if (!itFind->second.expired()) {
                return itFind->second.lock();
            }
        }
        return std::move(std::shared_ptr< T_Storage >{nullptr});
    }
    /// @brief Register
    /// @param stSpecifier
    /// @param pSharedHandle
    /// @return
    /// @throws
    std::shared_ptr< T_Storage > Reg(ara::core::String const& stSpecifier,
                                     std::shared_ptr< T_Storage > const& pSharedHandle)
    {
        std::lock_guard< std::recursive_mutex > const lock{guard_};
        ara::core::String const stSharedName{stSpecifier};
        typename ara::core::Map< ara::core::String, std::weak_ptr< T_Storage > >::iterator itFind;
        itFind = mapInstances_.find(stSharedName);
        if (itFind != mapInstances_.end()) {
            if (!itFind->second.expired()) {
                return itFind->second.lock();
            }
        }
        mapInstances_[stSharedName] = pSharedHandle;
        return pSharedHandle;
    }
    /// @brief Unregister
    /// @param stSpecifier
    /// @throws
    void Deg(ara::core::String const& stSpecifier)
    {
        std::lock_guard< std::recursive_mutex > const lock{guard_};
        typename ara::core::Map< ara::core::String, std::weak_ptr< T_Storage > >::iterator itFind;
        itFind = mapInstances_.find(stSpecifier);
        if (itFind != mapInstances_.end()) {
            if (itFind->second.expired()) {
                std::ignore = mapInstances_.erase(itFind);
            }
        }
    }
    /// @brief Check if a valid pointer exists
    /// @param stSpecifier
    /// @return
    /// @throws
    bool HasObject(ara::core::String const& stSpecifier) const
    {
        std::lock_guard< std::recursive_mutex > const lock{guard_};
        ara::core::String const stN{stSpecifier};
        typename ara::core::Map< ara::core::String, std::weak_ptr< T_Storage > >::const_iterator itFind;
        itFind = mapInstances_.find(stN);
        if (itFind == mapInstances_.end()) {
            return false;
        }
        if (!itFind->second.expired()) {
            return false;
        }
        return true;
    }
};
}  // namespace isoftkv
}  // namespace per
}  // namespace ara

#endif  // ARA_PER_UTILITY_SHARED_OBJECTS_REGISTRY_H_
