// Disclaimer
//
// This work (specification and/or software implementation) and the material
// contained in it, as released by AUTOSAR, is for the purpose of information
// only. AUTOSAR and the companies that have contributed to it shall not be
// liable for any use of the work.
//
// The material contained in this work is protected by copyright and other
// types of intellectual property rights. The commercial exploitation of the
// material contained in this work requires a license to such intellectual
// property rights.
//
// This work may be utilized or reproduced without any modification, in any
// form or by any means, for informational purposes only. For any other
// purpose, no part of the work may be utilized or reproduced, in any form
// or by any means, without permission in writing from the publisher.
//
// The work has been developed for automotive applications only. It has
// neither been developed, nor tested for non-automotive applications.
//
// The word AUTOSAR and the AUTOSAR logo are registered trademarks.
// --------------------------------------------------------------------------

/// ================================================================
///
/// File description:
/// ----------------
/// @file       raw_data_identifier_agent.h
/// @brief      Generated by RPC script from API define.
/// @details
/// @date       2024-12-28
/// @author     kai.ju
/// @version    1.2.0
///
/// ================================================================

#ifndef __GEN_SERVICEAGENT_RAWDATAIDENTIFIEAGENT__
#define __GEN_SERVICEAGENT_RAWDATAIDENTIFIEAGENT__

#include <functional>

#include "ara/core/future.h"
#include "gen_code/defines.h"
namespace isoft {
namespace dm {

class CancellationEvent;
namespace dic {
class RawDataIdentifierProxy;

class RawDataIdentifierAgent
{
public:
    ara::core::Future< ara::core::Vector< std::uint8_t > > Read(MetaInfoMap const& metaInfo,
                                                                std::shared_ptr< CancellationEvent >& cancelEventPtr);

    ara::core::Future< void > Write(ara::core::Vector< std::uint8_t > requestData,
                                    MetaInfoMap const& metaInfo,
                                    std::shared_ptr< CancellationEvent >& cancelEventPtr);

public:
    explicit RawDataIdentifierAgent(uint16_t const& instanceId, uint32_t const& serviceInstanceId);

private:
    std::shared_ptr< RawDataIdentifierProxy > proxy_{nullptr};
};

}  // namespace dic
}  // namespace dm
}  // namespace isoft

#endif  // __GEN_SERVICEAGENT_RAWDATAIDENTIFIEAGENT__