#  Disclaimer
#
#  This work (specification and/or software implementation) and the material
#  contained in it, as released by AUTOSAR, is for the purpose of information
#  only. AUTOSAR and the companies that have contributed to it shall not be
#  liable for any use of the work.
#
#  The material contained in this work is protected by copyright and other
#  types of intellectual property rights. The commercial exploitation of the
#  material contained in this work requires a license to such intellectual
#  property rights.
#
#  This work may be utilized or reproduced without any modification, in any
#  form or by any means, for informational purposes only. For any other
#  purpose, no part of the work may be utilized or reproduced, in any form
#  or by any means, without permission in writing from the publisher.
#
#  The work has been developed for automotive applications only. It has
#  neither been developed, nor tested for non-automotive applications.
#
#  The word AUTOSAR and the AUTOSAR logo are registered trademarks.
#  --------------------------------------------------------------------------

include(CMakeParseArguments)

if(NOT PYTHON_EXECUTABLE)
	find_package(PythonInterp 3.8)
endif()

if(NOT ARAGEN_PATH)
	set(ARAGEN_PATH ${ARA_ARAGEN_SCRIPT})
endif()

if(NO_REFERENCE_CHECKING)
        set(SKIP_RC_OPTION "--no-reference-checking")
else()
        set(SKIP_RC_OPTION "")
endif()

if(ENABLE_SINGLE_PRCESS_MODE)
	set(SINGLE_PRCESS_MODE "--single-process")
else()
	set(SINGLE_PRCESS_MODE"")
endif()

# Configure naming convention for elements generated by SOA code generator:
# Empty string "" follows the AUTOSAR standard naming rule;
# Value "inside" means prepending the Service name as prefix to elements to prevent naming conflicts.
if(SOA_ELEMENT_CPP_DEF_STYLE)
	set(SOA_ELEMENT_CPP_DEF_STYLE "--soa-element-cpp-def-style=${SOA_ELEMENT_CPP_DEF_STYLE}")
else()
	set(SOA_ELEMENT_CPP_DEF_STYLE "")
endif()

if(USE_NSOMEIP2)
        set(SOMEIP_LIBS_OPTION "--someip-libs=nsomeip2")
        set(SOMEIP_COMPILER_DEFINE "-DHAS_NSOMEIP_BINDING")
else()
        set(SOMEIP_LIBS_OPTION "")
        set(SOMEIP_COMPILER_DEFINE "")
endif()


if(USE_FASTDDS)
	set(DDS_LIBS_OPTION "--dds-libs=fastdds")
	set(DDS_COMPILER_DEFINE "-DHAS_FASTDDS_BINDING")
endif()


if(HAS_NPC_BINDING)
	set(IPC_LIBS_OPTION "--ipc-libs=npc")
	set(IPC_COMPILER_DEFINE "-DHAS_NPC_BINDING")
endif()
if(HAS_ICC_BINDING)
	set(ICC_LIBS_OPTION "--icc-libs=icc")
	set(ICC_COMPILER_DEFINE "-DHAS_ICC_BINDING")
endif()

# gen code 
function(add_aragen)
	set(options ALL FORCE_PKGPATH_FALLBACK)
	set(oneValueArgs DESTINATION  EXECUTABLE SCHEMA TARGET)
	set(multiValueArgs PROCESS_FQN  ARXMLS)
	cmake_parse_arguments(add_aragen_ARGS "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

	set(add_aragen_COMMON_ARGS
		${SKIP_RC_OPTION}
		${SINGLE_PRCESS_MODE}
		-o ${add_aragen_ARGS_DESTINATION}
		-g CODE
		${add_aragen_PKGPATH_ARGUMENT}
		${SOMEIP_LIBS_OPTION}
		${DDS_LIBS_OPTION}
		${IPC_LIBS_OPTION}
		${ICC_LIBS_OPTION}
		${SOA_ELEMENT_CPP_DEF_STYLE}
	)

	if(add_aragen_ARGS_FORCE_PKGPATH_FALLBACK)
		set(add_aragen_COMMON_ARGS ${add_aragen_COMMON_ARGS} "--force-pkg-path-fallback")
	endif()

	if(DEFINED add_aragen_ARGS_PROCESS_FQN AND NOT ${add_aragen_ARGS_PROCESS_FQN} STREQUAL "Unknown" )
		string(JOIN "," process ${add_aragen_ARGS_PROCESS_FQN})
		set(add_aragen_COMMON_ARGS ${add_aragen_COMMON_ARGS} -p ${process})
	endif()

	if(DEFINED add_aragen_ARGS_EXECUTABLE AND NOT ${add_aragen_ARGS_EXECUTABLE} STREQUAL "Unknown" )
		set(add_aragen_COMMON_ARGS ${add_aragen_COMMON_ARGS} -e ${add_aragen_ARGS_EXECUTABLE})
	endif()

	if(DEBUG_ARA_GEN)
		set(command_line --list-files ${add_aragen_COMMON_ARGS} ${add_aragen_ARGS_ARXMLS})
		string(JOIN " " command_line ${command_line})
		message(STATUS "add_aragen aragen command:${ARAGEN_PATH} ${command_line}")
	endif()

	execute_process(
		COMMAND
		${ARAGEN_PATH}
		--list-files
		${add_aragen_COMMON_ARGS}
		${add_aragen_ARGS_ARXMLS}
		ERROR_VARIABLE aragen_errors
		OUTPUT_VARIABLE aragen_outputs
		RESULT_VARIABLE aragen_return
		WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
	)
	if(NOT aragen_return EQUAL 0)
		message(STATUS "aragen_outputs: ${aragen_outputs}")
		message(STATUS "aragen_errors: ${aragen_errors}")
		message(FATAL_ERROR "aragen failed!")
	endif()

	# 将目录换到文件，因为目录内文件的变化不会触发修改重编译
	set(_ARXML_FILES )
	FOREACH(it ${add_aragen_ARGS_ARXMLS})
	string(TOLOWER ${it} _it2)
	if(${_it2} MATCHES ".*\\.arxml")
			list(APPEND _ARXML_FILES ${it}) 
	else()
			string(CONCAT _FIND ${it} "/*.arxml")
			file(GLOB_RECURSE _Ret_GetArxmlsFromDIR ${_FIND}) 
			list(APPEND _ARXML_FILES ${_Ret_GetArxmlsFromDIR})
	endif()
	ENDFOREACH(it)
	list(REMOVE_DUPLICATES _ARXML_FILES)
	# Add input .arxmls to the list of input files to the configuration process.
	# This is needed so that CMake is re-run, if any of this files are changed,
	# because it might affect which output files the generator produces.
	set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${_ARXML_FILES})
	# Export the list of files (sources and headers) to the caller
	set(aragen_hdrs)
	set(aragen_srcs)
	set(aragen_idls)
	foreach(f IN LISTS aragen_outputs)
		if(f MATCHES ".*\\.h")
			list(APPEND aragen_hdrs ${f})
		elseif(f MATCHES ".*\\.cpp")
			list(APPEND aragen_srcs ${f})
		elseif(f MATCHES ".*\\.idl")
			list(APPEND aragen_idls ${f})
		endif()
	endforeach()
	set(${add_aragen_ARGS_TARGET}_HEADERS ${aragen_hdrs} PARENT_SCOPE)
	set(${add_aragen_ARGS_TARGET}_SOURCES ${aragen_srcs} PARENT_SCOPE)
	set(${add_aragen_ARGS_TARGET}_IDLS ${aragen_idls} PARENT_SCOPE)

	# Finally setup custom command/target for invoking the generator
	# (this will happen during build, i.e. upon `make' invocation)
	add_custom_command(
		OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/${add_aragen_ARGS_TARGET}.stamp
		COMMAND
		${ARAGEN_PATH}
		${add_aragen_COMMON_ARGS}
		${add_aragen_VALIDATE_ARGUMENT}
		${add_aragen_ARGS_ARXMLS}
		COMMAND
		${CMAKE_COMMAND} -E touch ${CMAKE_CURRENT_BINARY_DIR}/${add_aragen_ARGS_TARGET}.stamp
		DEPENDS ${_ARXML_FILES}
		BYPRODUCTS ${aragen_outputs}
		WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
	)

	if(add_aragen_ARGS_ALL)
		set(add_aragen_ALL_VALUE "ALL")
	else()
		set(add_aragen_ALL_VALUE "")
	endif()
	add_custom_target(${add_aragen_ARGS_TARGET} ${add_aragen_ALL_VALUE} DEPENDS ${add_aragen_ARGS_TARGET}.stamp)
endfunction()

# gen process config(Execution Manifest)
function(add_em_gen)
	message(WARNING "!!!add_em_gen is removed!!! you can delete this function call or recreate project from IDE")
endfunction()


# gen code(gen fastdds code && include add_aragen) TODO add EXECUTABLE
function(add_fastdds)
	set(options "")
	set(oneValueArgs APP_NAME DESTINATION SCHEMA TARGET EXECUTABLE GENERATED_LIB)
	set(multiValueArgs PROCESS_FQN ARXMLS)

	cmake_parse_arguments(add_fastdds_ARGS "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

	set(GENERATED_TARGET ${add_fastdds_ARGS_APP_NAME}Generated)
	set(FASTDDS_GENERATED_LIB ${add_fastdds_ARGS_TARGET}Lib)
	set(FASTDDS_GEN_DEST ${add_fastdds_ARGS_DESTINATION}/net-bindings/)
	set(ARA_GEN_INCLUDE_DEST ${add_fastdds_ARGS_DESTINATION}/includes)


	add_aragen(
		DESTINATION ${add_fastdds_ARGS_DESTINATION}
		TARGET ${add_fastdds_ARGS_TARGET}
		PROCESS_FQN ${add_fastdds_ARGS_PROCESS_FQN}
		EXECUTABLE ${add_fastdds_ARGS_EXECUTABLE}
		ARXMLS ${add_fastdds_ARGS_ARXMLS}
	)

	find_path(FASTDDSGEN_DIR fastddsgen) 
	set(FASTDDSGEN_PATH ${FASTDDSGEN_DIR}/fastddsgen)
	set(fastdds_srcs)
	set(fastdds_idls)
	list(APPEND fastdds_srcs ${${add_fastdds_ARGS_TARGET}_SOURCES})
	set(_depends)
	#创建目录
	set(IDL_STAMP_DIR ${CMAKE_CURRENT_BINARY_DIR}/stamp)
	set(IDL_TMP_DIR ${CMAKE_CURRENT_BINARY_DIR}/tmp)
	execute_process( 
		COMMAND ${CMAKE_COMMAND} -E make_directory ${IDL_STAMP_DIR}
		COMMAND ${CMAKE_COMMAND} -E make_directory ${IDL_TMP_DIR}
		)
	if(FASTDDS_ROS2)
		set(FASTDDS_GEN_OPTS -replace -cs -typeros2 )
	else()
		set(FASTDDS_GEN_OPTS -replace -cs )
	endif()
	foreach(IDL_PATH IN LISTS ${add_fastdds_ARGS_TARGET}_IDLS)
		list(APPEND fastdds_idls  ${IDL_PATH})
		get_filename_component(IDL_DIR ${IDL_PATH} DIRECTORY)
		get_filename_component(IDL_NAME ${IDL_PATH} NAME)
		string(REPLACE ".idl" ".cxx" IDS_CXX1 ${IDL_PATH})
		string(REPLACE ".idl" "PubSubTypes.h" IDL_PUBSUBTYPES_H ${IDL_PATH})
		string(REPLACE ".idl" "PubSubTypes.cxx" IDS_CXX2 ${IDL_PATH})
		string(REPLACE ".idl" "TypeObjectSupport.cxx" IDS_TYPEOBJECTSUPPORT_CXX ${IDL_PATH})
		string(REPLACE ".idl" "CdrAux.hpp" IDS_CDRAUX_H ${IDL_PATH})


		list(APPEND fastdds_srcs ${IDS_CXX1})
		list(APPEND fastdds_srcs ${IDS_TYPEOBJECTSUPPORT_CXX})
		list(APPEND fastdds_srcs ${IDS_CXX2})

		execute_process( 
			COMMAND ${CMAKE_COMMAND} -E make_directory ${IDL_DIR}
		)

		execute_process( 
			COMMAND ${CMAKE_COMMAND} -E touch ${IDS_CXX1}
			COMMAND ${CMAKE_COMMAND} -E touch ${IDS_CXX2}
			COMMAND ${CMAKE_COMMAND} -E touch ${IDL_PUBSUBTYPES_H}
			COMMAND ${CMAKE_COMMAND} -E touch ${IDS_CDRAUX_H}
			COMMAND ${CMAKE_COMMAND} -E touch ${IDS_TYPEOBJECTSUPPORT_CXX}
			)
		add_custom_command(
			OUTPUT  ${IDL_STAMP_DIR}/${IDL_NAME}.stamp
			COMMAND
					${FASTDDSGEN_PATH} ${FASTDDS_GEN_OPTS} -t ${IDL_TMP_DIR} -I ${add_fastdds_ARGS_DESTINATION}/net-bindings/fastdds_idl ${IDL_PATH}
			COMMAND
				${CMAKE_COMMAND} -E touch ${IDL_STAMP_DIR}/${IDL_NAME}.stamp
			DEPENDS ${IDL_PATH}
			#BYPRODUCTS ${jsongen_outputs}
			WORKING_DIRECTORY "${add_fastdds_ARGS_DESTINATION}/net-bindings/"
		)
		list(APPEND _depends ${IDL_STAMP_DIR}/${IDL_NAME}.stamp)
	endforeach()

	add_custom_target(${helper_ARGS_TARGET}_IDLS ALL DEPENDS ${_depends} ${add_fastdds_ARGS_TARGET})
	add_library(${FASTDDS_GENERATED_LIB} OBJECT  ${add_fastdds_ARGS_DESTINATION}/helper_libary.cpp )
	add_dependencies(${FASTDDS_GENERATED_LIB} ${helper_ARGS_TARGET}_IDLS)
	target_compile_definitions(${FASTDDS_GENERATED_LIB} PRIVATE HAS_FASTDDS_BINDING)
	target_include_directories(${FASTDDS_GENERATED_LIB}
		PRIVATE ${ARA_GEN_INCLUDE_DEST}
				${CMAKE_CURRENT_SOURCE_DIR}
				${FASTDDS_GEN_DEST}
				${FASTDDS_GEN_DEST}/fastdds_idl
				${CMAKE_INSTALL_PREFIX}/include)

	set(${add_fastdds_ARGS_TARGET}_SOURCES  ${fastdds_srcs} PARENT_SCOPE)
endfunction()
